<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>musings of the Professor</title>
  <meta name="description" content="Weekly examples and musings related to PSYC 7014.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="musings of the Professor" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Weekly examples and musings related to PSYC 7014." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="musings of the Professor" />
  
  <meta name="twitter:description" content="Weekly examples and musings related to PSYC 7014." />
  

<meta name="author" content="Tehran J. Davis">


<meta name="date" content="2018-12-15">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="anova-iv-interactions-simple-effects.html">
<link rel="next" href="anova6-within-subjects.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Words from the Professor</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Weekly musings</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to R / getting to know your data</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-and-loading-an-r-package"><i class="fa fa-check"></i><b>1.1</b> Installing and loading an R package:</a><ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-a-package-using-the-gui"><i class="fa fa-check"></i><b>1.1.1</b> Installing a package using the GUI</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-packages-with-install.packages"><i class="fa fa-check"></i><b>1.1.2</b> Installing packages with <code>install.packages()</code></a></li>
<li class="chapter" data-level="1.1.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#an-important-note-on-knitting-with-install.packages"><i class="fa fa-check"></i><b>1.1.3</b> An IMPORTANT note on knitting with install.packages:</a></li>
<li class="chapter" data-level="1.1.4" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-packages-with-library"><i class="fa fa-check"></i><b>1.1.4</b> Loading packages with <code>library()</code></a></li>
<li class="chapter" data-level="1.1.5" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-packages-with-require"><i class="fa fa-check"></i><b>1.1.5</b> Loading packages with <code>require()</code></a></li>
<li class="chapter" data-level="1.1.6" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-and-loading-packages-like-a-ninja"><i class="fa fa-check"></i><b>1.1.6</b> Installing and loading packages like a ninja</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-in-data"><i class="fa fa-check"></i><b>1.2</b> Loading in data</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-in-local-data-using-a-gui"><i class="fa fa-check"></i><b>1.2.1</b> Loading in local data using a GUI:</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#importing-data-from-the-web"><i class="fa fa-check"></i><b>1.2.2</b> importing data from the web</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#downloading-data"><i class="fa fa-check"></i><b>1.2.3</b> Downloading data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#looking-ahead"><i class="fa fa-check"></i><b>1.3</b> Looking ahead…</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html"><i class="fa fa-check"></i><b>2</b> Measures of distribution, central tendency, PLOTS… oh my!</a><ul>
<li class="chapter" data-level="2.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#getting-measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Getting measures of central tendency</a></li>
<li class="chapter" data-level="2.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-the-distribution-with-a-histogram"><i class="fa fa-check"></i><b>2.2</b> Plotting the distribution with a histogram</a><ul>
<li class="chapter" data-level="2.2.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#using-hist"><i class="fa fa-check"></i><b>2.2.1</b> Using <code>hist()</code></a></li>
<li class="chapter" data-level="2.2.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-a-histogram-with-ggplot"><i class="fa fa-check"></i><b>2.2.2</b> Plotting a histogram with <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-your-data-in-a-boxplot"><i class="fa fa-check"></i><b>2.3</b> Plotting your data in a boxplot:</a><ul>
<li class="chapter" data-level="2.3.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#turning-numeric-data-into-categorical"><i class="fa fa-check"></i><b>2.3.1</b> turning numeric data into categorical</a></li>
<li class="chapter" data-level="2.3.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#boxplotting-using-ggplot"><i class="fa fa-check"></i><b>2.3.2</b> boxplotting using <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#assessing-the-data-for-normality"><i class="fa fa-check"></i><b>2.4</b> Assessing the data for normality</a><ul>
<li class="chapter" data-level="2.4.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#q-q-plots"><i class="fa fa-check"></i><b>2.4.1</b> Q-Q Plots</a></li>
<li class="chapter" data-level="2.4.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#generating-a-theoretical-normal-distribution."><i class="fa fa-check"></i><b>2.4.2</b> Generating a theoretical normal distribution.</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#subsetting-your-data"><i class="fa fa-check"></i><b>2.5</b> Subsetting your data</a></li>
<li class="chapter" data-level="2.6" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#looking-ahead-means-and-better-models"><i class="fa fa-check"></i><b>2.6</b> Looking ahead: Means and better models</a><ul>
<li class="chapter" data-level="2.6.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-highest-probability"><i class="fa fa-check"></i><b>2.6.1</b> mean as highest probability:</a></li>
<li class="chapter" data-level="2.6.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-fulcrum-point"><i class="fa fa-check"></i><b>2.6.2</b> mean as fulcrum point</a></li>
<li class="chapter" data-level="2.6.3" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-minimizing-random-error"><i class="fa fa-check"></i><b>2.6.3</b> mean as minimizing random error</a></li>
<li class="chapter" data-level="2.6.4" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#but-we-can-do-better-than-that"><i class="fa fa-check"></i><b>2.6.4</b> but we can do better than that</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html"><i class="fa fa-check"></i><b>3</b> Sampling distributions and building the logic of NHST</a><ul>
<li class="chapter" data-level="3.1" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-sampling-distribution"><i class="fa fa-check"></i><b>3.1</b> The sampling distribution</a></li>
<li class="chapter" data-level="3.2" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>3.2</b> Standard error of the mean</a></li>
<li class="chapter" data-level="3.3" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-difference-distribution"><i class="fa fa-check"></i><b>3.3</b> The difference distribution</a></li>
<li class="chapter" data-level="3.4" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-null-distribution"><i class="fa fa-check"></i><b>3.4</b> The Null distribution</a></li>
<li class="chapter" data-level="3.5" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#probabilty-of-observed-differences"><i class="fa fa-check"></i><b>3.5</b> Probabilty of observed differences</a></li>
<li class="chapter" data-level="3.6" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#a-note-about-sample-size"><i class="fa fa-check"></i><b>3.6</b> A note about sample size</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html"><i class="fa fa-check"></i><b>4</b> Probability and the Binomial Distribution</a><ul>
<li class="chapter" data-level="4.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#a-few-words-on-where-we-are-at-so-far"><i class="fa fa-check"></i><b>4.1</b> A few words on where we are at so far…</a></li>
<li class="chapter" data-level="4.2" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#okay-on-to-this-weeks-example-analyses"><i class="fa fa-check"></i><b>4.2</b> Okay on to this week’s example analyses:</a></li>
<li class="chapter" data-level="4.3" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#classic-example-the-coin-flip"><i class="fa fa-check"></i><b>4.3</b> Classic example: The coin flip</a><ul>
<li class="chapter" data-level="4.3.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#how-many-heads-would-we-get-if-we-flipped-a-fair-coin-10-times"><i class="fa fa-check"></i><b>4.3.1</b> How many heads would we get if we flipped a fair coin 10 times?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#changing-the-parameters"><i class="fa fa-check"></i><b>4.4</b> Changing the parameters</a><ul>
<li class="chapter" data-level="4.4.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#constructing-a-table-of-outcome-probabilities"><i class="fa fa-check"></i><b>4.4.1</b> Constructing a table of outcome probabilities:</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#assessing-cummulative-probability"><i class="fa fa-check"></i><b>4.4.2</b> Assessing cummulative probability</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#catching-a-cheat"><i class="fa fa-check"></i><b>4.5</b> Catching a cheat</a></li>
<li class="chapter" data-level="4.6" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#one-last-thing-permutations-combinations-and-building-functions"><i class="fa fa-check"></i><b>4.6</b> One last thing… Permutations, combinations, and building functions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html"><i class="fa fa-check"></i><b>5</b> Chi-square and associated methods</a><ul>
<li class="chapter" data-level="5.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#goodness-of-fit-test"><i class="fa fa-check"></i><b>5.1</b> Goodness of fit test</a><ul>
<li class="chapter" data-level="5.1.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#what-to-do-if-you-are-given-a-table-with-tallies"><i class="fa fa-check"></i><b>5.1.1</b> What to do if you are given a table with tallies</a></li>
<li class="chapter" data-level="5.1.2" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#assuming-all-things-are-not-equal"><i class="fa fa-check"></i><b>5.1.2</b> Assuming all things are NOT equal</a></li>
<li class="chapter" data-level="5.1.3" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#real-data-is-likely-not-pre-tallied"><i class="fa fa-check"></i><b>5.1.3</b> Real data is likely NOT pre-tallied</a></li>
<li class="chapter" data-level="5.1.4" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#getting-counts-the-in-class-way-not-recommended"><i class="fa fa-check"></i><b>5.1.4</b> getting counts the in-class way (not recommended)</a></li>
<li class="chapter" data-level="5.1.5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#getting-counts-the-table-way-my-new-recommendation"><i class="fa fa-check"></i><b>5.1.5</b> getting counts the <code>table()</code> way (my new recommendation)</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#contingency-table-analysis-in-r"><i class="fa fa-check"></i><b>5.2</b> Contingency Table Analysis in R</a><ul>
<li class="chapter" data-level="5.2.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#okay-but-what-about-with-real-data"><i class="fa fa-check"></i><b>5.2.1</b> Okay, but what about with REAL DATA:</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#effect-sizes-and-odds-ratios"><i class="fa fa-check"></i><b>5.3</b> Effect Sizes and Odds Ratios</a></li>
<li class="chapter" data-level="5.4" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#fishers-exact-test"><i class="fa fa-check"></i><b>5.4</b> Fisher’s exact test</a></li>
<li class="chapter" data-level="5.5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#cohens-kappa"><i class="fa fa-check"></i><b>5.5</b> Cohen’s kappa</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html"><i class="fa fa-check"></i><b>6</b> Correlation and Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#the-relationship-btw-stress-and-health"><i class="fa fa-check"></i><b>6.1</b> The Relationship b/tw Stress and Health</a><ul>
<li class="chapter" data-level="6.1.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#testing-our-assumptions"><i class="fa fa-check"></i><b>6.1.1</b> Testing our assumptions</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#plotting-the-data"><i class="fa fa-check"></i><b>6.2</b> Plotting the data</a></li>
<li class="chapter" data-level="6.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#covariance-and-correlation"><i class="fa fa-check"></i><b>6.3</b> Covariance and Correlation</a><ul>
<li class="chapter" data-level="6.3.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#covariance"><i class="fa fa-check"></i><b>6.3.1</b> Covariance</a></li>
<li class="chapter" data-level="6.3.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#correlation"><i class="fa fa-check"></i><b>6.3.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#sigfnificance-testing-r"><i class="fa fa-check"></i><b>6.4</b> Sigfnificance testing <span class="math inline">\(r\)</span></a></li>
<li class="chapter" data-level="6.5" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#fitting-the-data-to-a-model"><i class="fa fa-check"></i><b>6.5</b> Fitting the data to a model</a></li>
<li class="chapter" data-level="6.6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#linear-models-in-r"><i class="fa fa-check"></i><b>6.6</b> Linear models in R</a><ul>
<li class="chapter" data-level="6.6.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#attributes-of-class-lm"><i class="fa fa-check"></i><b>6.6.1</b> Attributes of class <code>lm</code>:</a></li>
<li class="chapter" data-level="6.6.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#testing-the-residuals"><i class="fa fa-check"></i><b>6.6.2</b> Testing the residuals</a></li>
<li class="chapter" data-level="6.6.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#using-your-lm-object-with-other-functions"><i class="fa fa-check"></i><b>6.6.3</b> Using your <code>lm</code> object with other functions</a></li>
<li class="chapter" data-level="6.6.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#plotting-the-regression-line"><i class="fa fa-check"></i><b>6.6.4</b> Plotting the regression line</a></li>
<li class="chapter" data-level="6.6.5" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#a-note-on-degrees-of-freedom-of-our-model"><i class="fa fa-check"></i><b>6.6.5</b> A note on degrees of freedom of our model</a></li>
<li class="chapter" data-level="6.6.6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#interpreting-the-output"><i class="fa fa-check"></i><b>6.6.6</b> Interpreting the output</a></li>
<li class="chapter" data-level="6.6.7" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#the-coeff.-of-determination-as-index-of-explanatory-value"><i class="fa fa-check"></i><b>6.6.7</b> The coeff. of determination as index of explanatory value</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#write-up-and-presentaion"><i class="fa fa-check"></i><b>6.7</b> Write up and presentaion</a></li>
<li class="chapter" data-level="6.8" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#advanced-plotting"><i class="fa fa-check"></i><b>6.8</b> Advanced plotting</a><ul>
<li class="chapter" data-level="6.8.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#adding-text-to-the-plot"><i class="fa fa-check"></i><b>6.8.1</b> Adding text to the plot</a></li>
<li class="chapter" data-level="6.8.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#addnig-text-like-a-r-ninja"><i class="fa fa-check"></i><b>6.8.2</b> addnig text like a R-ninja:</a></li>
<li class="chapter" data-level="6.8.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#placing-plots-side-by-side-in-a-grid"><i class="fa fa-check"></i><b>6.8.3</b> Placing plots side-by-side in a grid</a></li>
<li class="chapter" data-level="6.8.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#two-series-on-the-same-damn-plot"><i class="fa fa-check"></i><b>6.8.4</b> Two series on the same damn plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html"><i class="fa fa-check"></i><b>7</b> Testing differences in means: t-test</a><ul>
<li class="chapter" data-level="7.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#things-to-consider-before-running-the-t-test"><i class="fa fa-check"></i><b>7.1</b> Things to consider before running the t-test</a><ul>
<li class="chapter" data-level="7.1.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#what-is-the-nature-of-your-sample-data"><i class="fa fa-check"></i><b>7.1.1</b> What is the nature of your sample data?</a></li>
<li class="chapter" data-level="7.1.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#what-is-the-structure-of-your-data-file"><i class="fa fa-check"></i><b>7.1.2</b> What is the structure of your data file?</a></li>
<li class="chapter" data-level="7.1.3" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#testing-assumptions"><i class="fa fa-check"></i><b>7.1.3</b> Testing assumptions</a></li>
<li class="chapter" data-level="7.1.4" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#getting-the-descriptive-stats-and-plotting-the-means."><i class="fa fa-check"></i><b>7.1.4</b> Getting the descriptive stats and plotting the means.</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#performing-the-t-test-paired-sample-t-test"><i class="fa fa-check"></i><b>7.2</b> Performing the t-test (Paired sample t-test)</a></li>
<li class="chapter" data-level="7.3" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#measuring-effect-size"><i class="fa fa-check"></i><b>7.3</b> Measuring effect size</a></li>
<li class="chapter" data-level="7.4" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#other-t-tests"><i class="fa fa-check"></i><b>7.4</b> Other <span class="math inline">\(t\)</span> tests:</a><ul>
<li class="chapter" data-level="7.4.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#one-sample"><i class="fa fa-check"></i><b>7.4.1</b> One sample:</a></li>
<li class="chapter" data-level="7.4.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#independent-samples-example"><i class="fa fa-check"></i><b>7.4.2</b> Independent samples example</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#independent-or-paired-sample"><i class="fa fa-check"></i><b>7.5</b> Independent or Paired Sample?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html"><i class="fa fa-check"></i><b>8</b> Analysis of Variance I: the One-way ANOVA</a><ul>
<li class="chapter" data-level="8.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#required-packages"><i class="fa fa-check"></i><b>8.1</b> Required packages</a></li>
<li class="chapter" data-level="8.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#anovas-for-comparing-means"><i class="fa fa-check"></i><b>8.2</b> ANOVAs for comparing means</a></li>
<li class="chapter" data-level="8.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#pre-processing-the-data"><i class="fa fa-check"></i><b>8.3</b> Pre-processing the data:</a><ul>
<li class="chapter" data-level="8.3.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#recoding-the-factors-if-dummy-coded"><i class="fa fa-check"></i><b>8.3.1</b> Recoding the factors (if dummy coded)</a></li>
<li class="chapter" data-level="8.3.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#renaming-column-headers"><i class="fa fa-check"></i><b>8.3.2</b> Renaming column headers</a></li>
<li class="chapter" data-level="8.3.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reordering-your-levels"><i class="fa fa-check"></i><b>8.3.3</b> Reordering your levels</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#assumptions-for-anova"><i class="fa fa-check"></i><b>8.4</b> Assumptions for ANOVA</a><ul>
<li class="chapter" data-level="8.4.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#checking-the-normality-assumption-option-1"><i class="fa fa-check"></i><b>8.4.1</b> Checking the normality assumption, OPTION 1</a></li>
<li class="chapter" data-level="8.4.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#checking-the-normality-assumption-option-2"><i class="fa fa-check"></i><b>8.4.2</b> Checking the normality assumption, OPTION 2</a></li>
<li class="chapter" data-level="8.4.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#homogeneity-of-variance"><i class="fa fa-check"></i><b>8.4.3</b> Homogeneity of Variance</a></li>
<li class="chapter" data-level="8.4.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#what-to-do-if-the-assumptions-are-violated"><i class="fa fa-check"></i><b>8.4.4</b> What to do if the assumptions are violated?</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#running-the-anova-in-r"><i class="fa fa-check"></i><b>8.5</b> Running the ANOVA in R:</a></li>
<li class="chapter" data-level="8.6" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reporting-your-data"><i class="fa fa-check"></i><b>8.6</b> Reporting your data</a><ul>
<li class="chapter" data-level="8.6.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reporting-in-the-text"><i class="fa fa-check"></i><b>8.6.1</b> Reporting in the text</a></li>
<li class="chapter" data-level="8.6.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#what-the-omnibus-anova-tells-you"><i class="fa fa-check"></i><b>8.6.2</b> What the omnibus ANOVA tells you</a></li>
<li class="chapter" data-level="8.6.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#plots"><i class="fa fa-check"></i><b>8.6.3</b> Plots</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#digging-deeper-anova-and-regression"><i class="fa fa-check"></i><b>8.7</b> DIGGING DEEPER: ANOVA and Regression</a><ul>
<li class="chapter" data-level="8.7.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#regression-method-v.-means-method"><i class="fa fa-check"></i><b>8.7.1</b> Regression method v. means method</a></li>
<li class="chapter" data-level="8.7.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#comparing-two-models"><i class="fa fa-check"></i><b>8.7.2</b> Comparing two models</a></li>
<li class="chapter" data-level="8.7.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#means-method-calculations"><i class="fa fa-check"></i><b>8.7.3</b> Means method calculations</a></li>
<li class="chapter" data-level="8.7.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#bringing-it-together-its-all-about-the-residuals-baby"><i class="fa fa-check"></i><b>8.7.4</b> Bringing it together: it’s all about the residuals, baby</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><i class="fa fa-check"></i><b>9</b> Analysis of Variance II: Multiple comparisons in One-way ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#getting-started-loading-packages-and-data"><i class="fa fa-check"></i><b>9.1</b> Getting started (loading packages and data)</a></li>
<li class="chapter" data-level="9.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#running-the-one-way-anova"><i class="fa fa-check"></i><b>9.2</b> Running the One-way ANOVA</a></li>
<li class="chapter" data-level="9.3" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#post-hoc-tests"><i class="fa fa-check"></i><b>9.3</b> Post-hoc tests</a><ul>
<li class="chapter" data-level="9.3.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#bonferonni-dunn-and-holm-tests"><i class="fa fa-check"></i><b>9.3.1</b> Bonferonni-Dunn and Holm tests</a></li>
<li class="chapter" data-level="9.3.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#tukey-hsd-and-regwq-tests"><i class="fa fa-check"></i><b>9.3.2</b> Tukey HSD and REGWQ tests</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#the-logic-of-planned-contrasts"><i class="fa fa-check"></i><b>9.4</b> The logic of Planned contrasts</a></li>
<li class="chapter" data-level="9.5" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#performing-planned-contrasts-in-r"><i class="fa fa-check"></i><b>9.5</b> Performing planned contrasts in R</a><ul>
<li class="chapter" data-level="9.5.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#making-the-output-easier-to-read"><i class="fa fa-check"></i><b>9.5.1</b> Making the output easier to read</a></li>
<li class="chapter" data-level="9.5.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#calculating-your-effect-size"><i class="fa fa-check"></i><b>9.5.2</b> Calculating your effect size</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#reporting-your-results"><i class="fa fa-check"></i><b>9.6</b> Reporting your results</a></li>
<li class="chapter" data-level="9.7" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#a-note-on-using-the-multcomp-package-v.-using-the-base-stats-method"><i class="fa fa-check"></i><b>9.7</b> A note on using the <code>multcomp</code> package v. using the base stats method</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html"><i class="fa fa-check"></i><b>10</b> Analysis of Varience III: Factorial ANOVA</a><ul>
<li class="chapter" data-level="10.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#main-effect-main-effect-and-interactions-oh-my"><i class="fa fa-check"></i><b>10.1</b> Main effect, main effect, and interactions… oh my!</a></li>
<li class="chapter" data-level="10.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#example-a-22-anova"><i class="fa fa-check"></i><b>10.2</b> Example: a 2×2 ANOVA</a></li>
<li class="chapter" data-level="10.3" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#making-sense-of-plots"><i class="fa fa-check"></i><b>10.3</b> Making sense of plots</a><ul>
<li class="chapter" data-level="10.3.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-plots"><i class="fa fa-check"></i><b>10.3.1</b> Interaction plots</a></li>
<li class="chapter" data-level="10.3.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#plotting-main-effects"><i class="fa fa-check"></i><b>10.3.2</b> Plotting main effects</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-lm-method"><i class="fa fa-check"></i><b>10.4</b> Running the ANOVA <code>lm()</code> method</a></li>
<li class="chapter" data-level="10.5" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-in-the-afexaov_ez-method"><i class="fa fa-check"></i><b>10.5</b> Running the ANOVA in the <code>afex::aov_ez()</code> method:</a></li>
<li class="chapter" data-level="10.6" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#getting-cell-means"><i class="fa fa-check"></i><b>10.6</b> Getting cell means</a></li>
<li class="chapter" data-level="10.7" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#more-examples-a-2-3-anova"><i class="fa fa-check"></i><b>10.7</b> More examples: a 2 × 3 ANOVA</a><ul>
<li class="chapter" data-level="10.7.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova"><i class="fa fa-check"></i><b>10.7.1</b> Running the ANOVA</a></li>
<li class="chapter" data-level="10.7.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#apa-plotting"><i class="fa fa-check"></i><b>10.7.2</b> APA plotting</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#anova-howell-13.1"><i class="fa fa-check"></i><b>10.8</b> 2 × 5 ANOVA (Howell 13.1)</a><ul>
<li class="chapter" data-level="10.8.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-1"><i class="fa fa-check"></i><b>10.8.1</b> Running the ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#one-last-example"><i class="fa fa-check"></i><b>10.9</b> One last example,</a><ul>
<li class="chapter" data-level="10.9.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-2"><i class="fa fa-check"></i><b>10.9.1</b> Running the ANOVA</a></li>
<li class="chapter" data-level="10.9.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-plot"><i class="fa fa-check"></i><b>10.9.2</b> Interaction plot</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-v.-no-interaction"><i class="fa fa-check"></i><b>10.10</b> Interaction v. no interaction</a><ul>
<li class="chapter" data-level="10.10.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#no-interaction-how-about-some-posthocs"><i class="fa fa-check"></i><b>10.10.1</b> No interaction? How about some posthocs?</a></li>
<li class="chapter" data-level="10.10.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#what-to-do-if-you-do-have-an-interaction"><i class="fa fa-check"></i><b>10.10.2</b> what to do if you DO have an interaction</a></li>
</ul></li>
<li class="chapter" data-level="10.11" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#what-about-planned-contrasts"><i class="fa fa-check"></i><b>10.11</b> What about planned contrasts?</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html"><i class="fa fa-check"></i><b>11</b> ANOVA IV: Interactions &amp; simple Effects</a><ul>
<li class="chapter" data-level="11.1" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#the-data-set"><i class="fa fa-check"></i><b>11.1</b> the data set</a></li>
<li class="chapter" data-level="11.2" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#plotting-the-data-and-descriptive-stats"><i class="fa fa-check"></i><b>11.2</b> Plotting the data and descriptive stats</a></li>
<li class="chapter" data-level="11.3" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#the-omnibus-anova-and-assumption-tests"><i class="fa fa-check"></i><b>11.3</b> the Omnibus ANOVA (and assumption tests)</a></li>
<li class="chapter" data-level="11.4" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#running-the-simple-effects-anova-in-6-steps"><i class="fa fa-check"></i><b>11.4</b> Running the simple effects ANOVA in 6 steps:</a><ul>
<li class="chapter" data-level="11.4.1" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-1-get-the-omnibus-anova"><i class="fa fa-check"></i><b>11.4.1</b> step 1: get the omnibus ANOVA:</a></li>
<li class="chapter" data-level="11.4.2" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-2-get-the-mserror-error-df-and-error-ss-from-omnibus-anova"><i class="fa fa-check"></i><b>11.4.2</b> step 2: get the MSError, Error df, and Error SS from omnibus ANOVA</a></li>
<li class="chapter" data-level="11.4.3" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-3-subset-your-data-accordingly"><i class="fa fa-check"></i><b>11.4.3</b> step 3: subset your data accordingly</a></li>
<li class="chapter" data-level="11.4.4" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-4-run-your-one-way-simple-effects-anovas"><i class="fa fa-check"></i><b>11.4.4</b> step 4: run your One-way simple effects ANOVA(s)</a></li>
<li class="chapter" data-level="11.4.5" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-5-get-the-treatment-ms-df-ss-and-f-value-from-your-simple-anova"><i class="fa fa-check"></i><b>11.4.5</b> step 5: get the treatment MS, df, SS, and F-value from your simple ANOVA</a></li>
<li class="chapter" data-level="11.4.6" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-6-make-our-corrections"><i class="fa fa-check"></i><b>11.4.6</b> step 6: make our corrections</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#building-a-function-to-ninja-this-for-us"><i class="fa fa-check"></i><b>11.5</b> Building a function to ninja this for us</a></li>
<li class="chapter" data-level="11.6" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#post-hoc-tests-1"><i class="fa fa-check"></i><b>11.6</b> Post hoc tests</a></li>
<li class="chapter" data-level="11.7" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#interpreting-these-results"><i class="fa fa-check"></i><b>11.7</b> Interpreting these results:</a></li>
<li class="chapter" data-level="11.8" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#example-write-up"><i class="fa fa-check"></i><b>11.8</b> Example write-up:</a></li>
<li class="chapter" data-level="11.9" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#performing-this-in-spss-video"><i class="fa fa-check"></i><b>11.9</b> Performing this in SPSS (video)</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA V: Higher Order Factorial ANOVA</a><ul>
<li class="chapter" data-level="12.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#packages-and-data"><i class="fa fa-check"></i><b>12.1</b> Packages and data</a></li>
<li class="chapter" data-level="12.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-1-no-three-way-interaction-single-two-way-interaction"><i class="fa fa-check"></i><b>12.2</b> EXAMPLE 1: no three-way interaction, single two way interaction</a><ul>
<li class="chapter" data-level="12.2.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#first-plot-3-way-interaction-plot"><i class="fa fa-check"></i><b>12.2.1</b> First plot: 3 way interaction plot</a></li>
<li class="chapter" data-level="12.2.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-anova-3"><i class="fa fa-check"></i><b>12.2.2</b> running the ANOVA:</a></li>
<li class="chapter" data-level="12.2.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#replotting-the-2-way-interaction"><i class="fa fa-check"></i><b>12.2.3</b> Replotting the 2-way interaction</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-2-no-three-way-interaction-multiple-main-effects-multiple-2-way-interactions"><i class="fa fa-check"></i><b>12.3</b> EXAMPLE 2: No three-way interaction, multiple main effects, multiple 2 way interactions:</a><ul>
<li class="chapter" data-level="12.3.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#plotting-the-data-1"><i class="fa fa-check"></i><b>12.3.1</b> plotting the data</a></li>
<li class="chapter" data-level="12.3.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-omnibus-anova"><i class="fa fa-check"></i><b>12.3.2</b> running the omnibus ANOVA:</a></li>
<li class="chapter" data-level="12.3.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#testing-the-lecturepresentation-interaction"><i class="fa fa-check"></i><b>12.3.3</b> testing the <code>Lecture:Presentation</code> interaction:</a></li>
<li class="chapter" data-level="12.3.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#testing-the-lecturegrade-interaction"><i class="fa fa-check"></i><b>12.3.4</b> testing the <code>Lecture:Grade</code> interaction:</a></li>
<li class="chapter" data-level="12.3.5" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#simple-effect-anovas-1"><i class="fa fa-check"></i><b>12.3.5</b> simple effect ANOVAs:</a></li>
<li class="chapter" data-level="12.3.6" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#main-takeaways-write-up"><i class="fa fa-check"></i><b>12.3.6</b> Main takeaways / write-up</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-3-omg-multiple-two-way-interactions-and-a-nasty-three-way"><i class="fa fa-check"></i><b>12.4</b> EXAMPLE 3: OMG, multiple two way interactions and a nasty three-way!!!</a><ul>
<li class="chapter" data-level="12.4.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#plotting"><i class="fa fa-check"></i><b>12.4.1</b> Plotting:</a></li>
<li class="chapter" data-level="12.4.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-anova-4"><i class="fa fa-check"></i><b>12.4.2</b> running the ANOVA:</a></li>
<li class="chapter" data-level="12.4.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#fifth-graders-lecturepresentation-interaction."><i class="fa fa-check"></i><b>12.4.3</b> Fifth Graders, Lecture:Presentation interaction.</a></li>
<li class="chapter" data-level="12.4.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#eighth-graders-lecturepresentation-interaction."><i class="fa fa-check"></i><b>12.4.4</b> Eighth Graders, Lecture:Presentation interaction.</a></li>
<li class="chapter" data-level="12.4.5" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#constructing-a-narrative"><i class="fa fa-check"></i><b>12.4.5</b> Constructing a narrative:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html"><i class="fa fa-check"></i><b>13</b> ANOVA6: Within-Subjects</a><ul>
<li class="chapter" data-level="13.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#within-subject-v.-between-subjects"><i class="fa fa-check"></i><b>13.1</b> Within-Subject v. Between Subjects</a><ul>
<li class="chapter" data-level="13.1.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#within-v-between-anova"><i class="fa fa-check"></i><b>13.1.1</b> Within v Between ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-1"><i class="fa fa-check"></i><b>13.2</b> EXAMPLE 1</a><ul>
<li class="chapter" data-level="13.2.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data"><i class="fa fa-check"></i><b>13.2.1</b> loading in the data:</a></li>
<li class="chapter" data-level="13.2.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-2"><i class="fa fa-check"></i><b>13.2.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.2.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-a-within-anova-afex"><i class="fa fa-check"></i><b>13.2.3</b> running a within ANOVA (afex):</a></li>
<li class="chapter" data-level="13.2.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#planned-contrasts"><i class="fa fa-check"></i><b>13.2.4</b> planned contrasts</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-2"><i class="fa fa-check"></i><b>13.3</b> EXAMPLE 2</a><ul>
<li class="chapter" data-level="13.3.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data-1"><i class="fa fa-check"></i><b>13.3.1</b> loading in the data</a></li>
<li class="chapter" data-level="13.3.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-3"><i class="fa fa-check"></i><b>13.3.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.3.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-anova-5"><i class="fa fa-check"></i><b>13.3.3</b> running the ANOVA:</a></li>
<li class="chapter" data-level="13.3.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#post-hocs"><i class="fa fa-check"></i><b>13.3.4</b> post-hocs</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-3"><i class="fa fa-check"></i><b>13.4</b> EXAMPLE 3</a><ul>
<li class="chapter" data-level="13.4.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data-2"><i class="fa fa-check"></i><b>13.4.1</b> loading in the data:</a></li>
<li class="chapter" data-level="13.4.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-4"><i class="fa fa-check"></i><b>13.4.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.4.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-omnibus-anova-1"><i class="fa fa-check"></i><b>13.4.3</b> running the omnibus ANOVA:</a></li>
<li class="chapter" data-level="13.4.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-simple-effects-anovas"><i class="fa fa-check"></i><b>13.4.4</b> running the simple effects ANOVAs</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#how-to-perform-a-within-subjects-analysis-in-spss"><i class="fa fa-check"></i><b>13.5</b> How to perform a within subjects analysis in SPSS:</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html"><i class="fa fa-check"></i><b>14</b> ANOVA VI: Mixed-effects ANOVA (BS + WS)</a><ul>
<li class="chapter" data-level="14.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#example-1-1"><i class="fa fa-check"></i><b>14.1</b> Example 1:</a><ul>
<li class="chapter" data-level="14.1.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#data-import-and-wrangling"><i class="fa fa-check"></i><b>14.1.1</b> data import and wrangling</a></li>
<li class="chapter" data-level="14.1.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#plotting-the-data-5"><i class="fa fa-check"></i><b>14.1.2</b> plotting the data</a></li>
<li class="chapter" data-level="14.1.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#running-our-anova"><i class="fa fa-check"></i><b>14.1.3</b> Running our ANOVA:</a></li>
<li class="chapter" data-level="14.1.4" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#simple-effects"><i class="fa fa-check"></i><b>14.1.4</b> simple effects</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#example-2-1"><i class="fa fa-check"></i><b>14.2</b> Example 2:</a><ul>
<li class="chapter" data-level="14.2.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#data-import-and-wrangling-1"><i class="fa fa-check"></i><b>14.2.1</b> data import and wrangling</a></li>
<li class="chapter" data-level="14.2.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#plotting-the-data-6"><i class="fa fa-check"></i><b>14.2.2</b> plotting the data</a></li>
<li class="chapter" data-level="14.2.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#run-your-omnibus-anova"><i class="fa fa-check"></i><b>14.2.3</b> Run your omnibus ANOVA:</a></li>
<li class="chapter" data-level="14.2.4" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#simple-effects-1"><i class="fa fa-check"></i><b>14.2.4</b> simple effects:</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#to-pool-or-not-to-pool-this-is-the-yada-yada-yada"><i class="fa fa-check"></i><b>14.3</b> to pool or not to pool, this is the yada yada yada</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html"><i class="fa fa-check"></i><b>A</b> Plotting histograms and probability distributions</a><ul>
<li class="chapter" data-level="A.1" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#the-basics"><i class="fa fa-check"></i><b>A.1</b> The Basics</a><ul>
<li class="chapter" data-level="A.1.1" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-1-building-the-canvas"><i class="fa fa-check"></i><b>A.1.1</b> Step 1: Building the canvas</a></li>
<li class="chapter" data-level="A.1.2" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-2-tell-ggplot-what-kind-of-plot-to-make."><i class="fa fa-check"></i><b>A.1.2</b> Step 2: Tell <code>ggplot</code> what kind of plot to make.</a></li>
<li class="chapter" data-level="A.1.3" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-3-adjust-the-axes-and-labels"><i class="fa fa-check"></i><b>A.1.3</b> Step 3: Adjust the axes and labels</a></li>
<li class="chapter" data-level="A.1.4" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-4-adjusting-for-apa"><i class="fa fa-check"></i><b>A.1.4</b> Step 4: Adjusting for APA</a></li>
<li class="chapter" data-level="A.1.5" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-5-add-and-adjust-the-legend"><i class="fa fa-check"></i><b>A.1.5</b> Step 5: Add and adjust the legend</a></li>
<li class="chapter" data-level="A.1.6" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-6-save-the-ggplot."><i class="fa fa-check"></i><b>A.1.6</b> Step 6: Save the <code>ggplot</code>.</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#a-note-about-your-bonus-on-week-4."><i class="fa fa-check"></i><b>A.2</b> A note about your BONUS on Week 4.</a></li>
<li class="chapter" data-level="A.3" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#advanced-stuff"><i class="fa fa-check"></i><b>A.3</b> Advanced stuff</a></li>
</ul></li>
<li class="divider"></li>
<li></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">musings of the Professor</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova-v-higher-order-factorial-anova" class="section level1">
<h1><span class="header-section-number">Week 12</span> ANOVA V: Higher Order Factorial ANOVA</h1>
<p>This walk-through is a continuation of our previous work with factorial ANOVA. If you haven’t already, please check the factorial ANOVA and Interaction vignettes. In truth, nothing terribly new is being introduced here; we are just ramping up the complexity of our ANOVA models. Whereas before we considered a scenario with just 2 factors, here we will consider a 3 factor ANOVA. For all practical purposes you typically do not want to go higher than a 3 or 4 factor ANOVA, simply because of the exponential increase in complexity. For example, consider below where each letter is an IV and the resulting tests in the full factorial omnibus ANOVA:</p>
<ul>
<li>2 factor: a, b, a×b</li>
<li>3 factor: a, b, c, a×b, a×c, b×c, a×b×c</li>
<li>4 factor: a, b, c, d, a×b, a×c, a×d, b×c, b×d, c×d, a×b×c, a×b×d, a×c×d, b×c×d, a×b×c×d</li>
<li>5 factor: ummm, no… just don’t (unless you really want to)</li>
</ul>
<p>Increasing the number of factors not only increases the practical difficulty of analysis, but more importantly, makes it more difficult to interpret your results. The primary culprit here is the potential presence of multiple interactions.</p>
<p>When dealing with interactions in a higher order factorial design you always start off with the highest order interaction. For example in the 3 factor case, if you have a 3-way interaction, that supercedes any other effects and interactions, and must be dealt with first. If there is no three-way interaction, then you can co about the business of addressing any two way interactions that are present.</p>
<div id="packages-and-data" class="section level2">
<h2><span class="header-section-number">12.1</span> Packages and data</h2>
<p>Let’s load in our necessary packages, scripts and some data and try some examples. This write-up requires the following packages:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># required packages:</span>
pacman<span class="op">::</span><span class="kw">p_load</span>(tidyverse, afex, cowplot, agricolae)

<span class="co"># custom simple effects ANOVA script (see interaction vignette):</span>
<span class="kw">source</span>(<span class="st">&quot;https://raw.githubusercontent.com/tehrandavis/statsRepo/master/statsScripts/simpleEffectsAOV.R&quot;</span>)</code></pre></div>
<p>And now let’s reaquaint ourselves with our dataset from last week, but with one new twist…</p>
<p>Background: Given the ease of access for new technologies and increasing enrollment demands, many grade schools are advocating that teachers switch over to E-courses, where students view an online, pre-recorded lecture on the course topic in lieu of sitting in a classroom in a live lecture. Given this push, a critical question remains regarding the impact of E-courses on primary school student outcomes. More it may be the case that certain subject content more readily lends itself to E-course presentations than other subjects. To address this question we tested students performance on a test one week after listening to the related lecture. Lectures were either experienced via online (Computer) or in a live classroom (Standard). In addition, the lecture content varied in topic (Physical science, Social science, History). Finally, to assess whether age had an impact on expected outcomes we assessed students in 5th and 8th grades.</p>
<p>Looking at the above we have a 2 (Grade: 5th, 8th) × 2 (Presentation: Computer, Standard) × 3 (Lecture: Physical, Social, History) design. Our omnibus ANOVA therefore will test for the following effects:</p>
<ul>
<li>Main Effects: Grade, Presentation, Lecture</li>
<li>2-way interactions: Grade × Presentation, Grade × Lecture, Lecture × Presentation</li>
<li>3-way interation: Grade × Presentation × Lecture</li>
</ul>
</div>
<div id="example-1-no-three-way-interaction-single-two-way-interaction" class="section level2">
<h2><span class="header-section-number">12.2</span> EXAMPLE 1: no three-way interaction, single two way interaction</h2>
<p>Let’s load in this data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">higherEx1 &lt;-<span class="st"> </span><span class="kw">read_delim</span>(<span class="st">&quot;https://raw.githubusercontent.com/tehrandavis/statsRepo/master/statsData/ANOVA5_higherEx1.txt&quot;</span>, 
    <span class="dt">delim =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Subject = col_integer(),
##   Grade = col_character(),
##   Lecture = col_character(),
##   Presentation = col_character(),
##   Score = col_integer()
## )</code></pre>
<div id="first-plot-3-way-interaction-plot" class="section level3">
<h3><span class="header-section-number">12.2.1</span> First plot: 3 way interaction plot</h3>
<p>One thing you may notice is since we have a more complex ANOVA, we have a more complex design with three factors we also have to construct a more complex plot. Whereas in the 2 factor case we could place one factor on the x-axis and group the other factor by line or shape or color; in the three factor case things become slightly more tricky.</p>
<p>One thing to consider is the logic of what we are doing with our plots. When we have two factors, say A &amp; B, we are distinguishing between each level of B (by lines, shapes, colors) at each level of A (on the x-axis). In the 3 factor case where we have A,B, &amp; C, we are distinguishing the B×C interaction (through the combination of shapes, lines, colors) on each level of A.</p>
<p>In the folling plot, let’s place Lecture type along the x-axis. From here, we can create 2 groups of lines (each with 2 levels) representing the Grade × Presentation interaction. We note this by specifying the <code>interaction</code> in <code>group</code> of our baseline <code>ggplot</code> call:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(ggplot2)
p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(higherEx1, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Lecture, <span class="dt">y =</span> Score, <span class="dt">group =</span> <span class="kw">interaction</span>(Presentation, 
    Grade)))</code></pre></div>
<p>From here, we can proceed as before. Note, however, depending on the complexity of your plot you may also need to specify the interaction in each <code>stat_summary::aes()</code> as necessary.</p>
<p>Below I am changing the <code>shape</code> by <code>Presentation</code> and the <code>linetype</code> by <code>Grade</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;pointrange&quot;</span>, <span class="dt">fun.data =</span> <span class="st">&quot;mean_se&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
    <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
    <span class="kw">aes</span>(<span class="dt">linetype =</span> Grade)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span><span class="co"># adjusting the legend</span>
<span class="kw">theme</span>(<span class="dt">legend.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>, <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>), <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.2</span>, 
    <span class="fl">0.25</span>)) <span class="op">+</span><span class="st"> </span><span class="co"># renaming axies</span>
<span class="kw">xlab</span>(<span class="st">&quot;Lecture&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Score&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># adding whitespace around plot (optional)</span>
<span class="kw">theme</span>(<span class="dt">plot.margin =</span> <span class="kw">unit</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>), <span class="st">&quot;in&quot;</span>))
<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-365-1.png" width="672" /></p>
<p>OK, not exactly the best plot. Let’s see if we can create some more space to work with by forcing the y-axis to go to 0, instead of cutting off at 10. There’s also a trick that we can use to stack our legend keys horizontally, rather than vertically</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="co"># take the previous plot and... </span>
<span class="st">  </span><span class="co"># set the y-axis limits to 0 and 50</span>
<span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">50</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="co"># direction to stack legend keys</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.direction =</span> <span class="st">&quot;horizontal&quot;</span>, 
        <span class="dt">legend.position =</span> <span class="kw">c</span>(.<span class="dv">2</span>,.<span class="dv">25</span>))
<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-366-1.png" width="672" /></p>
<p>alternatively, we could also just stack the legend boxes side by side:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># redoing intial steps</span>
p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(higherEx1, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Lecture, <span class="dt">y =</span> Score, <span class="dt">group =</span> <span class="kw">interaction</span>(Presentation, 
    Grade))) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;pointrange&quot;</span>, <span class="dt">fun.data =</span> <span class="st">&quot;mean_se&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
    <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
    <span class="kw">aes</span>(<span class="dt">linetype =</span> Grade)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">xlab</span>(<span class="st">&quot;Lecture&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Score&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.margin =</span> <span class="kw">unit</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, 
    <span class="fl">0.25</span>), <span class="st">&quot;in&quot;</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">50</span>)) <span class="op">+</span><span class="st"> </span>
<span class="co"># stack legend boxes horizontally:</span>
<span class="kw">theme</span>(<span class="dt">legend.box =</span> <span class="st">&quot;horizontal&quot;</span>)
<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-367-1.png" width="672" /></p>
</div>
<div id="running-the-anova-3" class="section level3">
<h3><span class="header-section-number">12.2.2</span> running the ANOVA:</h3>
<p>From here we run the omnibus as usual:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">omnibus.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> higherEx1, <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>, 
    <span class="st">&quot;Presentation&quot;</span>, <span class="st">&quot;Grade&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture, Presentation, Grade</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture, Presentation, Grade</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">omnibus.aov<span class="op">$</span>anova_table</code></pre></div>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: Score
##                            num Df den Df    MSE       F     pes    Pr(&gt;F)
## Lecture                         2     60 54.619 21.3327 0.41558 1.004e-07
## Presentation                    1     60 54.619 80.0287 0.57152 1.217e-12
## Grade                           1     60 54.619  0.0064 0.00011    0.9367
## Lecture:Presentation            2     60 54.619 13.3660 0.30821 1.582e-05
## Lecture:Grade                   2     60 54.619  0.0033 0.00011    0.9967
## Presentation:Grade              1     60 54.619  0.0023 0.00004    0.9620
## Lecture:Presentation:Grade      2     60 54.619  0.0008 0.00003    0.9992
##                               
## Lecture                    ***
## Presentation               ***
## Grade                         
## Lecture:Presentation       ***
## Lecture:Grade                 
## Presentation:Grade            
## Lecture:Presentation:Grade    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In this case we only have Main effects for Lecture and Presentation, and a Lecture × Presentation interaction. Given this we can disregard Grade as its not contributing to any effects.</p>
</div>
<div id="replotting-the-2-way-interaction" class="section level3">
<h3><span class="header-section-number">12.2.3</span> Replotting the 2-way interaction</h3>
<p>In some cases it is advisable to re-plot the data factoring out Grade by removing Grade from baseline <code>group=</code> as well as any <code>summary_stat::aes()</code>, (essentially treating this if it was a 2 factorial design like last week). For the sake of your sanity, and your readers’ sanity) I would also suggest being consistent with how you present your conditions. For example, in the original plot, Presentation was differentiated by <code>shape</code>. To be consistent, we need to do the same here).</p>
<p>(You’ll note in the example below I’m also customing font size and weight ourely for personal aesthetics):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(higherEx1, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Lecture, <span class="dt">y =</span> Score, <span class="dt">group =</span> Presentation)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;pointrange&quot;</span>, <span class="dt">fun.data =</span> <span class="st">&quot;mean_se&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
        <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, 
    <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">axis.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">16</span>, <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="dt">lineheight =</span> <span class="fl">0.55</span>), 
        <span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>), <span class="dt">legend.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>, 
            <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>), <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Lecture&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">ylab</span>(<span class="st">&quot;Score&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.margin =</span> <span class="kw">unit</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>), <span class="st">&quot;in&quot;</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">50</span>)) <span class="op">+</span><span class="st"> </span>
<span class="co"># stack legend boxes horizontally:</span>
<span class="kw">theme</span>(<span class="dt">legend.box =</span> <span class="st">&quot;horizontal&quot;</span>)</code></pre></div>
<pre><code>## Warning: Ignoring unknown aesthetics: shape</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-369-1.png" width="672" /></p>
<p>From here I would deal with the follow-ups as we did in our 2×3 example from the last write-up: Run the simple effects and any necessary posthocs, being sure to correct using the error terms from the omnibus ANOVA.</p>
</div>
</div>
<div id="example-2-no-three-way-interaction-multiple-main-effects-multiple-2-way-interactions" class="section level2">
<h2><span class="header-section-number">12.3</span> EXAMPLE 2: No three-way interaction, multiple main effects, multiple 2 way interactions:</h2>
<p>Let’s load in a data set that is a little more complicated:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">higherEx2 &lt;-<span class="st"> </span><span class="kw">read_delim</span>(<span class="st">&quot;https://raw.githubusercontent.com/tehrandavis/statsRepo/master/statsData/ANOVA5_higherEx2.txt&quot;</span>, 
    <span class="dt">delim =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Subject = col_integer(),
##   Grade = col_character(),
##   Lecture = col_character(),
##   Presentation = col_character(),
##   Score = col_integer()
## )</code></pre>
<div id="plotting-the-data-1" class="section level3">
<h3><span class="header-section-number">12.3.1</span> plotting the data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(higherEx2, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Lecture, <span class="dt">y =</span> Score, <span class="dt">group =</span> <span class="kw">interaction</span>(Presentation, 
    Grade))) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;pointrange&quot;</span>, <span class="dt">fun.data =</span> <span class="st">&quot;mean_se&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
    <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
    <span class="kw">aes</span>(<span class="dt">linetype =</span> Grade)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">16</span>, 
    <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="dt">lineheight =</span> <span class="fl">0.55</span>), <span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>), <span class="dt">legend.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>, 
    <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>), <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>)) <span class="op">+</span><span class="st"> </span>
<span class="kw">xlab</span>(<span class="st">&quot;Lecture&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Score&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.margin =</span> <span class="kw">unit</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>), 
    <span class="st">&quot;in&quot;</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">60</span>)) <span class="op">+</span><span class="st"> </span>
<span class="co"># stack legend boxes horizontally:</span>
<span class="kw">theme</span>(<span class="dt">legend.box =</span> <span class="st">&quot;horizontal&quot;</span>)

<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-371-1.png" width="672" /></p>
<p>Looking at this plot its quite apparent that the pattern of results is different from Example 1. Perhaps most simply, there is a general shared pattern of effects for each of the shapes (Presentation) with the exception of the 8th Grade-Computer condition. For the remainder there is a dip for Social lectures, but in this one condition Social actually increases. Let’s run our ANOVA.</p>
</div>
<div id="running-the-omnibus-anova" class="section level3">
<h3><span class="header-section-number">12.3.2</span> running the omnibus ANOVA:</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">omnibus.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> higherEx2, <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>, 
    <span class="st">&quot;Presentation&quot;</span>, <span class="st">&quot;Grade&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture, Presentation, Grade</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture, Presentation, Grade</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">omnibus.aov<span class="op">$</span>anova_table</code></pre></div>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: Score
##                            num Df den Df    MSE       F     pes    Pr(&gt;F)
## Lecture                         2     60 54.619  7.0887 0.19113  0.001723
## Presentation                    1     60 54.619 80.0287 0.57152 1.217e-12
## Grade                           1     60 54.619  5.6454 0.08600  0.020711
## Lecture:Presentation            2     60 54.619 13.3660 0.30821 1.582e-05
## Lecture:Grade                   2     60 54.619  5.5325 0.15570  0.006236
## Presentation:Grade              1     60 54.619  0.0023 0.00004  0.962004
## Lecture:Presentation:Grade      2     60 54.619  0.0008 0.00003  0.999237
##                               
## Lecture                    ** 
## Presentation               ***
## Grade                      *  
## Lecture:Presentation       ***
## Lecture:Grade              ** 
## Presentation:Grade            
## Lecture:Presentation:Grade    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Our ANOVA reveals an abundance of results. There are main effects for each of our IVs. In addition there are <strong>two</strong> interaction effects: <code>Lecture:Presentation</code> and <code>Lecture:Grade</code>. Unless there is a strong theoretical reason not to (which I see none) we will need to examine each of these interactions in further detail.</p>
</div>
<div id="testing-the-lecturepresentation-interaction" class="section level3">
<h3><span class="header-section-number">12.3.3</span> testing the <code>Lecture:Presentation</code> interaction:</h3>
<div id="way-interaction-plot" class="section level4">
<h4><span class="header-section-number">12.3.3.1</span> 2-way interaction plot</h4>
<p>We can begin by recreating our interaction plot, this time only focusing on the IVs that are of interest (those that are interacting). In this first case, they are <code>Lecture</code> and <code>Presentation</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(higherEx2, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Lecture, <span class="dt">y =</span> Score, <span class="dt">group =</span> Presentation)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;pointrange&quot;</span>, <span class="dt">fun.data =</span> <span class="st">&quot;mean_cl_normal&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
        <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, 
    <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">axis.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">16</span>, <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="dt">lineheight =</span> <span class="fl">0.55</span>), 
        <span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>), <span class="dt">legend.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>, 
            <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>), <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>)) <span class="op">+</span><span class="st"> </span>
<span class="kw">xlab</span>(<span class="st">&quot;Lecture&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Score&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.margin =</span> <span class="kw">unit</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>), 
    <span class="st">&quot;in&quot;</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">60</span>)) <span class="op">+</span><span class="st"> </span>
<span class="co"># stack legend boxes horizontally:</span>
<span class="kw">theme</span>(<span class="dt">legend.box =</span> <span class="st">&quot;horizontal&quot;</span>)</code></pre></div>
<pre><code>## Warning: Ignoring unknown aesthetics: shape</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-373-1.png" width="672" /></p>
</div>
<div id="simple-effect-anovas" class="section level4">
<h4><span class="header-section-number">12.3.3.2</span> simple effect ANOVAs:</h4>
<p>Provided what we see on this plot, it may make sense to first run a simple effects ANOVA for each Presentation and then run the appropriate follow-ups. I say this because the more obvious, and potentially easily interpret-able effects occur moving across the line series (i.e., lines trend up or down).</p>
<div id="computer-aov-and-follow-ups" class="section level5">
<h5><span class="header-section-number">12.3.3.2.1</span> computer AOV and follow-ups:</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">computer.data &lt;-<span class="st"> </span><span class="kw">filter</span>(higherEx2, Presentation <span class="op">==</span><span class="st"> &quot;Computer&quot;</span>)

computer.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> computer.data, 
    <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, computer.aov)</code></pre></div>
<pre><code>##      Effect    full_mse ftest                                  
## [1,] &quot;Lecture&quot; &quot;54.619&quot; &quot;F(2,60) = 4.739, p = 0.012, pes=0.136&quot;</code></pre>
<p>Our simple effects ANOVA of Lecture on our <code>computer.data</code> was significant, suggesting that we should perform a post-hoc:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">agricolae<span class="op">::</span><span class="kw">HSD.test</span>(computer.data<span class="op">$</span>Score, <span class="dt">trt =</span> computer.data<span class="op">$</span>Lecture, <span class="dt">MSerror =</span> <span class="fl">54.62</span>, 
    <span class="dt">DFerror =</span> <span class="dv">60</span>, <span class="dt">group =</span> T, <span class="dt">console =</span> T)</code></pre></div>
<pre><code>## 
## Study: computer.data$Score ~ computer.data$Lecture
## 
## HSD Test for computer.data$Score 
## 
## Mean Square Error:  54.62 
## 
## computer.data$Lecture,  means
## 
##          computer.data.Score      std  r Min Max
## History             38.00000 4.177864 12  33  45
## Physical            45.91667 6.734691 12  33  53
## Social              46.16667 7.814129 12  33  58
## 
## Alpha: 0.05 ; DF Error: 60 
## Critical Value of Studentized Range: 3.398661 
## 
## Minimun Significant Difference: 7.25092 
## 
## Treatments with the same letter are not significantly different.
## 
##          computer.data$Score groups
## Social              46.16667      a
## Physical            45.91667      a
## History             38.00000      b</code></pre>
<p>The results of the Tukey post-hoc suggests that History scores are significantly less than the other two groups for the Computer presentation.</p>
</div>
<div id="standard-aov-and-follow-ups" class="section level5">
<h5><span class="header-section-number">12.3.3.2.2</span> standard AOV and follow-ups:</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">standard.data &lt;-<span class="st"> </span><span class="kw">filter</span>(higherEx2, Presentation <span class="op">==</span><span class="st"> &quot;Standard&quot;</span>)
standard.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> standard.data, 
    <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, standard.aov)</code></pre></div>
<pre><code>##      Effect    full_mse ftest                                  
## [1,] &quot;Lecture&quot; &quot;54.619&quot; &quot;F(2,60) = 15.715, p &lt; .001, pes=0.344&quot;</code></pre>
<p>Our simple effects ANOVA for <code>cstandard.data</code> was also significant, suggesting that we should perform a post-hoc:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">agricolae<span class="op">::</span><span class="kw">HSD.test</span>(standard.data<span class="op">$</span>Score, <span class="dt">trt =</span> standard.data<span class="op">$</span>Lecture, <span class="dt">MSerror =</span> <span class="fl">54.62</span>, 
    <span class="dt">DFerror =</span> <span class="dv">60</span>, <span class="dt">group =</span> T, <span class="dt">console =</span> T)</code></pre></div>
<pre><code>## 
## Study: standard.data$Score ~ standard.data$Lecture
## 
## HSD Test for standard.data$Score 
## 
## Mean Square Error:  54.62 
## 
## standard.data$Lecture,  means
## 
##          standard.data.Score       std  r Min Max
## History             31.08333  9.624385 12  20  46
## Physical            34.08333 10.483392 12  18  49
## Social              18.16667  7.383438 12   6  29
## 
## Alpha: 0.05 ; DF Error: 60 
## Critical Value of Studentized Range: 3.398661 
## 
## Minimun Significant Difference: 7.25092 
## 
## Treatments with the same letter are not significantly different.
## 
##          standard.data$Score groups
## Physical            34.08333      a
## History             31.08333      a
## Social              18.16667      b</code></pre>
<p>For the standard presentation, scores in the History and Physical lecture were greater than the Social lecture.</p>
</div>
</div>
</div>
<div id="testing-the-lecturegrade-interaction" class="section level3">
<h3><span class="header-section-number">12.3.4</span> testing the <code>Lecture:Grade</code> interaction:</h3>
<p>Now we do the same for the <code>Lecture:Grade</code> interaction. This time removing <code>Presentation</code> from our consideration.</p>
<div id="way-interaction-plot-1" class="section level4">
<h4><span class="header-section-number">12.3.4.1</span> 2-way interaction plot</h4>
<p>You’ll notice that in this interaction plot, and the plot above, I am using the shape/linetype conventions that I established in my original plot. This will make things much easier if I wind up comparing these plots to my 3-way plot. I know I’ve said this before, but ONE MORE TIME WITH FEELING!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(higherEx2, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Lecture, <span class="dt">y =</span> Score, <span class="dt">group =</span> Grade)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;pointrange&quot;</span>, 
    <span class="dt">fun.data =</span> <span class="st">&quot;mean_se&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.15</span>), 
        <span class="kw">aes</span>(<span class="dt">linetype =</span> Grade)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">16</span>, 
    <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="dt">lineheight =</span> <span class="fl">0.55</span>), <span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>), <span class="dt">legend.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>, 
    <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>), <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>)) <span class="op">+</span><span class="st"> </span>
<span class="kw">xlab</span>(<span class="st">&quot;Lecture&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Score&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.margin =</span> <span class="kw">unit</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>), 
    <span class="st">&quot;in&quot;</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">60</span>)) <span class="op">+</span><span class="st"> </span>
<span class="co"># stack legend boxes horizontally:</span>
<span class="kw">theme</span>(<span class="dt">legend.box =</span> <span class="st">&quot;horizontal&quot;</span>)

<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-378-1.png" width="672" /></p>
</div>
</div>
<div id="simple-effect-anovas-1" class="section level3">
<h3><span class="header-section-number">12.3.5</span> simple effect ANOVAs:</h3>
<p>Looking at this plot Provided what we see on this plot, it may make the best sense to examine the pairwise differences in each Grade group by Lecture. Whereas in the previous interaction, the compelling changes occurred across lines, here what is more compelling is the presence/absence of gaps between the lines. In particular, while there are practically no differences due to Grade in the History or Physical Lectures, there is a larger gap in the Social condition.</p>
<div id="history-aov" class="section level4">
<h4><span class="header-section-number">12.3.5.1</span> History AOV:</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">history.data &lt;-<span class="st"> </span><span class="kw">filter</span>(higherEx2, Lecture <span class="op">==</span><span class="st"> &quot;History&quot;</span>)

history.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> history.data, <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Grade&quot;</span>), 
    <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Grade</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Grade</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, history.aov)</code></pre></div>
<pre><code>##      Effect  full_mse ftest                              
## [1,] &quot;Grade&quot; &quot;54.619&quot; &quot;F(1,60) = 0.001, p = 0.978, pes=0&quot;</code></pre>
</div>
<div id="physical-aov" class="section level4">
<h4><span class="header-section-number">12.3.5.2</span> Physical AOV:</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">physical.data &lt;-<span class="st"> </span><span class="kw">filter</span>(higherEx2, Lecture <span class="op">==</span><span class="st"> &quot;Physical&quot;</span>)

physical.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> physical.data, 
    <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Grade&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Grade</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Grade</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, physical.aov)</code></pre></div>
<pre><code>##      Effect  full_mse ftest                      
## [1,] &quot;Grade&quot; &quot;54.619&quot; &quot;F(1,60) = 0, p = 1, pes=0&quot;</code></pre>
</div>
<div id="social-aov" class="section level4">
<h4><span class="header-section-number">12.3.5.3</span> Social AOV:</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">social.data &lt;-<span class="st"> </span><span class="kw">filter</span>(higherEx2, Lecture <span class="op">==</span><span class="st"> &quot;Social&quot;</span>)

social.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> social.data, <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Grade&quot;</span>), 
    <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Grade</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Grade</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, social.aov)</code></pre></div>
<pre><code>##      Effect  full_mse ftest                                 
## [1,] &quot;Grade&quot; &quot;54.619&quot; &quot;F(1,60) = 16.71, p &lt; .001, pes=0.218&quot;</code></pre>
<p>As anticipated from looking at the plot, there was a significant difference between our Grades in the Social group, but not the remainder.</p>
</div>
</div>
<div id="main-takeaways-write-up" class="section level3">
<h3><span class="header-section-number">12.3.6</span> Main takeaways / write-up</h3>
<p>It’s typically best to go back and look at all of your plots.</p>
<ol style="list-style-type: decimal">
<li>the main effect for <code>Presentation</code> is meaningful: Regardless of what plays out on the other factors, students tended to perform better in the computer presentation. Best to report that.</li>
<li>the <code>Lecture:Presentation</code> interaction resulted from the following:
<ol style="list-style-type: lower-alpha">
<li>in the <strong>Computer presentations</strong> scores were lowest in the History lecture (indifferent in other two)</li>
<li>in the <strong>Standard presentations</strong> scores were lowest in the Social lecture (indifferent in the other two)</li>
</ol></li>
<li>the <code>Lecture:Grade</code> interaction resulted from the 5th graders performing worse than the eight graders in Social lectures; while performance was not different in the other two lectures.</li>
</ol>
<p>With this in mind, an example write-up:</p>
<blockquote>
Our results revealed main effects for each of our factors, in addition to Lecture × Presentation <span class="math inline">\([F(2,60)=13.37, p&lt;.001, \eta_p^2=.31]\)</span> and Lecture × Grade interactions <span class="math inline">\([F(2,60)=5.53, p=.006, \eta_p^2=.16]\)</span>.
<p>
Considering the former interaction, students presented material via computer format tended to perform poorest from the History Lecture, compared to Physical and Social (Tukey HSD, <em>p</em>&lt;.05). However, when material was presented in the standard format, students performed poorest in the Social condition (<em>p</em>&lt;.05), while the other two were not different.
<p>
Considering the latter interaction, a detailed analysis of performance as a function of lecture revaled that 8th Graders performed better than their 5th grade counterparts only in the Social lecture, <span class="math inline">\(F(1,60) = 16.71, p &lt; .001, \eta_p^2=0.21\)</span>.
<p>
<p>In all conditions, students performed better when presented the material via computer compared to the standard presentation, <span class="math inline">\([F(2,60)=7.09, p=.002, \eta_p^2=.19]\)</span> (see Figure 1).</p>
</blockquote>
</div>
</div>
<div id="example-3-omg-multiple-two-way-interactions-and-a-nasty-three-way" class="section level2">
<h2><span class="header-section-number">12.4</span> EXAMPLE 3: OMG, multiple two way interactions and a nasty three-way!!!</h2>
<p>Finally let’s take a look at some data that is all over the place:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">higherEx3 &lt;-<span class="st"> </span><span class="kw">read_delim</span>(<span class="st">&quot;https://raw.githubusercontent.com/tehrandavis/statsRepo/master/statsData/ANOVA5_higherEx3.txt&quot;</span>, 
    <span class="dt">delim =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Subject = col_integer(),
##   Grade = col_character(),
##   Lecture = col_character(),
##   Presentation = col_character(),
##   Score = col_integer()
## )</code></pre>
<div id="plotting" class="section level3">
<h3><span class="header-section-number">12.4.1</span> Plotting:</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(higherEx3, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Lecture, <span class="dt">y =</span> Score, <span class="dt">group =</span> <span class="kw">interaction</span>(Presentation, 
    Grade))) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;pointrange&quot;</span>, <span class="dt">fun.data =</span> <span class="st">&quot;mean_se&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.5</span>), 
    <span class="kw">aes</span>(<span class="dt">shape =</span> Presentation)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_summary</span>(<span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, <span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.5</span>), 
    <span class="kw">aes</span>(<span class="dt">linetype =</span> Grade)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">16</span>, 
    <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="dt">lineheight =</span> <span class="fl">0.55</span>), <span class="dt">axis.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>), <span class="dt">legend.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>, 
    <span class="dt">face =</span> <span class="st">&quot;bold&quot;</span>), <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.15</span>)) <span class="op">+</span><span class="st"> </span>
<span class="kw">xlab</span>(<span class="st">&quot;Lecture&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Score&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.margin =</span> <span class="kw">unit</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>), 
    <span class="st">&quot;in&quot;</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">50</span>)) <span class="op">+</span><span class="st"> </span>
<span class="co"># stack legend boxes horizontally:</span>
<span class="kw">theme</span>(<span class="dt">legend.box =</span> <span class="st">&quot;horizontal&quot;</span>)

<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-383-1.png" width="672" /></p>
</div>
<div id="running-the-anova-4" class="section level3">
<h3><span class="header-section-number">12.4.2</span> running the ANOVA:</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">omnibus.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> higherEx3, <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>, 
    <span class="st">&quot;Presentation&quot;</span>, <span class="st">&quot;Grade&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture, Presentation, Grade</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture, Presentation, Grade</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">omnibus.aov<span class="op">$</span>anova_table</code></pre></div>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: Score
##                            num Df den Df    MSE       F     pes    Pr(&gt;F)
## Lecture                         2     60 42.861 11.6436 0.27960 5.336e-05
## Presentation                    1     60 42.861 36.1491 0.37597 1.171e-07
## Grade                           1     60 42.861 65.6189 0.52236 3.302e-11
## Lecture:Presentation            2     60 42.861  4.7609 0.13696 0.0120482
## Lecture:Grade                   2     60 42.861  3.7835 0.11199 0.0283455
## Presentation:Grade              1     60 42.861 16.2592 0.21321 0.0001583
## Lecture:Presentation:Grade      2     60 42.861  3.8743 0.11437 0.0261541
##                               
## Lecture                    ***
## Presentation               ***
## Grade                      ***
## Lecture:Presentation       *  
## Lecture:Grade              *  
## Presentation:Grade         ***
## Lecture:Presentation:Grade *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>O.M.F.G., everything is significant!!! What to do!!!</p>
<p>Remember, the first thing that we do is tackle the highest-order interaction. In this case we should tease-out the three-way. Again, we should look to our plot to help guide us in what to do. Looking at the plot it appears that different things are happening by Grade. The <code>Presentation:Lecture</code> lines tend to stay parallel for the 5th graders, but not as much for the 8th graders. At the same time the gaps between the two lines are different by grade. So, my advice would be to attack the 3-way interaction by looking at the individual <code>Lecture:Presentation</code> interactions on each Grade.</p>
</div>
<div id="fifth-graders-lecturepresentation-interaction." class="section level3">
<h3><span class="header-section-number">12.4.3</span> Fifth Graders, Lecture:Presentation interaction.</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fifth.data &lt;-<span class="st"> </span><span class="kw">filter</span>(higherEx3, Grade <span class="op">==</span><span class="st"> &quot;5th&quot;</span>)

fifth.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> fifth.data, <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>, 
    <span class="st">&quot;Presentation&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture, Presentation</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture, Presentation</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, fifth.aov)</code></pre></div>
<pre><code>##      Effect                 full_mse
## [1,] &quot;Lecture&quot;              &quot;42.861&quot;
## [2,] &quot;Presentation&quot;         &quot;42.861&quot;
## [3,] &quot;Lecture:Presentation&quot; &quot;42.861&quot;
##      ftest                                  
## [1,] &quot;F(2,60) = 2.167, p = 0.123, pes=0.067&quot;
## [2,] &quot;F(1,60) = 1.96, p = 0.167, pes=0.032&quot; 
## [3,] &quot;F(2,60) = 0.024, p = 0.976, pes=0.001&quot;</code></pre>
<p>You’ll note that our results include simple effects for Lecture and Presentation for 5th graders as well as their interaction. That said, there are no effects when looking at the fifth graders.</p>
</div>
<div id="eighth-graders-lecturepresentation-interaction." class="section level3">
<h3><span class="header-section-number">12.4.4</span> Eighth Graders, Lecture:Presentation interaction.</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">eighth.data &lt;-<span class="st"> </span><span class="kw">subset</span>(higherEx3, Grade <span class="op">==</span><span class="st"> &quot;8th&quot;</span>)

eighth.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> eighth.data, <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>, 
    <span class="st">&quot;Presentation&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture, Presentation</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture, Presentation</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, eighth.aov)</code></pre></div>
<pre><code>##      Effect                 full_mse
## [1,] &quot;Lecture&quot;              &quot;42.861&quot;
## [2,] &quot;Presentation&quot;         &quot;42.861&quot;
## [3,] &quot;Lecture:Presentation&quot; &quot;42.861&quot;
##      ftest                                  
## [1,] &quot;F(2,60) = 13.261, p &lt; .001, pes=0.307&quot;
## [2,] &quot;F(1,60) = 50.448, p &lt; .001, pes=0.457&quot;
## [3,] &quot;F(2,60) = 8.611, p &lt; .001, pes=0.223&quot;</code></pre>
<p>The detailed <code>Lecture:Presentation</code> analysis for the 8th graders revealed both main effects and their interaction. We need to follow-up on this interaction in the 8th-grade data. In this case we would look at the effect of Lecture on each level of Presentation for the eighth graders. To do this we first subset the data further:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">eighth.computer.data &lt;-<span class="st"> </span><span class="kw">filter</span>(eighth.data, Presentation <span class="op">==</span><span class="st"> &quot;Computer&quot;</span>)
eighth.standard.data &lt;-<span class="st"> </span><span class="kw">filter</span>(eighth.data, Presentation <span class="op">==</span><span class="st"> &quot;Standard&quot;</span>)</code></pre></div>
<div id="th-graders-computer-presentation" class="section level4">
<h4><span class="header-section-number">12.4.4.1</span> 8th graders: Computer presentation</h4>
<p>ANOVA of Lecture on the 8th graders via Computer presentation:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">eighth.computer.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> eighth.computer.data, 
    <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, eighth.computer.aov)</code></pre></div>
<pre><code>##      Effect    full_mse ftest                                 
## [1,] &quot;Lecture&quot; &quot;42.861&quot; &quot;F(2,60) = 2.264, p = 0.113, pes=0.07&quot;</code></pre>
<p>No effect for lecture type for 8th graders using the computer presentation.</p>
</div>
<div id="th-graders-standard-presentation" class="section level4">
<h4><span class="header-section-number">12.4.4.2</span> 8th graders: Standard presentation</h4>
<p>ANOVA of Lecture on the 8th graders via Standard presentation</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">eighth.standard.aov &lt;-<span class="st"> </span>afex<span class="op">::</span><span class="kw">aov_ez</span>(<span class="dt">id =</span> <span class="st">&quot;Subject&quot;</span>, <span class="dt">dv =</span> <span class="st">&quot;Score&quot;</span>, <span class="dt">data =</span> eighth.standard.data, 
    <span class="dt">between =</span> <span class="kw">c</span>(<span class="st">&quot;Lecture&quot;</span>), <span class="dt">within =</span> <span class="ot">NULL</span>, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">return =</span> <span class="st">&quot;afex_aov&quot;</span>, <span class="dt">anova_table =</span> <span class="kw">list</span>(<span class="dt">es =</span> <span class="st">&quot;pes&quot;</span>))</code></pre></div>
<pre><code>## Converting to factor: Lecture</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Lecture</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simpleEffectsAOV</span>(omnibus.aov, eighth.standard.aov)</code></pre></div>
<pre><code>##      Effect    full_mse ftest                                  
## [1,] &quot;Lecture&quot; &quot;42.861&quot; &quot;F(2,60) = 19.607, p &lt; .001, pes=0.395&quot;</code></pre>
<p>This yielded an effect, so now the necessary follow-up post-hocs:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">agricolae<span class="op">::</span><span class="kw">HSD.test</span>(eighth.standard.data<span class="op">$</span>Score, <span class="dt">trt =</span> eighth.standard.data<span class="op">$</span>Lecture, 
    <span class="dt">DFerror =</span> <span class="dv">60</span>, <span class="dt">MSerror =</span> <span class="fl">42.86</span>, <span class="dt">console =</span> T, <span class="dt">group =</span> T)</code></pre></div>
<pre><code>## 
## Study: eighth.standard.data$Score ~ eighth.standard.data$Lecture
## 
## HSD Test for eighth.standard.data$Score 
## 
## Mean Square Error:  42.86 
## 
## eighth.standard.data$Lecture,  means
## 
##          eighth.standard.data.Score       std r Min Max
## History                    31.16667  9.867455 6  21  44
## Physical                   34.16667 10.980285 6  19  49
## Social                     12.33333  3.723797 6   7  17
## 
## Alpha: 0.05 ; DF Error: 60 
## Critical Value of Studentized Range: 3.398661 
## 
## Minimun Significant Difference: 9.083607 
## 
## Treatments with the same letter are not significantly different.
## 
##          eighth.standard.data$Score groups
## Physical                   34.16667      a
## History                    31.16667      a
## Social                     12.33333      b</code></pre>
<p>Scores for the Social test were less than the Physical and History.</p>
</div>
</div>
<div id="constructing-a-narrative" class="section level3">
<h3><span class="header-section-number">12.4.5</span> Constructing a narrative:</h3>
<p>Given these results, what narrative do you think you can tell? Remember use the plots to unpack what the results are telling you. Our results focused on differences in the <code>Lecture:Presentation</code> analysis for each grade. I would recommend that your story start there. Something to the effect of Lecture and Presentation interact for 8th graders but not 5th graders.</p>
<p>To remind ourselves:</p>
<ul>
<li>Main effects for Lecture, Presentation, and Grade</li>
<li>Two way interactions</li>
<li>Three-way interaction that we focus on</li>
<li>The results of the 3-way interaction, by Grade:</li>
<li>5th graders = no effects</li>
<li>8th graders = Lecture × Presentation interaction, where there was a null effect for Lecture on the Computer presentation, but an effect for Lecture on the Standard Presentation.</li>
</ul>
<p>Now the narrative:</p>
<p>… to answer this question we conducted a 2 (Grade) × 2 (Presentation) × 3 (Lecture) between effects ANOVA. Our ANOVA revealed a three-way, Grade × Presentation × Lecture type interaction, <em>F</em>(2, 60) = 3.87, <em>p</em> = .03, <span class="math inline">\(\eta_p^2\)</span> = .11. To address this interaction we conducted seperate Presentation × Lecture ANOVA for each Grade. Our results for 5th graders showed no main effects nor an interaction (<em>p</em> &gt; .05). For 8th graders, we found an Presentation × Lecture interaction, <em>F</em>(2, 60) = 8.61, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2\)</span> = .22. While there were no differences due to Lecture type for 8th graders presented information via computer (<em>p</em> &gt; .05), 8th graders in the Standard presentation, <em>F</em>(2, 60) = 19.61, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2\)</span> = .40 tended to perform worse for the Social lecture (<em>M</em> ± <em>SD</em> = 12.33 ± 3.72) than for the History (31.17 ± 9.87) and Physical (34.17 ± 10.98) lectures (Tukey HSD, <em>p</em> &lt; .05).</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="anova-iv-interactions-simple-effects.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova6-within-subjects.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["Vignettes.pdf", "Vignettes.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
