<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>musings of the Professor</title>
  <meta name="description" content="Weekly examples and musings related to PSYC 7014.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="musings of the Professor" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Weekly examples and musings related to PSYC 7014." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="musings of the Professor" />
  
  <meta name="twitter:description" content="Weekly examples and musings related to PSYC 7014." />
  

<meta name="author" content="Tehran J. Davis">


<meta name="date" content="2018-12-15">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="probability-and-the-binomial-distribution.html">
<link rel="next" href="correlation-and-regression.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Words from the Professor</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Weekly musings</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to R / getting to know your data</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-and-loading-an-r-package"><i class="fa fa-check"></i><b>1.1</b> Installing and loading an R package:</a><ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-a-package-using-the-gui"><i class="fa fa-check"></i><b>1.1.1</b> Installing a package using the GUI</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-packages-with-install.packages"><i class="fa fa-check"></i><b>1.1.2</b> Installing packages with <code>install.packages()</code></a></li>
<li class="chapter" data-level="1.1.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#an-important-note-on-knitting-with-install.packages"><i class="fa fa-check"></i><b>1.1.3</b> An IMPORTANT note on knitting with install.packages:</a></li>
<li class="chapter" data-level="1.1.4" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-packages-with-library"><i class="fa fa-check"></i><b>1.1.4</b> Loading packages with <code>library()</code></a></li>
<li class="chapter" data-level="1.1.5" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-packages-with-require"><i class="fa fa-check"></i><b>1.1.5</b> Loading packages with <code>require()</code></a></li>
<li class="chapter" data-level="1.1.6" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-and-loading-packages-like-a-ninja"><i class="fa fa-check"></i><b>1.1.6</b> Installing and loading packages like a ninja</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-in-data"><i class="fa fa-check"></i><b>1.2</b> Loading in data</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-in-local-data-using-a-gui"><i class="fa fa-check"></i><b>1.2.1</b> Loading in local data using a GUI:</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#importing-data-from-the-web"><i class="fa fa-check"></i><b>1.2.2</b> importing data from the web</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#downloading-data"><i class="fa fa-check"></i><b>1.2.3</b> Downloading data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#looking-ahead"><i class="fa fa-check"></i><b>1.3</b> Looking ahead…</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html"><i class="fa fa-check"></i><b>2</b> Measures of distribution, central tendency, PLOTS… oh my!</a><ul>
<li class="chapter" data-level="2.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#getting-measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Getting measures of central tendency</a></li>
<li class="chapter" data-level="2.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-the-distribution-with-a-histogram"><i class="fa fa-check"></i><b>2.2</b> Plotting the distribution with a histogram</a><ul>
<li class="chapter" data-level="2.2.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#using-hist"><i class="fa fa-check"></i><b>2.2.1</b> Using <code>hist()</code></a></li>
<li class="chapter" data-level="2.2.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-a-histogram-with-ggplot"><i class="fa fa-check"></i><b>2.2.2</b> Plotting a histogram with <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-your-data-in-a-boxplot"><i class="fa fa-check"></i><b>2.3</b> Plotting your data in a boxplot:</a><ul>
<li class="chapter" data-level="2.3.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#turning-numeric-data-into-categorical"><i class="fa fa-check"></i><b>2.3.1</b> turning numeric data into categorical</a></li>
<li class="chapter" data-level="2.3.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#boxplotting-using-ggplot"><i class="fa fa-check"></i><b>2.3.2</b> boxplotting using <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#assessing-the-data-for-normality"><i class="fa fa-check"></i><b>2.4</b> Assessing the data for normality</a><ul>
<li class="chapter" data-level="2.4.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#q-q-plots"><i class="fa fa-check"></i><b>2.4.1</b> Q-Q Plots</a></li>
<li class="chapter" data-level="2.4.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#generating-a-theoretical-normal-distribution."><i class="fa fa-check"></i><b>2.4.2</b> Generating a theoretical normal distribution.</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#subsetting-your-data"><i class="fa fa-check"></i><b>2.5</b> Subsetting your data</a></li>
<li class="chapter" data-level="2.6" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#looking-ahead-means-and-better-models"><i class="fa fa-check"></i><b>2.6</b> Looking ahead: Means and better models</a><ul>
<li class="chapter" data-level="2.6.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-highest-probability"><i class="fa fa-check"></i><b>2.6.1</b> mean as highest probability:</a></li>
<li class="chapter" data-level="2.6.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-fulcrum-point"><i class="fa fa-check"></i><b>2.6.2</b> mean as fulcrum point</a></li>
<li class="chapter" data-level="2.6.3" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-minimizing-random-error"><i class="fa fa-check"></i><b>2.6.3</b> mean as minimizing random error</a></li>
<li class="chapter" data-level="2.6.4" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#but-we-can-do-better-than-that"><i class="fa fa-check"></i><b>2.6.4</b> but we can do better than that</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html"><i class="fa fa-check"></i><b>3</b> Sampling distributions and building the logic of NHST</a><ul>
<li class="chapter" data-level="3.1" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-sampling-distribution"><i class="fa fa-check"></i><b>3.1</b> The sampling distribution</a></li>
<li class="chapter" data-level="3.2" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>3.2</b> Standard error of the mean</a></li>
<li class="chapter" data-level="3.3" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-difference-distribution"><i class="fa fa-check"></i><b>3.3</b> The difference distribution</a></li>
<li class="chapter" data-level="3.4" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-null-distribution"><i class="fa fa-check"></i><b>3.4</b> The Null distribution</a></li>
<li class="chapter" data-level="3.5" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#probabilty-of-observed-differences"><i class="fa fa-check"></i><b>3.5</b> Probabilty of observed differences</a></li>
<li class="chapter" data-level="3.6" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#a-note-about-sample-size"><i class="fa fa-check"></i><b>3.6</b> A note about sample size</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html"><i class="fa fa-check"></i><b>4</b> Probability and the Binomial Distribution</a><ul>
<li class="chapter" data-level="4.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#a-few-words-on-where-we-are-at-so-far"><i class="fa fa-check"></i><b>4.1</b> A few words on where we are at so far…</a></li>
<li class="chapter" data-level="4.2" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#okay-on-to-this-weeks-example-analyses"><i class="fa fa-check"></i><b>4.2</b> Okay on to this week’s example analyses:</a></li>
<li class="chapter" data-level="4.3" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#classic-example-the-coin-flip"><i class="fa fa-check"></i><b>4.3</b> Classic example: The coin flip</a><ul>
<li class="chapter" data-level="4.3.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#how-many-heads-would-we-get-if-we-flipped-a-fair-coin-10-times"><i class="fa fa-check"></i><b>4.3.1</b> How many heads would we get if we flipped a fair coin 10 times?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#changing-the-parameters"><i class="fa fa-check"></i><b>4.4</b> Changing the parameters</a><ul>
<li class="chapter" data-level="4.4.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#constructing-a-table-of-outcome-probabilities"><i class="fa fa-check"></i><b>4.4.1</b> Constructing a table of outcome probabilities:</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#assessing-cummulative-probability"><i class="fa fa-check"></i><b>4.4.2</b> Assessing cummulative probability</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#catching-a-cheat"><i class="fa fa-check"></i><b>4.5</b> Catching a cheat</a></li>
<li class="chapter" data-level="4.6" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#one-last-thing-permutations-combinations-and-building-functions"><i class="fa fa-check"></i><b>4.6</b> One last thing… Permutations, combinations, and building functions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html"><i class="fa fa-check"></i><b>5</b> Chi-square and associated methods</a><ul>
<li class="chapter" data-level="5.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#goodness-of-fit-test"><i class="fa fa-check"></i><b>5.1</b> Goodness of fit test</a><ul>
<li class="chapter" data-level="5.1.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#what-to-do-if-you-are-given-a-table-with-tallies"><i class="fa fa-check"></i><b>5.1.1</b> What to do if you are given a table with tallies</a></li>
<li class="chapter" data-level="5.1.2" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#assuming-all-things-are-not-equal"><i class="fa fa-check"></i><b>5.1.2</b> Assuming all things are NOT equal</a></li>
<li class="chapter" data-level="5.1.3" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#real-data-is-likely-not-pre-tallied"><i class="fa fa-check"></i><b>5.1.3</b> Real data is likely NOT pre-tallied</a></li>
<li class="chapter" data-level="5.1.4" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#getting-counts-the-in-class-way-not-recommended"><i class="fa fa-check"></i><b>5.1.4</b> getting counts the in-class way (not recommended)</a></li>
<li class="chapter" data-level="5.1.5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#getting-counts-the-table-way-my-new-recommendation"><i class="fa fa-check"></i><b>5.1.5</b> getting counts the <code>table()</code> way (my new recommendation)</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#contingency-table-analysis-in-r"><i class="fa fa-check"></i><b>5.2</b> Contingency Table Analysis in R</a><ul>
<li class="chapter" data-level="5.2.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#okay-but-what-about-with-real-data"><i class="fa fa-check"></i><b>5.2.1</b> Okay, but what about with REAL DATA:</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#effect-sizes-and-odds-ratios"><i class="fa fa-check"></i><b>5.3</b> Effect Sizes and Odds Ratios</a></li>
<li class="chapter" data-level="5.4" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#fishers-exact-test"><i class="fa fa-check"></i><b>5.4</b> Fisher’s exact test</a></li>
<li class="chapter" data-level="5.5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#cohens-kappa"><i class="fa fa-check"></i><b>5.5</b> Cohen’s kappa</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html"><i class="fa fa-check"></i><b>6</b> Correlation and Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#the-relationship-btw-stress-and-health"><i class="fa fa-check"></i><b>6.1</b> The Relationship b/tw Stress and Health</a><ul>
<li class="chapter" data-level="6.1.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#testing-our-assumptions"><i class="fa fa-check"></i><b>6.1.1</b> Testing our assumptions</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#plotting-the-data"><i class="fa fa-check"></i><b>6.2</b> Plotting the data</a></li>
<li class="chapter" data-level="6.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#covariance-and-correlation"><i class="fa fa-check"></i><b>6.3</b> Covariance and Correlation</a><ul>
<li class="chapter" data-level="6.3.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#covariance"><i class="fa fa-check"></i><b>6.3.1</b> Covariance</a></li>
<li class="chapter" data-level="6.3.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#correlation"><i class="fa fa-check"></i><b>6.3.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#sigfnificance-testing-r"><i class="fa fa-check"></i><b>6.4</b> Sigfnificance testing <span class="math inline">\(r\)</span></a></li>
<li class="chapter" data-level="6.5" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#fitting-the-data-to-a-model"><i class="fa fa-check"></i><b>6.5</b> Fitting the data to a model</a></li>
<li class="chapter" data-level="6.6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#linear-models-in-r"><i class="fa fa-check"></i><b>6.6</b> Linear models in R</a><ul>
<li class="chapter" data-level="6.6.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#attributes-of-class-lm"><i class="fa fa-check"></i><b>6.6.1</b> Attributes of class <code>lm</code>:</a></li>
<li class="chapter" data-level="6.6.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#testing-the-residuals"><i class="fa fa-check"></i><b>6.6.2</b> Testing the residuals</a></li>
<li class="chapter" data-level="6.6.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#using-your-lm-object-with-other-functions"><i class="fa fa-check"></i><b>6.6.3</b> Using your <code>lm</code> object with other functions</a></li>
<li class="chapter" data-level="6.6.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#plotting-the-regression-line"><i class="fa fa-check"></i><b>6.6.4</b> Plotting the regression line</a></li>
<li class="chapter" data-level="6.6.5" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#a-note-on-degrees-of-freedom-of-our-model"><i class="fa fa-check"></i><b>6.6.5</b> A note on degrees of freedom of our model</a></li>
<li class="chapter" data-level="6.6.6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#interpreting-the-output"><i class="fa fa-check"></i><b>6.6.6</b> Interpreting the output</a></li>
<li class="chapter" data-level="6.6.7" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#the-coeff.-of-determination-as-index-of-explanatory-value"><i class="fa fa-check"></i><b>6.6.7</b> The coeff. of determination as index of explanatory value</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#write-up-and-presentaion"><i class="fa fa-check"></i><b>6.7</b> Write up and presentaion</a></li>
<li class="chapter" data-level="6.8" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#advanced-plotting"><i class="fa fa-check"></i><b>6.8</b> Advanced plotting</a><ul>
<li class="chapter" data-level="6.8.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#adding-text-to-the-plot"><i class="fa fa-check"></i><b>6.8.1</b> Adding text to the plot</a></li>
<li class="chapter" data-level="6.8.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#addnig-text-like-a-r-ninja"><i class="fa fa-check"></i><b>6.8.2</b> addnig text like a R-ninja:</a></li>
<li class="chapter" data-level="6.8.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#placing-plots-side-by-side-in-a-grid"><i class="fa fa-check"></i><b>6.8.3</b> Placing plots side-by-side in a grid</a></li>
<li class="chapter" data-level="6.8.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#two-series-on-the-same-damn-plot"><i class="fa fa-check"></i><b>6.8.4</b> Two series on the same damn plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html"><i class="fa fa-check"></i><b>7</b> Testing differences in means: t-test</a><ul>
<li class="chapter" data-level="7.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#things-to-consider-before-running-the-t-test"><i class="fa fa-check"></i><b>7.1</b> Things to consider before running the t-test</a><ul>
<li class="chapter" data-level="7.1.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#what-is-the-nature-of-your-sample-data"><i class="fa fa-check"></i><b>7.1.1</b> What is the nature of your sample data?</a></li>
<li class="chapter" data-level="7.1.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#what-is-the-structure-of-your-data-file"><i class="fa fa-check"></i><b>7.1.2</b> What is the structure of your data file?</a></li>
<li class="chapter" data-level="7.1.3" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#testing-assumptions"><i class="fa fa-check"></i><b>7.1.3</b> Testing assumptions</a></li>
<li class="chapter" data-level="7.1.4" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#getting-the-descriptive-stats-and-plotting-the-means."><i class="fa fa-check"></i><b>7.1.4</b> Getting the descriptive stats and plotting the means.</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#performing-the-t-test-paired-sample-t-test"><i class="fa fa-check"></i><b>7.2</b> Performing the t-test (Paired sample t-test)</a></li>
<li class="chapter" data-level="7.3" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#measuring-effect-size"><i class="fa fa-check"></i><b>7.3</b> Measuring effect size</a></li>
<li class="chapter" data-level="7.4" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#other-t-tests"><i class="fa fa-check"></i><b>7.4</b> Other <span class="math inline">\(t\)</span> tests:</a><ul>
<li class="chapter" data-level="7.4.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#one-sample"><i class="fa fa-check"></i><b>7.4.1</b> One sample:</a></li>
<li class="chapter" data-level="7.4.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#independent-samples-example"><i class="fa fa-check"></i><b>7.4.2</b> Independent samples example</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#independent-or-paired-sample"><i class="fa fa-check"></i><b>7.5</b> Independent or Paired Sample?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html"><i class="fa fa-check"></i><b>8</b> Analysis of Variance I: the One-way ANOVA</a><ul>
<li class="chapter" data-level="8.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#required-packages"><i class="fa fa-check"></i><b>8.1</b> Required packages</a></li>
<li class="chapter" data-level="8.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#anovas-for-comparing-means"><i class="fa fa-check"></i><b>8.2</b> ANOVAs for comparing means</a></li>
<li class="chapter" data-level="8.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#pre-processing-the-data"><i class="fa fa-check"></i><b>8.3</b> Pre-processing the data:</a><ul>
<li class="chapter" data-level="8.3.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#recoding-the-factors-if-dummy-coded"><i class="fa fa-check"></i><b>8.3.1</b> Recoding the factors (if dummy coded)</a></li>
<li class="chapter" data-level="8.3.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#renaming-column-headers"><i class="fa fa-check"></i><b>8.3.2</b> Renaming column headers</a></li>
<li class="chapter" data-level="8.3.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reordering-your-levels"><i class="fa fa-check"></i><b>8.3.3</b> Reordering your levels</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#assumptions-for-anova"><i class="fa fa-check"></i><b>8.4</b> Assumptions for ANOVA</a><ul>
<li class="chapter" data-level="8.4.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#checking-the-normality-assumption-option-1"><i class="fa fa-check"></i><b>8.4.1</b> Checking the normality assumption, OPTION 1</a></li>
<li class="chapter" data-level="8.4.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#checking-the-normality-assumption-option-2"><i class="fa fa-check"></i><b>8.4.2</b> Checking the normality assumption, OPTION 2</a></li>
<li class="chapter" data-level="8.4.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#homogeneity-of-variance"><i class="fa fa-check"></i><b>8.4.3</b> Homogeneity of Variance</a></li>
<li class="chapter" data-level="8.4.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#what-to-do-if-the-assumptions-are-violated"><i class="fa fa-check"></i><b>8.4.4</b> What to do if the assumptions are violated?</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#running-the-anova-in-r"><i class="fa fa-check"></i><b>8.5</b> Running the ANOVA in R:</a></li>
<li class="chapter" data-level="8.6" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reporting-your-data"><i class="fa fa-check"></i><b>8.6</b> Reporting your data</a><ul>
<li class="chapter" data-level="8.6.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reporting-in-the-text"><i class="fa fa-check"></i><b>8.6.1</b> Reporting in the text</a></li>
<li class="chapter" data-level="8.6.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#what-the-omnibus-anova-tells-you"><i class="fa fa-check"></i><b>8.6.2</b> What the omnibus ANOVA tells you</a></li>
<li class="chapter" data-level="8.6.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#plots"><i class="fa fa-check"></i><b>8.6.3</b> Plots</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#digging-deeper-anova-and-regression"><i class="fa fa-check"></i><b>8.7</b> DIGGING DEEPER: ANOVA and Regression</a><ul>
<li class="chapter" data-level="8.7.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#regression-method-v.-means-method"><i class="fa fa-check"></i><b>8.7.1</b> Regression method v. means method</a></li>
<li class="chapter" data-level="8.7.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#comparing-two-models"><i class="fa fa-check"></i><b>8.7.2</b> Comparing two models</a></li>
<li class="chapter" data-level="8.7.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#means-method-calculations"><i class="fa fa-check"></i><b>8.7.3</b> Means method calculations</a></li>
<li class="chapter" data-level="8.7.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#bringing-it-together-its-all-about-the-residuals-baby"><i class="fa fa-check"></i><b>8.7.4</b> Bringing it together: it’s all about the residuals, baby</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><i class="fa fa-check"></i><b>9</b> Analysis of Variance II: Multiple comparisons in One-way ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#getting-started-loading-packages-and-data"><i class="fa fa-check"></i><b>9.1</b> Getting started (loading packages and data)</a></li>
<li class="chapter" data-level="9.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#running-the-one-way-anova"><i class="fa fa-check"></i><b>9.2</b> Running the One-way ANOVA</a></li>
<li class="chapter" data-level="9.3" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#post-hoc-tests"><i class="fa fa-check"></i><b>9.3</b> Post-hoc tests</a><ul>
<li class="chapter" data-level="9.3.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#bonferonni-dunn-and-holm-tests"><i class="fa fa-check"></i><b>9.3.1</b> Bonferonni-Dunn and Holm tests</a></li>
<li class="chapter" data-level="9.3.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#tukey-hsd-and-regwq-tests"><i class="fa fa-check"></i><b>9.3.2</b> Tukey HSD and REGWQ tests</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#the-logic-of-planned-contrasts"><i class="fa fa-check"></i><b>9.4</b> The logic of Planned contrasts</a></li>
<li class="chapter" data-level="9.5" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#performing-planned-contrasts-in-r"><i class="fa fa-check"></i><b>9.5</b> Performing planned contrasts in R</a><ul>
<li class="chapter" data-level="9.5.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#making-the-output-easier-to-read"><i class="fa fa-check"></i><b>9.5.1</b> Making the output easier to read</a></li>
<li class="chapter" data-level="9.5.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#calculating-your-effect-size"><i class="fa fa-check"></i><b>9.5.2</b> Calculating your effect size</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#reporting-your-results"><i class="fa fa-check"></i><b>9.6</b> Reporting your results</a></li>
<li class="chapter" data-level="9.7" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#a-note-on-using-the-multcomp-package-v.-using-the-base-stats-method"><i class="fa fa-check"></i><b>9.7</b> A note on using the <code>multcomp</code> package v. using the base stats method</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html"><i class="fa fa-check"></i><b>10</b> Analysis of Varience III: Factorial ANOVA</a><ul>
<li class="chapter" data-level="10.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#main-effect-main-effect-and-interactions-oh-my"><i class="fa fa-check"></i><b>10.1</b> Main effect, main effect, and interactions… oh my!</a></li>
<li class="chapter" data-level="10.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#example-a-22-anova"><i class="fa fa-check"></i><b>10.2</b> Example: a 2×2 ANOVA</a></li>
<li class="chapter" data-level="10.3" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#making-sense-of-plots"><i class="fa fa-check"></i><b>10.3</b> Making sense of plots</a><ul>
<li class="chapter" data-level="10.3.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-plots"><i class="fa fa-check"></i><b>10.3.1</b> Interaction plots</a></li>
<li class="chapter" data-level="10.3.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#plotting-main-effects"><i class="fa fa-check"></i><b>10.3.2</b> Plotting main effects</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-lm-method"><i class="fa fa-check"></i><b>10.4</b> Running the ANOVA <code>lm()</code> method</a></li>
<li class="chapter" data-level="10.5" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-in-the-afexaov_ez-method"><i class="fa fa-check"></i><b>10.5</b> Running the ANOVA in the <code>afex::aov_ez()</code> method:</a></li>
<li class="chapter" data-level="10.6" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#getting-cell-means"><i class="fa fa-check"></i><b>10.6</b> Getting cell means</a></li>
<li class="chapter" data-level="10.7" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#more-examples-a-2-3-anova"><i class="fa fa-check"></i><b>10.7</b> More examples: a 2 × 3 ANOVA</a><ul>
<li class="chapter" data-level="10.7.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova"><i class="fa fa-check"></i><b>10.7.1</b> Running the ANOVA</a></li>
<li class="chapter" data-level="10.7.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#apa-plotting"><i class="fa fa-check"></i><b>10.7.2</b> APA plotting</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#anova-howell-13.1"><i class="fa fa-check"></i><b>10.8</b> 2 × 5 ANOVA (Howell 13.1)</a><ul>
<li class="chapter" data-level="10.8.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-1"><i class="fa fa-check"></i><b>10.8.1</b> Running the ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#one-last-example"><i class="fa fa-check"></i><b>10.9</b> One last example,</a><ul>
<li class="chapter" data-level="10.9.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-2"><i class="fa fa-check"></i><b>10.9.1</b> Running the ANOVA</a></li>
<li class="chapter" data-level="10.9.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-plot"><i class="fa fa-check"></i><b>10.9.2</b> Interaction plot</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-v.-no-interaction"><i class="fa fa-check"></i><b>10.10</b> Interaction v. no interaction</a><ul>
<li class="chapter" data-level="10.10.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#no-interaction-how-about-some-posthocs"><i class="fa fa-check"></i><b>10.10.1</b> No interaction? How about some posthocs?</a></li>
<li class="chapter" data-level="10.10.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#what-to-do-if-you-do-have-an-interaction"><i class="fa fa-check"></i><b>10.10.2</b> what to do if you DO have an interaction</a></li>
</ul></li>
<li class="chapter" data-level="10.11" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#what-about-planned-contrasts"><i class="fa fa-check"></i><b>10.11</b> What about planned contrasts?</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html"><i class="fa fa-check"></i><b>11</b> ANOVA IV: Interactions &amp; simple Effects</a><ul>
<li class="chapter" data-level="11.1" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#the-data-set"><i class="fa fa-check"></i><b>11.1</b> the data set</a></li>
<li class="chapter" data-level="11.2" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#plotting-the-data-and-descriptive-stats"><i class="fa fa-check"></i><b>11.2</b> Plotting the data and descriptive stats</a></li>
<li class="chapter" data-level="11.3" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#the-omnibus-anova-and-assumption-tests"><i class="fa fa-check"></i><b>11.3</b> the Omnibus ANOVA (and assumption tests)</a></li>
<li class="chapter" data-level="11.4" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#running-the-simple-effects-anova-in-6-steps"><i class="fa fa-check"></i><b>11.4</b> Running the simple effects ANOVA in 6 steps:</a><ul>
<li class="chapter" data-level="11.4.1" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-1-get-the-omnibus-anova"><i class="fa fa-check"></i><b>11.4.1</b> step 1: get the omnibus ANOVA:</a></li>
<li class="chapter" data-level="11.4.2" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-2-get-the-mserror-error-df-and-error-ss-from-omnibus-anova"><i class="fa fa-check"></i><b>11.4.2</b> step 2: get the MSError, Error df, and Error SS from omnibus ANOVA</a></li>
<li class="chapter" data-level="11.4.3" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-3-subset-your-data-accordingly"><i class="fa fa-check"></i><b>11.4.3</b> step 3: subset your data accordingly</a></li>
<li class="chapter" data-level="11.4.4" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-4-run-your-one-way-simple-effects-anovas"><i class="fa fa-check"></i><b>11.4.4</b> step 4: run your One-way simple effects ANOVA(s)</a></li>
<li class="chapter" data-level="11.4.5" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-5-get-the-treatment-ms-df-ss-and-f-value-from-your-simple-anova"><i class="fa fa-check"></i><b>11.4.5</b> step 5: get the treatment MS, df, SS, and F-value from your simple ANOVA</a></li>
<li class="chapter" data-level="11.4.6" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-6-make-our-corrections"><i class="fa fa-check"></i><b>11.4.6</b> step 6: make our corrections</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#building-a-function-to-ninja-this-for-us"><i class="fa fa-check"></i><b>11.5</b> Building a function to ninja this for us</a></li>
<li class="chapter" data-level="11.6" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#post-hoc-tests-1"><i class="fa fa-check"></i><b>11.6</b> Post hoc tests</a></li>
<li class="chapter" data-level="11.7" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#interpreting-these-results"><i class="fa fa-check"></i><b>11.7</b> Interpreting these results:</a></li>
<li class="chapter" data-level="11.8" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#example-write-up"><i class="fa fa-check"></i><b>11.8</b> Example write-up:</a></li>
<li class="chapter" data-level="11.9" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#performing-this-in-spss-video"><i class="fa fa-check"></i><b>11.9</b> Performing this in SPSS (video)</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA V: Higher Order Factorial ANOVA</a><ul>
<li class="chapter" data-level="12.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#packages-and-data"><i class="fa fa-check"></i><b>12.1</b> Packages and data</a></li>
<li class="chapter" data-level="12.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-1-no-three-way-interaction-single-two-way-interaction"><i class="fa fa-check"></i><b>12.2</b> EXAMPLE 1: no three-way interaction, single two way interaction</a><ul>
<li class="chapter" data-level="12.2.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#first-plot-3-way-interaction-plot"><i class="fa fa-check"></i><b>12.2.1</b> First plot: 3 way interaction plot</a></li>
<li class="chapter" data-level="12.2.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-anova-3"><i class="fa fa-check"></i><b>12.2.2</b> running the ANOVA:</a></li>
<li class="chapter" data-level="12.2.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#replotting-the-2-way-interaction"><i class="fa fa-check"></i><b>12.2.3</b> Replotting the 2-way interaction</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-2-no-three-way-interaction-multiple-main-effects-multiple-2-way-interactions"><i class="fa fa-check"></i><b>12.3</b> EXAMPLE 2: No three-way interaction, multiple main effects, multiple 2 way interactions:</a><ul>
<li class="chapter" data-level="12.3.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#plotting-the-data-1"><i class="fa fa-check"></i><b>12.3.1</b> plotting the data</a></li>
<li class="chapter" data-level="12.3.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-omnibus-anova"><i class="fa fa-check"></i><b>12.3.2</b> running the omnibus ANOVA:</a></li>
<li class="chapter" data-level="12.3.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#testing-the-lecturepresentation-interaction"><i class="fa fa-check"></i><b>12.3.3</b> testing the <code>Lecture:Presentation</code> interaction:</a></li>
<li class="chapter" data-level="12.3.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#testing-the-lecturegrade-interaction"><i class="fa fa-check"></i><b>12.3.4</b> testing the <code>Lecture:Grade</code> interaction:</a></li>
<li class="chapter" data-level="12.3.5" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#simple-effect-anovas-1"><i class="fa fa-check"></i><b>12.3.5</b> simple effect ANOVAs:</a></li>
<li class="chapter" data-level="12.3.6" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#main-takeaways-write-up"><i class="fa fa-check"></i><b>12.3.6</b> Main takeaways / write-up</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-3-omg-multiple-two-way-interactions-and-a-nasty-three-way"><i class="fa fa-check"></i><b>12.4</b> EXAMPLE 3: OMG, multiple two way interactions and a nasty three-way!!!</a><ul>
<li class="chapter" data-level="12.4.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#plotting"><i class="fa fa-check"></i><b>12.4.1</b> Plotting:</a></li>
<li class="chapter" data-level="12.4.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-anova-4"><i class="fa fa-check"></i><b>12.4.2</b> running the ANOVA:</a></li>
<li class="chapter" data-level="12.4.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#fifth-graders-lecturepresentation-interaction."><i class="fa fa-check"></i><b>12.4.3</b> Fifth Graders, Lecture:Presentation interaction.</a></li>
<li class="chapter" data-level="12.4.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#eighth-graders-lecturepresentation-interaction."><i class="fa fa-check"></i><b>12.4.4</b> Eighth Graders, Lecture:Presentation interaction.</a></li>
<li class="chapter" data-level="12.4.5" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#constructing-a-narrative"><i class="fa fa-check"></i><b>12.4.5</b> Constructing a narrative:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html"><i class="fa fa-check"></i><b>13</b> ANOVA6: Within-Subjects</a><ul>
<li class="chapter" data-level="13.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#within-subject-v.-between-subjects"><i class="fa fa-check"></i><b>13.1</b> Within-Subject v. Between Subjects</a><ul>
<li class="chapter" data-level="13.1.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#within-v-between-anova"><i class="fa fa-check"></i><b>13.1.1</b> Within v Between ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-1"><i class="fa fa-check"></i><b>13.2</b> EXAMPLE 1</a><ul>
<li class="chapter" data-level="13.2.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data"><i class="fa fa-check"></i><b>13.2.1</b> loading in the data:</a></li>
<li class="chapter" data-level="13.2.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-2"><i class="fa fa-check"></i><b>13.2.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.2.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-a-within-anova-afex"><i class="fa fa-check"></i><b>13.2.3</b> running a within ANOVA (afex):</a></li>
<li class="chapter" data-level="13.2.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#planned-contrasts"><i class="fa fa-check"></i><b>13.2.4</b> planned contrasts</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-2"><i class="fa fa-check"></i><b>13.3</b> EXAMPLE 2</a><ul>
<li class="chapter" data-level="13.3.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data-1"><i class="fa fa-check"></i><b>13.3.1</b> loading in the data</a></li>
<li class="chapter" data-level="13.3.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-3"><i class="fa fa-check"></i><b>13.3.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.3.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-anova-5"><i class="fa fa-check"></i><b>13.3.3</b> running the ANOVA:</a></li>
<li class="chapter" data-level="13.3.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#post-hocs"><i class="fa fa-check"></i><b>13.3.4</b> post-hocs</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-3"><i class="fa fa-check"></i><b>13.4</b> EXAMPLE 3</a><ul>
<li class="chapter" data-level="13.4.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data-2"><i class="fa fa-check"></i><b>13.4.1</b> loading in the data:</a></li>
<li class="chapter" data-level="13.4.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-4"><i class="fa fa-check"></i><b>13.4.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.4.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-omnibus-anova-1"><i class="fa fa-check"></i><b>13.4.3</b> running the omnibus ANOVA:</a></li>
<li class="chapter" data-level="13.4.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-simple-effects-anovas"><i class="fa fa-check"></i><b>13.4.4</b> running the simple effects ANOVAs</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#how-to-perform-a-within-subjects-analysis-in-spss"><i class="fa fa-check"></i><b>13.5</b> How to perform a within subjects analysis in SPSS:</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html"><i class="fa fa-check"></i><b>14</b> ANOVA VI: Mixed-effects ANOVA (BS + WS)</a><ul>
<li class="chapter" data-level="14.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#example-1-1"><i class="fa fa-check"></i><b>14.1</b> Example 1:</a><ul>
<li class="chapter" data-level="14.1.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#data-import-and-wrangling"><i class="fa fa-check"></i><b>14.1.1</b> data import and wrangling</a></li>
<li class="chapter" data-level="14.1.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#plotting-the-data-5"><i class="fa fa-check"></i><b>14.1.2</b> plotting the data</a></li>
<li class="chapter" data-level="14.1.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#running-our-anova"><i class="fa fa-check"></i><b>14.1.3</b> Running our ANOVA:</a></li>
<li class="chapter" data-level="14.1.4" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#simple-effects"><i class="fa fa-check"></i><b>14.1.4</b> simple effects</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#example-2-1"><i class="fa fa-check"></i><b>14.2</b> Example 2:</a><ul>
<li class="chapter" data-level="14.2.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#data-import-and-wrangling-1"><i class="fa fa-check"></i><b>14.2.1</b> data import and wrangling</a></li>
<li class="chapter" data-level="14.2.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#plotting-the-data-6"><i class="fa fa-check"></i><b>14.2.2</b> plotting the data</a></li>
<li class="chapter" data-level="14.2.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#run-your-omnibus-anova"><i class="fa fa-check"></i><b>14.2.3</b> Run your omnibus ANOVA:</a></li>
<li class="chapter" data-level="14.2.4" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#simple-effects-1"><i class="fa fa-check"></i><b>14.2.4</b> simple effects:</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#to-pool-or-not-to-pool-this-is-the-yada-yada-yada"><i class="fa fa-check"></i><b>14.3</b> to pool or not to pool, this is the yada yada yada</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html"><i class="fa fa-check"></i><b>A</b> Plotting histograms and probability distributions</a><ul>
<li class="chapter" data-level="A.1" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#the-basics"><i class="fa fa-check"></i><b>A.1</b> The Basics</a><ul>
<li class="chapter" data-level="A.1.1" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-1-building-the-canvas"><i class="fa fa-check"></i><b>A.1.1</b> Step 1: Building the canvas</a></li>
<li class="chapter" data-level="A.1.2" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-2-tell-ggplot-what-kind-of-plot-to-make."><i class="fa fa-check"></i><b>A.1.2</b> Step 2: Tell <code>ggplot</code> what kind of plot to make.</a></li>
<li class="chapter" data-level="A.1.3" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-3-adjust-the-axes-and-labels"><i class="fa fa-check"></i><b>A.1.3</b> Step 3: Adjust the axes and labels</a></li>
<li class="chapter" data-level="A.1.4" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-4-adjusting-for-apa"><i class="fa fa-check"></i><b>A.1.4</b> Step 4: Adjusting for APA</a></li>
<li class="chapter" data-level="A.1.5" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-5-add-and-adjust-the-legend"><i class="fa fa-check"></i><b>A.1.5</b> Step 5: Add and adjust the legend</a></li>
<li class="chapter" data-level="A.1.6" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-6-save-the-ggplot."><i class="fa fa-check"></i><b>A.1.6</b> Step 6: Save the <code>ggplot</code>.</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#a-note-about-your-bonus-on-week-4."><i class="fa fa-check"></i><b>A.2</b> A note about your BONUS on Week 4.</a></li>
<li class="chapter" data-level="A.3" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#advanced-stuff"><i class="fa fa-check"></i><b>A.3</b> Advanced stuff</a></li>
</ul></li>
<li class="divider"></li>
<li></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">musings of the Professor</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chi-square-and-associated-methods" class="section level1">
<h1><span class="header-section-number">Week 5</span> Chi-square and associated methods</h1>
<p>This week we will be working through how to conduct and report Chi-square, <span class="math inline">\(\chi^2\)</span>, analyses in <code>R</code>. As mentioned in class we can use <span class="math inline">\(\chi^2\)</span> in several ways: to assess goodness of fit (assuming all is fair), to test for independence, to compare models (see you next semester), and a derivative of the Chi-square logic to test for inter-rater reliability.</p>
<p>In what follows we will walk through each of these scenarios, focusing on how to conduct the analyses in <code>R</code>. For each analysis we will also provide examples of how to construct frequency tables depending on what information is available to you. In some cases you are already provided with pre-tallied frequencies, in other cases you may be given raw data and need to create the tallied frequencies yourself. I realize in class I walked you through several methods of how get the appropriate results. Here I’m just going to focus on the most simple and efficient way to do this.</p>
<p>Here are the packages we’ll be using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pacman<span class="op">::</span><span class="kw">p_load</span>(tidyverse,  
               kableExtra, <span class="co"># creating html tables for this page </span>
               epitools, <span class="co"># calculating odds ratios</span>
               lme4, <span class="co"># for the comparing models example</span>
               vcd, <span class="co"># Cohen&#39;s kappa</span>
               gmodels <span class="co"># makes obsolete a lot of our workshop</span>
               )</code></pre></div>
<p>Also, if you are using a newer version of <code>R</code>, you’ll need to install <code>zoo</code>. <code>vcd</code> depends on <code>zoo</code> to work. If prompted in your Console with the question: “Do you want to install from sources the package which needs compilation?”, type in “no”:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pacman<span class="op">::</span><span class="kw">p_load</span>(zoo)  <span class="co"># this is a package that needs to be installed, but needs a response from you to do so.</span></code></pre></div>
<div id="goodness-of-fit-test" class="section level2">
<h2><span class="header-section-number">5.1</span> Goodness of fit test</h2>
<p>The Goodness of fit test examines how “close“ observed values are to those which would be expected if things were ‘fair’ or equal. Measures of <strong>goodness of fit</strong> test to see if the discrepancy between observed and expected values is a significant discrepancy using the following formula:</p>
<p><span class="math display">\[\chi^2 = \sum{\frac{(O-E)^2}{E}}\]</span> Where <span class="math inline">\(O\)</span> and <span class="math inline">\(E\)</span> refer to the observed frequency and expected frequency respectively.</p>
<div id="what-to-do-if-you-are-given-a-table-with-tallies" class="section level3">
<h3><span class="header-section-number">5.1.1</span> What to do if you are given a table with tallies</h3>
<p>In class I asked you to consider the data from your Howell text, Table 6.1, where the data are taken from a study testing therapeutic touch as a “real” phenomena. Therapeutic touch postulates that one may heal a patient by manipulating their “human energy field”. If this is true, and if patients are indeed sensitive to therapeutic touch, then we would expect that patients should be able to report the effect (position of the healers hand) greater significantly greater than chance. The resulting frequencies and expected were:</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Correct
</th>
<th style="text-align:right;">
Incorrect
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Observed
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
157
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
Expected
</td>
<td style="text-align:right;">
140
</td>
<td style="text-align:right;">
140
</td>
<td style="text-align:right;">
280
</td>
</tr>
</tbody>
</table>
<p>In this case, the tallies are already done for you. You just need to enter them into <code>R</code> as a frequency table.</p>
<div id="creating-the-frequency-table." class="section level4">
<h4><span class="header-section-number">5.1.1.1</span> Creating the frequency table.</h4>
<p>The first important step is to build a matrix object that contains the table. This can be accomplished using the <code>matrix()</code> function. In this case we need to create a 2×2 matrix to place our four values in. The critical thing to remember when entering your values is that you need to go in order either down columns or across rows. By default <code>R</code> prefers you to go down columns, so we’ll just do that here. For simplicity’s sake let’s just create an object to store these values. Since we are doing down columns, the entry order should be 123,140,157,140,280,280.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table_values &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">123</span>, <span class="dv">140</span>, <span class="dv">157</span>, <span class="dv">140</span>, <span class="dv">280</span>, <span class="dv">280</span>)</code></pre></div>
<p>We can then create matrix using the <code>matrix()</code> function with the following arguments:</p>
<ul>
<li><code>data</code>: the values you are putting into the matrix, in this case <code>table_values</code></li>
<li><code>nrow</code> or <code>ncol</code>: the number of rows or columns in the matrix; you only need to enter one or the other</li>
<li><code>byrow</code>: <code>TRUE</code> or <code>FALSE</code>, will the values be entered into the matrix going across by rows (<code>TRUE</code>) or down by columns (<code>FALSE</code>). The function default is <code>FALSE</code>, meaning data is entered by column.</li>
</ul>
<p>So to get our numbers into a matrix named <code>table_6.1</code> we:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table_<span class="fl">6.1</span> &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dt">data =</span> table_values, <span class="dt">nrow =</span> <span class="dv">2</span>)
<span class="co"># no need to enter byrow= as I&#39;m just using the default setting</span>
<span class="kw">show</span>(table_<span class="fl">6.1</span>)</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]  123  157  280
## [2,]  140  140  280</code></pre>
<p>Before moving on, we need to convert this matrix to a table object. This can be accomplished in one fell swoop by adding <code>as.table()</code> to the previous step in a <code>pipe</code>, <code>%&gt;%</code>. Piping was mentioned in the Intro to Tidyverse DataCamp assignment. Basically it says take the previous output and now perform this additional function. Steps that would normally take multiple lines can be done in a single line:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table_<span class="fl">6.1</span> &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dt">data =</span> table_values, <span class="dt">nrow =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as.table</span>()
<span class="co"># the pipe operator %&gt;% is from tidyverse. See Demos</span>
<span class="kw">show</span>(table_<span class="fl">6.1</span>)</code></pre></div>
<pre><code>##     A   B   C
## A 123 157 280
## B 140 140 280</code></pre>
<p>Almost there, not we just need to give our table meaningful names, ABC is not going to cut it. This can be accomplished using <code>rownames()</code> and <code>colnames()</code> and assigning a vector of the appropriate names:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rownames</span>(table_<span class="fl">6.1</span>) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Observed&quot;</span>, <span class="st">&quot;Expected&quot;</span>)
<span class="kw">colnames</span>(table_<span class="fl">6.1</span>) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Correct&quot;</span>, <span class="st">&quot;Incorrect&quot;</span>, <span class="st">&quot;Total&quot;</span>)
<span class="kw">show</span>(table_<span class="fl">6.1</span>)</code></pre></div>
<pre><code>##          Correct Incorrect Total
## Observed     123       157   280
## Expected     140       140   280</code></pre>
<p>And that’s it. Your table is now in <code>R</code> and ready for the next step.</p>
</div>
<div id="running-the-chi-square" class="section level4">
<h4><span class="header-section-number">5.1.1.2</span> Running the Chi-square</h4>
<p>For a simple Goodness of fit test I suggest using the <code>chisq.test()</code> function. Remember from class that this has several important arguments:</p>
<ul>
<li><code>x</code>: a vector (1 dimensional) or matrix (2-dimensional: rows, columns) of the observed data</li>
<li><code>p</code>: a vector (1 dimensional) or matrix (2-dimensional: rows, columns) of the expected data expressed as raw numbers, <span class="math inline">\(E\)</span> or as probabilities <span class="math inline">\(E/N\)</span>.</li>
<li><code>rescale.p</code>: if you use the raw expected values then this needs to be set to <code>TRUE</code></li>
<li><code>correct</code>: perform a Yates correction when calculating the <span class="math inline">\(\chi^2\)</span></li>
</ul>
<p>So now that we have constructed our <code>table_6.1</code>, I would suggest calculating the <span class="math inline">\(\chi^2\)</span> as follows:</p>
<ol style="list-style-type: decimal">
<li>create a matrix of the observed data</li>
<li>create a matrix of the expected data</li>
<li>submit these matrices to <code>chisq.test()</code>:</li>
</ol>
<ul>
<li>correction or no correction: I typically prefer to perform the correction, <strong>BUT ultimately is unnecessary here as <code>correction</code> only applies to 2 by 2 tables.</strong></li>
<li>rescale or no rescale: I typically prefer to enter my raw expecteds and then set <code>rescale.p=TRUE</code></li>
</ul>
<p>So If I were running the Goodness of fit test based upon the data above I might:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># matrix of observed:</span>
observed &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dt">data =</span> <span class="kw">c</span>(<span class="dv">123</span>, <span class="dv">157</span>), <span class="dt">nrow =</span> <span class="dv">1</span>)

<span class="co"># matrix of expected:</span>
expected &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dt">data =</span> <span class="kw">c</span>(<span class="dv">140</span>, <span class="dv">140</span>), <span class="dt">nrow =</span> <span class="dv">1</span>)

<span class="co"># run the chi-square:</span>
<span class="kw">chisq.test</span>(<span class="dt">x =</span> observed, <span class="dt">p =</span> expected, <span class="dt">rescale.p =</span> T)</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observed
## X-squared = 4.1286, df = 1, p-value = 0.04216</code></pre>
<p>That said, remember you only need could just list the observeds:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chisq.test</span>(<span class="dt">x =</span> observed)</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observed
## X-squared = 4.1286, df = 1, p-value = 0.04216</code></pre>
</div>
<div id="using-your-built-r-table" class="section level4">
<h4><span class="header-section-number">5.1.1.3</span> Using your built <code>R</code> table</h4>
<p>You may have noticed that I elected to create my <code>observed</code> and <code>expected</code> objects by entering the data by hand. “Then why on earth did you have us make that damn table?”, you ask? Well I could have also got these values by indexing the table (see Demos, chapter 2). For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table_<span class="fl">6.1</span>[<span class="dv">1</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]</code></pre></div>
<pre><code>##   Correct Incorrect 
##       123       157</code></pre>
<p>gives me my observeds and</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table_<span class="fl">6.1</span>[<span class="dv">2</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]</code></pre></div>
<pre><code>##   Correct Incorrect 
##       140       140</code></pre>
<p>gives me my expecteds. Knowing this I could just run the above <code>chisq.test()</code> as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chisq.test</span>(<span class="dt">x =</span> table_<span class="fl">6.1</span>[<span class="dv">1</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>])</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  table_6.1[1, 1:2]
## X-squared = 4.1286, df = 1, p-value = 0.04216</code></pre>
</div>
</div>
<div id="assuming-all-things-are-not-equal" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Assuming all things are NOT equal</h3>
<p>Let’s assume that we are dealing with a Goodness of fit that involves three or more categories. For example, taken from Howell Table 6.3 a game of Rock, Paper, Scissors.</p>
<p><strong>R-ninjas</strong> Below is the code that I use to create the tables you see on this page. Note that the <code>kable()</code> function is what allows pretty web tables:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table6.<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">30</span>, <span class="dv">21</span>, <span class="dv">24</span>, <span class="dv">25</span>, <span class="dv">25</span>, <span class="dv">25</span>), <span class="dt">ncol =</span> <span class="dv">3</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>)  <span class="co"># I&#39;m a byrow = T person</span>
<span class="kw">rownames</span>(table6.<span class="dv">3</span>) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Observed&quot;</span>, <span class="st">&quot;Expected&quot;</span>)
<span class="kw">colnames</span>(table6.<span class="dv">3</span>) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Rock&quot;</span>, <span class="st">&quot;Paper&quot;</span>, <span class="st">&quot;Scissors&quot;</span>)
table6.<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">as.table</span>(table6.<span class="dv">3</span>)
<span class="kw">show</span>(table6.<span class="dv">3</span>)  <span class="co"># the semicolon here seperates the lines</span></code></pre></div>
<pre><code>##          Rock Paper Scissors
## Observed   30    21       24
## Expected   25    25       25</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">kable</span>(table6.<span class="dv">3</span>, <span class="dt">format =</span> <span class="st">&quot;html&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">kable_styling</span>(<span class="dt">bootstrap_options =</span> <span class="kw">c</span>(<span class="st">&quot;striped&quot;</span>, 
    <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>))</code></pre></div>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Rock
</th>
<th style="text-align:right;">
Paper
</th>
<th style="text-align:right;">
Scissors
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Observed
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
24
</td>
</tr>
<tr>
<td style="text-align:left;">
Expected
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
25
</td>
</tr>
</tbody>
</table>
<p>Assuming equal likelihood of a person selecting Rock, Paper, or Scissors I can just run this test as I did in the previous section. Note that in the code below I’m not even bothering with the expecteds because they are assumed equal:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">observed &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dt">data =</span> <span class="kw">c</span>(<span class="dv">30</span>, <span class="dv">21</span>, <span class="dv">24</span>), <span class="dt">nrow =</span> <span class="dv">1</span>)
<span class="kw">chisq.test</span>(<span class="dt">x =</span> observed)</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observed
## X-squared = 1.68, df = 2, p-value = 0.4317</code></pre>
<p><strong>BUT WHAT IF MY EXPECTEDS AREN’T EQUAL???</strong> That is, what if I know that people are twice as likely to choose Rock than Paper or Scissors. In this case the respective probabilities would be Rock = .5, Paper = .25, Scissors = .25). I can simply adjust <code>p=</code> in my <code>chisq.test()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">expected_probabilities &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dt">data =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>), <span class="dt">nrow =</span> <span class="dv">1</span>)
<span class="kw">chisq.test</span>(<span class="dt">x =</span> observed, <span class="dt">p =</span> expected_probabilities)</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observed
## X-squared = 3.24, df = 2, p-value = 0.1979</code></pre>
<p>As you can see, <span class="math inline">\(\chi^2\)</span> has been adjusted to reflect these new probabilities.</p>
</div>
<div id="real-data-is-likely-not-pre-tallied" class="section level3">
<h3><span class="header-section-number">5.1.3</span> Real data is likely NOT pre-tallied</h3>
<p>In the above examples, the observeds and expecteds were already tallied for you. In the real-world however, you’ll need to do the tallying yourself (or get your RA to do it). Let’s imagine this scenario running a goodness of fit test on a game of Paper, Rock, Scissors, Lizard Spock. This data can be found using this link:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prslOutcomes &lt;-<span class="st"> </span>prslOutcomes &lt;-<span class="st"> </span><span class="kw">read.delim</span>(<span class="st">&quot;https://raw.githubusercontent.com/tehrandavis/statsData/master/prslOutcomes.txt&quot;</span>)</code></pre></div>
<p>Note that you want to be sure that the data object is stored as a <code>data.frame</code> or <code>data_frame</code> and if not convert it to one. Importing a data set from a file typically defaults to a <code>data.frame</code> but here is how to check and convert if necessary:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(prslOutcomes)  <span class="co"># check class of object to ensure data.frame</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prslOutcomes_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(prslOutcomes)  <span class="co"># convert if necessary, not necessary here but an example</span></code></pre></div>
<p>And let’s take a look at the data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prslOutcomes</code></pre></div>
<pre><code>##         Outcomes
## 1           Rock
## 2          Paper
## 3       Scissors
## 4       Scissors
## 5          Paper
## 6           Rock
## 7       Scissors
## 8   Lizard Spock
## 9          Paper
## 10  Lizard Spock
## 11  Lizard Spock
## 12  Lizard Spock
## 13          Rock
## 14      Scissors
## 15  Lizard Spock
## 16  Lizard Spock
## 17          Rock
## 18          Rock
## 19         Paper
## 20  Lizard Spock
## 21          Rock
## 22  Lizard Spock
## 23          Rock
## 24          Rock
## 25         Paper
## 26          Rock
## 27      Scissors
## 28          Rock
## 29         Paper
## 30          Rock
## 31      Scissors
## 32          Rock
## 33  Lizard Spock
## 34      Scissors
## 35          Rock
## 36          Rock
## 37  Lizard Spock
## 38  Lizard Spock
## 39  Lizard Spock
## 40  Lizard Spock
## 41  Lizard Spock
## 42  Lizard Spock
## 43         Paper
## 44  Lizard Spock
## 45  Lizard Spock
## 46          Rock
## 47      Scissors
## 48      Scissors
## 49      Scissors
## 50  Lizard Spock
## 51          Rock
## 52  Lizard Spock
## 53         Paper
## 54         Paper
## 55      Scissors
## 56  Lizard Spock
## 57      Scissors
## 58  Lizard Spock
## 59         Paper
## 60  Lizard Spock
## 61      Scissors
## 62  Lizard Spock
## 63         Paper
## 64  Lizard Spock
## 65          Rock
## 66          Rock
## 67  Lizard Spock
## 68         Paper
## 69         Paper
## 70         Paper
## 71      Scissors
## 72      Scissors
## 73      Scissors
## 74         Paper
## 75      Scissors
## 76          Rock
## 77          Rock
## 78         Paper
## 79  Lizard Spock
## 80  Lizard Spock
## 81         Paper
## 82         Paper
## 83      Scissors
## 84  Lizard Spock
## 85      Scissors
## 86         Paper
## 87  Lizard Spock
## 88          Rock
## 89          Rock
## 90      Scissors
## 91      Scissors
## 92      Scissors
## 93  Lizard Spock
## 94      Scissors
## 95         Paper
## 96      Scissors
## 97          Rock
## 98          Rock
## 99      Scissors
## 100        Paper
## 101        Paper
## 102 Lizard Spock
## 103         Rock
## 104     Scissors
## 105 Lizard Spock
## 106     Scissors
## 107        Paper
## 108         Rock
## 109 Lizard Spock
## 110         Rock
## 111 Lizard Spock
## 112        Paper
## 113 Lizard Spock
## 114         Rock
## 115 Lizard Spock
## 116 Lizard Spock
## 117         Rock
## 118     Scissors
## 119 Lizard Spock
## 120         Rock
## 121     Scissors
## 122        Paper
## 123         Rock
## 124         Rock
## 125 Lizard Spock
## 126     Scissors
## 127        Paper
## 128     Scissors
## 129         Rock
## 130        Paper
## 131     Scissors
## 132 Lizard Spock
## 133         Rock
## 134         Rock
## 135        Paper
## 136        Paper
## 137         Rock
## 138     Scissors
## 139         Rock
## 140 Lizard Spock
## 141     Scissors
## 142 Lizard Spock
## 143         Rock
## 144        Paper
## 145 Lizard Spock
## 146         Rock
## 147         Rock
## 148     Scissors
## 149        Paper
## 150        Paper
## 151 Lizard Spock
## 152         Rock
## 153     Scissors
## 154     Scissors
## 155 Lizard Spock
## 156        Paper
## 157        Paper
## 158        Paper
## 159     Scissors
## 160     Scissors</code></pre>
<p>In the data set above, each line represents a single play out of 160 total.</p>
<p>When dealing with real data you’ll need to get the actual frequency counts that go into the data. There are several ways to get these counts.</p>
</div>
<div id="getting-counts-the-in-class-way-not-recommended" class="section level3">
<h3><span class="header-section-number">5.1.4</span> getting counts the in-class way (not recommended)</h3>
<p>We mentioned in class that you can use the <code>plyr::count()</code> function to get tallied data. One of the frustrating things about <code>R</code> is that with so many packages being made, many authors us the same names for their functions. In the case of <code>count()</code> note that the following give you different results:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">count</span>(prslOutcomes)</code></pre></div>
<pre><code>##       Outcomes freq
## 1 Lizard Spock   45
## 2        Paper   35
## 3         Rock   41
## 4     Scissors   39</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dplyr<span class="op">::</span><span class="kw">count</span>(prslOutcomes)</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1   160</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plyr<span class="op">::</span><span class="kw">count</span>(prslOutcomes)</code></pre></div>
<pre><code>##       Outcomes freq
## 1 Lizard Spock   45
## 2        Paper   35
## 3         Rock   41
## 4     Scissors   39</code></pre>
<p>Only <code>plyr::count()</code> gives us the counts per category. Let’s save this to an object called <code>counts</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">counts &lt;-<span class="st"> </span>plyr<span class="op">::</span><span class="kw">count</span>(prslOutcomes)
<span class="kw">show</span>(counts)</code></pre></div>
<pre><code>##       Outcomes freq
## 1 Lizard Spock   45
## 2        Paper   35
## 3         Rock   41
## 4     Scissors   39</code></pre>
<p>We can simply grab the frequency data from the <code>freq</code> column that <code>plyr::count()</code> has created:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chisq.test</span>(<span class="dt">x =</span> counts<span class="op">$</span>freq)</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  counts$freq
## X-squared = 1.3, df = 3, p-value = 0.7291</code></pre>
</div>
<div id="getting-counts-the-table-way-my-new-recommendation" class="section level3">
<h3><span class="header-section-number">5.1.5</span> getting counts the <code>table()</code> way (my new recommendation)</h3>
<p>An alternative to the above would be to create a table from your raw data. Given something I just discovered after class yesterday, I think this may be the better way, if for nothing other than being consistent. In this case we create a table from the data frame of raw data using the <code>table()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(prslOutcomes)</code></pre></div>
<pre><code>## prslOutcomes
## Lizard Spock        Paper         Rock     Scissors 
##           45           35           41           39</code></pre>
<p>You can simply plug this table into the <code>chisq.test()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chisq.test</span>(<span class="dt">x =</span> <span class="kw">table</span>(prslOutcomes))</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  table(prslOutcomes)
## X-squared = 1.3, df = 3, p-value = 0.7291</code></pre>
<p>And if we had prior knowledge that people tend to choose Lizard Spock 50% of the time, Rock 30%, and the remaining two 10% each? would you modify the previous call?</p>
</div>
</div>
<div id="contingency-table-analysis-in-r" class="section level2">
<h2><span class="header-section-number">5.2</span> Contingency Table Analysis in R</h2>
We use contingency tables to assess the relative independence of 2 categorical variables. Consider the example taken from the Howell text, Table 6.4:
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Yes
</th>
<th style="text-align:right;">
No
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Nonwhite
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
251
</td>
<td style="text-align:right;">
284
</td>
</tr>
<tr>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
508
</td>
<td style="text-align:right;">
541
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
759
</td>
<td style="text-align:right;">
825
</td>
</tr>
</tbody>
</table>
<p>The above table assesses whether the frequency of being handed the death penalty (Yes or No) is contingent on race (White or Non-White). In class I walked you through several ways of running the <span class="math inline">\(\chi^2\)</span> of independence test assuming you are given a table that has both observeds and marginal totals or just observeds. Ultimately this was done to show you how to calculate your expecteds in either scenario and perform the requisite steps flowing from there.</p>
<p><strong>BUT BUMP ALL DAT… THAT’S RIGHT I SAID BUMP IT!</strong></p>
<p>One of the cool things about <code>R</code> (for me at least) is discovering more efficient ways of doing things, and after class I got the thinking “there’s got to be a simpler way of dealing with Contingency Tables than I’m used to”. And in fact there is.</p>
<p>Ladies and Gents, I give you the <code>gmodels</code> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pacman<span class="op">::</span><span class="kw">p_load</span>(gmodels)</code></pre></div>
<p>Assuming we have the above table, we can use the <code>gmodels:CrossTable()</code> function. But first we need to recreate the table including <strong>only our observed values</strong> and save it to an object; here I’m saving it to <code>table6.4_observed</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table6.4_observed &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">33</span>, <span class="dv">251</span>, <span class="dv">33</span>, <span class="dv">508</span>), <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">byrow =</span> T)
<span class="kw">colnames</span>(table6.4_observed) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>)
<span class="kw">rownames</span>(table6.4_observed) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Nonwhite&quot;</span>, <span class="st">&quot;White&quot;</span>)
<span class="kw">show</span>(table6.4_observed)</code></pre></div>
<pre><code>##          Yes  No
## Nonwhite  33 251
## White     33 508</code></pre>
<p>From here we just throw this table into <code>gmodels::CrossTable</code>. Run <code>?gmodels::CrossTable</code> to get a feel for what arguments this function takes and what other things it can do. For now, I’m especially concerned with:</p>
<blockquote>
<p>expected: If TRUE, chisq will be set to TRUE and expected cell counts from the Chi-Square will be included</p>
</blockquote>
<blockquote>
<p>chisq: If TRUE, the results of a chi-square test will be included</p>
</blockquote>
<p>So if we run this with the argument <code>expected=TRUE</code> then it calculates and displays our expecteds AND runs the <span class="math inline">\(\chi^2\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmodels<span class="op">::</span><span class="kw">CrossTable</span>(table6.4_observed, <span class="dt">expected =</span> T)</code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |              Expected N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  825 
## 
##  
##              |  
##              |       Yes |        No | Row Total | 
## -------------|-----------|-----------|-----------|
##     Nonwhite |        33 |       251 |       284 | 
##              |    22.720 |   261.280 |           | 
##              |     4.651 |     0.404 |           | 
##              |     0.116 |     0.884 |     0.344 | 
##              |     0.500 |     0.331 |           | 
##              |     0.040 |     0.304 |           | 
## -------------|-----------|-----------|-----------|
##        White |        33 |       508 |       541 | 
##              |    43.280 |   497.720 |           | 
##              |     2.442 |     0.212 |           | 
##              |     0.061 |     0.939 |     0.656 | 
##              |     0.500 |     0.669 |           | 
##              |     0.040 |     0.616 |           | 
## -------------|-----------|-----------|-----------|
## Column Total |        66 |       759 |       825 | 
##              |     0.080 |     0.920 |           | 
## -------------|-----------|-----------|-----------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  7.709865     d.f. =  1     p =  0.005491987 
## 
## Pearson&#39;s Chi-squared test with Yates&#39; continuity correction 
## ------------------------------------------------------------
## Chi^2 =  6.978117     d.f. =  1     p =  0.008251239 
## 
## </code></pre>
<p>Voila!! The key at the top of the output gives you the info that’s in each line of each cell, where:</p>
<ul>
<li>line 1 is observed N</li>
<li>line 2 is expected N (it calculates them for you!!)</li>
<li>line 3 is the <span class="math inline">\(\chi^2\)</span> contribution of that cell (remember the sum of the cells gives you <span class="math inline">\(\chi^2\)</span>)</li>
<li>line 4 is the proportion of that cell to the row total</li>
<li>line 5 is the proportion of that cell to the column total</li>
<li>line 6 is the proportion of that cell to the grand total</li>
</ul>
<p>and then BAM!!! The end of the output gives you your <span class="math inline">\(\chi^2\)</span> test both with and without the Yates correction.</p>
<div id="okay-but-what-about-with-real-data" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Okay, but what about with REAL DATA:</h3>
<p>OK. Let’s take a look at our old professor income data. In this case, instead of actual income values, let’s just take a look at Men v. Women faculty and make a judgment on whether or not they make greater than 50K per year.</p>
<p>A raw data set may be found at the address below:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">FacultyIncome_chi &lt;-<span class="st"> </span><span class="kw">read.delim</span>(<span class="st">&quot;https://raw.githubusercontent.com/tehrandavis/statsData/master/FacultyIncome_chi.txt&quot;</span>)</code></pre></div>
<p>As in the REAL DATA example above, we can simply use the <code>table()</code> function as we did above to get tallies from this data frame:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(FacultyIncome_chi)</code></pre></div>
<pre><code>##        greater50
## Gender   No Yes
##   Man   808 692
##   Woman 774 726</code></pre>
<p>and throw this table into the <code>gmodels::CrossTable</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmodels<span class="op">::</span><span class="kw">CrossTable</span>(<span class="kw">table</span>(FacultyIncome_chi), <span class="dt">expected =</span> T)</code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |              Expected N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  3000 
## 
##  
##              | greater50 
##       Gender |        No |       Yes | Row Total | 
## -------------|-----------|-----------|-----------|
##          Man |       808 |       692 |      1500 | 
##              |   791.000 |   709.000 |           | 
##              |     0.365 |     0.408 |           | 
##              |     0.539 |     0.461 |     0.500 | 
##              |     0.511 |     0.488 |           | 
##              |     0.269 |     0.231 |           | 
## -------------|-----------|-----------|-----------|
##        Woman |       774 |       726 |      1500 | 
##              |   791.000 |   709.000 |           | 
##              |     0.365 |     0.408 |           | 
##              |     0.516 |     0.484 |     0.500 | 
##              |     0.489 |     0.512 |           | 
##              |     0.258 |     0.242 |           | 
## -------------|-----------|-----------|-----------|
## Column Total |      1582 |      1418 |      3000 | 
##              |     0.527 |     0.473 |           | 
## -------------|-----------|-----------|-----------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  1.545953     d.f. =  1     p =  0.2137338 
## 
## Pearson&#39;s Chi-squared test with Yates&#39; continuity correction 
## ------------------------------------------------------------
## Chi^2 =  1.456352     d.f. =  1     p =  0.2275114 
## 
## </code></pre>
<p>And we’re done. No need to get <code>count()</code> or use the <code>xtabs()</code> function or specify a formula. Life is good!</p>
</div>
</div>
<div id="effect-sizes-and-odds-ratios" class="section level2">
<h2><span class="header-section-number">5.3</span> Effect Sizes and Odds Ratios</h2>
<p>Extending this to Table 6.5 from the Howell text, assessing the relationship between childhood sexual abuse (0 incidents, 1,2,3) and abuse as adult (yes,no):</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
No
</th>
<th style="text-align:right;">
Yes
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0
</td>
<td style="text-align:right;">
512
</td>
<td style="text-align:right;">
54
</td>
</tr>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
227
</td>
<td style="text-align:right;">
37
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
3+
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
12
</td>
</tr>
</tbody>
</table>
<p>And now a Chi-square:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table6.<span class="dv">5</span> &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">512</span>, <span class="dv">54</span>, <span class="dv">227</span>, <span class="dv">37</span>, <span class="dv">59</span>, <span class="dv">15</span>, <span class="dv">18</span>, <span class="dv">12</span>), <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">byrow =</span> T)
<span class="kw">rownames</span>(table6.<span class="dv">5</span>) =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;0&quot;</span>, <span class="st">&quot;1&quot;</span>, <span class="st">&quot;2&quot;</span>, <span class="st">&quot;3+&quot;</span>)
<span class="kw">colnames</span>(table6.<span class="dv">5</span>) =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)

<span class="kw">show</span>(table6.<span class="dv">5</span>)</code></pre></div>
<pre><code>##     No Yes
## 0  512  54
## 1  227  37
## 2   59  15
## 3+  18  12</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmodels<span class="op">::</span><span class="kw">CrossTable</span>(table6.<span class="dv">5</span>, <span class="dt">expected =</span> T)</code></pre></div>
<pre><code>## Warning in chisq.test(t, correct = FALSE, ...): Chi-squared approximation
## may be incorrect</code></pre>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |              Expected N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  934 
## 
##  
##              |  
##              |        No |       Yes | Row Total | 
## -------------|-----------|-----------|-----------|
##            0 |       512 |        54 |       566 | 
##              |   494.493 |    71.507 |           | 
##              |     0.620 |     4.286 |           | 
##              |     0.905 |     0.095 |     0.606 | 
##              |     0.627 |     0.458 |           | 
##              |     0.548 |     0.058 |           | 
## -------------|-----------|-----------|-----------|
##            1 |       227 |        37 |       264 | 
##              |   230.647 |    33.353 |           | 
##              |     0.058 |     0.399 |           | 
##              |     0.860 |     0.140 |     0.283 | 
##              |     0.278 |     0.314 |           | 
##              |     0.243 |     0.040 |           | 
## -------------|-----------|-----------|-----------|
##            2 |        59 |        15 |        74 | 
##              |    64.651 |     9.349 |           | 
##              |     0.494 |     3.416 |           | 
##              |     0.797 |     0.203 |     0.079 | 
##              |     0.072 |     0.127 |           | 
##              |     0.063 |     0.016 |           | 
## -------------|-----------|-----------|-----------|
##           3+ |        18 |        12 |        30 | 
##              |    26.210 |     3.790 |           | 
##              |     2.572 |    17.783 |           | 
##              |     0.600 |     0.400 |     0.032 | 
##              |     0.022 |     0.102 |           | 
##              |     0.019 |     0.013 |           | 
## -------------|-----------|-----------|-----------|
## Column Total |       816 |       118 |       934 | 
##              |     0.874 |     0.126 |           | 
## -------------|-----------|-----------|-----------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  29.62726     d.f. =  3     p =  1.653054e-06 
## 
## 
## </code></pre>
<p>As I mentioned in class, we are not only interested in independence in itself, but also the the relationship between the frequency of our observed outcomes. This allow us to further interpret our data.</p>
<p>For example we might be interested in not only whether instances of sexual abuse as a child affect the likelihood of experiencing abuse as an adult, but also how much more likely one is to be abused as an adult with increased childhood incidence.</p>
<p>For this we can use odds ratios, which essentially act as a measure of effect size, or magnitude of the effect, for frequency data. Odd ratios may be calculated as by establishing a ratio of the binomial outcomes (in this case Yes v No) for each group (Incidence: 0,1,2,3+).</p>
<p>To do this “by hand” you can simply take the appropriate columns and perform division to get the odds for each group. In this case you can just divide the values in column 2 of <code>table6.5</code> by column 1 (because I’m interested in the relationship of number of incidents, Yes column). In themselves, the odds tell us the likelihood of occurrence:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">odds &lt;-<span class="st"> </span>table6.<span class="dv">5</span>[, <span class="dv">2</span>]<span class="op">/</span>table6.<span class="dv">5</span>[, <span class="dv">1</span>]
<span class="kw">show</span>(odds)</code></pre></div>
<pre><code>##         0         1         2        3+ 
## 0.1054688 0.1629956 0.2542373 0.6666667</code></pre>
<p>We then calculate each odds ratio by dividing each of the odds by a “control”. In this case the first group, 0 incidents is the logical control.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">odds_ratios &lt;-<span class="st"> </span>odds<span class="op">/</span>odds[<span class="dv">1</span>]
<span class="kw">show</span>(odds_ratios)</code></pre></div>
<pre><code>##        0        1        2       3+ 
## 1.000000 1.545440 2.410546 6.320988</code></pre>
<p>One important bit. Since we are dividing all odds by our control group, the odds ratio for the control will always be 1. Another way to think of this is that the odds ratio for our null condition will always be 1. <strong>Deviations away from 1 are deviations away from the null hypothesis.</strong> This makes since… if incidence did not have an effect we would expect the odds of adult abuse to be the same for all groups.</p>
<p>Rather than doing this by hand, however, you can simply use <code>epitools::oddsratio()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">epitools<span class="op">::</span><span class="kw">oddsratio</span>(table6.<span class="dv">5</span>)</code></pre></div>
<pre><code>## Warning in chisq.test(xx, correct = correction): Chi-squared approximation
## may be incorrect</code></pre>
<pre><code>## $data
##        No Yes Total
## 0     512  54   566
## 1     227  37   264
## 2      59  15    74
## 3+     18  12    30
## Total 816 118   934
## 
## $measure
##                         NA
## odds ratio with 95% C.I. estimate     lower     upper
##                       0  1.000000        NA        NA
##                       1  1.546412 0.9822983  2.411754
##                       2  2.420734 1.2459127  4.478786
##                       3+ 6.309182 2.8025291 13.779335
## 
## $p.value
##          NA
## two-sided   midp.exact fisher.exact   chi.square
##        0            NA           NA           NA
##        1  5.956497e-02 5.726661e-02 5.466205e-02
##        2  1.025698e-02 8.883009e-03 5.130875e-03
##        3+ 2.566199e-05 2.246154e-05 2.208505e-07
## 
## $correction
## [1] FALSE
## 
## attr(,&quot;method&quot;)
## [1] &quot;median-unbiased estimate &amp; mid-p exact CI&quot;</code></pre>
<p>Note that by default <code>epitools::oddsratio()</code> assumes that your table is constructed with your rows as groups and your columns as outcomes (YorN, Success or Fail, etc.). It also assumes that your first row is your control, and the second column is your column of interest. It this is not the case you need to reformat your table to fit.</p>
</div>
<div id="fishers-exact-test" class="section level2">
<h2><span class="header-section-number">5.4</span> Fisher’s exact test</h2>
<p>Fisher’s exact test is a statistical significance test used in the analysis of 2×2 contingency tables. Although in practice it is employed when sample sizes are small (expected &lt; 5), it is valid for all sample sizes.</p>
<p>It involves: 1. determining all possible tables that could be formed using same marginal totals observed and 2. calculating the probability of the observed data from whether it falls in the extreme region of all possible tables (i.e., &lt; .05 probability).</p>
<p>The <code>gmodels::CrossTable()</code> function is nice as it will also run a Fisher’s exact test for you as well. Returning to our examples from the previous section, Table 6.4 from the text:</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Yes
</th>
<th style="text-align:right;">
No
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Nonwhite
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
251
</td>
</tr>
<tr>
<td style="text-align:left;">
White
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
508
</td>
</tr>
</tbody>
</table>
<p>Remember we only need our observed data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table6.4_observed &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">33</span>, <span class="dv">251</span>, <span class="dv">33</span>, <span class="dv">508</span>), <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">byrow =</span> T)
<span class="kw">colnames</span>(table6.4_observed) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>)
<span class="kw">rownames</span>(table6.4_observed) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Nonwhite&quot;</span>, <span class="st">&quot;White&quot;</span>)
<span class="kw">show</span>(table6.4_observed)</code></pre></div>
<pre><code>##          Yes  No
## Nonwhite  33 251
## White     33 508</code></pre>
<p>And now to run the Fischer test by adding an additional argument to <code>gmodels::CrossTable()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmodels<span class="op">::</span><span class="kw">CrossTable</span>(table6.4_observed, <span class="dt">fisher =</span> T)</code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  825 
## 
##  
##              |  
##              |       Yes |        No | Row Total | 
## -------------|-----------|-----------|-----------|
##     Nonwhite |        33 |       251 |       284 | 
##              |     4.651 |     0.404 |           | 
##              |     0.116 |     0.884 |     0.344 | 
##              |     0.500 |     0.331 |           | 
##              |     0.040 |     0.304 |           | 
## -------------|-----------|-----------|-----------|
##        White |        33 |       508 |       541 | 
##              |     2.442 |     0.212 |           | 
##              |     0.061 |     0.939 |     0.656 | 
##              |     0.500 |     0.669 |           | 
##              |     0.040 |     0.616 |           | 
## -------------|-----------|-----------|-----------|
## Column Total |        66 |       759 |       825 | 
##              |     0.080 |     0.920 |           | 
## -------------|-----------|-----------|-----------|
## 
##  
## Fisher&#39;s Exact Test for Count Data
## ------------------------------------------------------------
## Sample estimate odds ratio:  2.022094 
## 
## Alternative hypothesis: true odds ratio is not equal to 1
## p =  0.00680891 
## 95% confidence interval:  1.179576 3.467215 
## 
## Alternative hypothesis: true odds ratio is less than 1
## p =  0.9978205 
## 95% confidence interval:  0 3.194368 
## 
## Alternative hypothesis: true odds ratio is greater than 1
## p =  0.004780401 
## 95% confidence interval:  1.280213 Inf 
## 
## 
## </code></pre>
<p>Note that this provides a general Fischer test, as well as directional tests (greater than, less than). How might we interpret this output?</p>
<p>The test uses the odds ratio obtained from the 2×2 data, in this case 2.02, and compares it to the ratio that would be obtained assuming independence, which is always 1 (see previous section on Odds Ratios. You may also notice the 95% confidence intervals. If the interval for any of the tests contains 1 then it must be that <span class="math inline">\(p&gt;.05\)</span>.</p>
</div>
<div id="cohens-kappa" class="section level2">
<h2><span class="header-section-number">5.5</span> Cohen’s kappa</h2>
<p>Cohen’s kappa is a measure of inter-judge agreement and used when we want to assess the reliability of judges or raters, or inter-rater reliability. For example.</p>
<p>Two judges interview 30 adolescents and rate them as exhibiting (1) no behavior problems, (2) internalizing behaviors, (3) externalizing behaviors:</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
NoProblem
</th>
<th style="text-align:right;">
Internalizing
</th>
<th style="text-align:right;">
Externalizing
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
NoProblem
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
Internalizing
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
Externalizing
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
30
</td>
</tr>
</tbody>
</table>
<p>The frequency of Judge 1’s reports move down columns, Judge 2’s reports move across rows. What is being conveyed on this table are the intersection of those reports. For example moving across the top row: there were 15 adolescents that both judges agreed had “No Problem”“; there were 2 that Judge 1 viewed as”Internalizing&quot; and Judge 2 viewed as “No Problem”; there were 3 that Judge 1 viewed as “Externalizing” and Judge 2 said “No Problem”, etc.</p>
<p>In class we mentioned that we can get a measure of agreement based upon the observed agreements (along the diagonal in this table) and their expecteds (the amount of agreement we might expect purely due to chance). Based upon that, when can calculate from by hand:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">N &lt;-<span class="st"> </span><span class="dv">30</span>

KappaAgree &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">15</span>, <span class="dv">3</span>, <span class="dv">3</span>)
kappaExpec &lt;-<span class="st"> </span><span class="kw">c</span>((<span class="dv">16</span> <span class="op">*</span><span class="st"> </span><span class="dv">20</span>)<span class="op">/</span><span class="dv">30</span>, (<span class="dv">6</span> <span class="op">*</span><span class="st"> </span><span class="dv">6</span>)<span class="op">/</span><span class="dv">30</span>, (<span class="dv">8</span> <span class="op">*</span><span class="st"> </span><span class="dv">4</span>)<span class="op">/</span><span class="dv">30</span>)

kappa &lt;-<span class="st"> </span>(<span class="kw">sum</span>(KappaAgree) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(kappaExpec))<span class="op">/</span>(N <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(kappaExpec))

<span class="kw">show</span>(kappa)</code></pre></div>
<pre><code>## [1] 0.4726562</code></pre>
<p>Alternatively assuming we have saved this table as an object in <code>R</code> we can use the <code>Kappa</code> function from the <code>vcd</code> package:</p>
<p>Constructing the table, note that I’m using piping to build my table in a single line (vector ➔ matrix ➔ table): Also note that I an using the table structure describe above (Rater 1 along columns, Rater down rows)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">kappaExample_table &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">15</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">3</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">matrix</span>(., <span class="dt">ncol =</span> <span class="dv">3</span>, <span class="dt">byrow =</span> T)
<span class="kw">rownames</span>(kappaExample_table) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;NoProblem&quot;</span>, <span class="st">&quot;Internalizing&quot;</span>, <span class="st">&quot;Externalizing&quot;</span>)
<span class="kw">colnames</span>(kappaExample_table) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;NoProblem&quot;</span>, <span class="st">&quot;Internalizing&quot;</span>, <span class="st">&quot;Externalizing&quot;</span>)

<span class="kw">show</span>(kappaExample_table)</code></pre></div>
<pre><code>##               NoProblem Internalizing Externalizing
## NoProblem            15             2             3
## Internalizing         1             3             2
## Externalizing         0             1             3</code></pre>
<p>And now Cohen’s Kappa:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vcd<span class="op">::</span><span class="kw">Kappa</span>(kappaExample_table)</code></pre></div>
<pre><code>##             value    ASE     z  Pr(&gt;|z|)
## Unweighted 0.4727 0.1304 3.624 0.0002898
## Weighted   0.5109 0.1322 3.863 0.0001119</code></pre>
<p>Note that <code>psych</code> also has a <code>cohen.kappa()</code> function, but the data needs to be structured differently.</p>
<p>That’s it for now. Be sure to check back later. ```</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probability-and-the-binomial-distribution.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="correlation-and-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["Vignettes.pdf", "Vignettes.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
