<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>musings of the Professor</title>
  <meta name="description" content="Weekly examples and musings related to PSYC 7014.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="musings of the Professor" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Weekly examples and musings related to PSYC 7014." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="musings of the Professor" />
  
  <meta name="twitter:description" content="Weekly examples and musings related to PSYC 7014." />
  

<meta name="author" content="Tehran J. Davis">


<meta name="date" content="2018-12-15">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="chi-square-and-associated-methods.html">
<link rel="next" href="testing-differences-in-means-t-test.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Words from the Professor</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Weekly musings</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html"><i class="fa fa-check"></i><b>1</b> Introduction to R / getting to know your data</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-and-loading-an-r-package"><i class="fa fa-check"></i><b>1.1</b> Installing and loading an R package:</a><ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-a-package-using-the-gui"><i class="fa fa-check"></i><b>1.1.1</b> Installing a package using the GUI</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-packages-with-install.packages"><i class="fa fa-check"></i><b>1.1.2</b> Installing packages with <code>install.packages()</code></a></li>
<li class="chapter" data-level="1.1.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#an-important-note-on-knitting-with-install.packages"><i class="fa fa-check"></i><b>1.1.3</b> An IMPORTANT note on knitting with install.packages:</a></li>
<li class="chapter" data-level="1.1.4" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-packages-with-library"><i class="fa fa-check"></i><b>1.1.4</b> Loading packages with <code>library()</code></a></li>
<li class="chapter" data-level="1.1.5" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-packages-with-require"><i class="fa fa-check"></i><b>1.1.5</b> Loading packages with <code>require()</code></a></li>
<li class="chapter" data-level="1.1.6" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#installing-and-loading-packages-like-a-ninja"><i class="fa fa-check"></i><b>1.1.6</b> Installing and loading packages like a ninja</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-in-data"><i class="fa fa-check"></i><b>1.2</b> Loading in data</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#loading-in-local-data-using-a-gui"><i class="fa fa-check"></i><b>1.2.1</b> Loading in local data using a GUI:</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#importing-data-from-the-web"><i class="fa fa-check"></i><b>1.2.2</b> importing data from the web</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#downloading-data"><i class="fa fa-check"></i><b>1.2.3</b> Downloading data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r-getting-to-know-your-data.html"><a href="introduction-to-r-getting-to-know-your-data.html#looking-ahead"><i class="fa fa-check"></i><b>1.3</b> Looking ahead…</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html"><i class="fa fa-check"></i><b>2</b> Measures of distribution, central tendency, PLOTS… oh my!</a><ul>
<li class="chapter" data-level="2.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#getting-measures-of-central-tendency"><i class="fa fa-check"></i><b>2.1</b> Getting measures of central tendency</a></li>
<li class="chapter" data-level="2.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-the-distribution-with-a-histogram"><i class="fa fa-check"></i><b>2.2</b> Plotting the distribution with a histogram</a><ul>
<li class="chapter" data-level="2.2.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#using-hist"><i class="fa fa-check"></i><b>2.2.1</b> Using <code>hist()</code></a></li>
<li class="chapter" data-level="2.2.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-a-histogram-with-ggplot"><i class="fa fa-check"></i><b>2.2.2</b> Plotting a histogram with <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#plotting-your-data-in-a-boxplot"><i class="fa fa-check"></i><b>2.3</b> Plotting your data in a boxplot:</a><ul>
<li class="chapter" data-level="2.3.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#turning-numeric-data-into-categorical"><i class="fa fa-check"></i><b>2.3.1</b> turning numeric data into categorical</a></li>
<li class="chapter" data-level="2.3.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#boxplotting-using-ggplot"><i class="fa fa-check"></i><b>2.3.2</b> boxplotting using <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#assessing-the-data-for-normality"><i class="fa fa-check"></i><b>2.4</b> Assessing the data for normality</a><ul>
<li class="chapter" data-level="2.4.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#q-q-plots"><i class="fa fa-check"></i><b>2.4.1</b> Q-Q Plots</a></li>
<li class="chapter" data-level="2.4.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#generating-a-theoretical-normal-distribution."><i class="fa fa-check"></i><b>2.4.2</b> Generating a theoretical normal distribution.</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#subsetting-your-data"><i class="fa fa-check"></i><b>2.5</b> Subsetting your data</a></li>
<li class="chapter" data-level="2.6" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#looking-ahead-means-and-better-models"><i class="fa fa-check"></i><b>2.6</b> Looking ahead: Means and better models</a><ul>
<li class="chapter" data-level="2.6.1" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-highest-probability"><i class="fa fa-check"></i><b>2.6.1</b> mean as highest probability:</a></li>
<li class="chapter" data-level="2.6.2" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-fulcrum-point"><i class="fa fa-check"></i><b>2.6.2</b> mean as fulcrum point</a></li>
<li class="chapter" data-level="2.6.3" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#mean-as-minimizing-random-error"><i class="fa fa-check"></i><b>2.6.3</b> mean as minimizing random error</a></li>
<li class="chapter" data-level="2.6.4" data-path="measures-of-distribution-central-tendency-plots-oh-my.html"><a href="measures-of-distribution-central-tendency-plots-oh-my.html#but-we-can-do-better-than-that"><i class="fa fa-check"></i><b>2.6.4</b> but we can do better than that</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html"><i class="fa fa-check"></i><b>3</b> Sampling distributions and building the logic of NHST</a><ul>
<li class="chapter" data-level="3.1" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-sampling-distribution"><i class="fa fa-check"></i><b>3.1</b> The sampling distribution</a></li>
<li class="chapter" data-level="3.2" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>3.2</b> Standard error of the mean</a></li>
<li class="chapter" data-level="3.3" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-difference-distribution"><i class="fa fa-check"></i><b>3.3</b> The difference distribution</a></li>
<li class="chapter" data-level="3.4" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#the-null-distribution"><i class="fa fa-check"></i><b>3.4</b> The Null distribution</a></li>
<li class="chapter" data-level="3.5" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#probabilty-of-observed-differences"><i class="fa fa-check"></i><b>3.5</b> Probabilty of observed differences</a></li>
<li class="chapter" data-level="3.6" data-path="sampling-distributions-and-building-the-logic-of-nhst.html"><a href="sampling-distributions-and-building-the-logic-of-nhst.html#a-note-about-sample-size"><i class="fa fa-check"></i><b>3.6</b> A note about sample size</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html"><i class="fa fa-check"></i><b>4</b> Probability and the Binomial Distribution</a><ul>
<li class="chapter" data-level="4.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#a-few-words-on-where-we-are-at-so-far"><i class="fa fa-check"></i><b>4.1</b> A few words on where we are at so far…</a></li>
<li class="chapter" data-level="4.2" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#okay-on-to-this-weeks-example-analyses"><i class="fa fa-check"></i><b>4.2</b> Okay on to this week’s example analyses:</a></li>
<li class="chapter" data-level="4.3" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#classic-example-the-coin-flip"><i class="fa fa-check"></i><b>4.3</b> Classic example: The coin flip</a><ul>
<li class="chapter" data-level="4.3.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#how-many-heads-would-we-get-if-we-flipped-a-fair-coin-10-times"><i class="fa fa-check"></i><b>4.3.1</b> How many heads would we get if we flipped a fair coin 10 times?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#changing-the-parameters"><i class="fa fa-check"></i><b>4.4</b> Changing the parameters</a><ul>
<li class="chapter" data-level="4.4.1" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#constructing-a-table-of-outcome-probabilities"><i class="fa fa-check"></i><b>4.4.1</b> Constructing a table of outcome probabilities:</a></li>
<li class="chapter" data-level="4.4.2" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#assessing-cummulative-probability"><i class="fa fa-check"></i><b>4.4.2</b> Assessing cummulative probability</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#catching-a-cheat"><i class="fa fa-check"></i><b>4.5</b> Catching a cheat</a></li>
<li class="chapter" data-level="4.6" data-path="probability-and-the-binomial-distribution.html"><a href="probability-and-the-binomial-distribution.html#one-last-thing-permutations-combinations-and-building-functions"><i class="fa fa-check"></i><b>4.6</b> One last thing… Permutations, combinations, and building functions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html"><i class="fa fa-check"></i><b>5</b> Chi-square and associated methods</a><ul>
<li class="chapter" data-level="5.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#goodness-of-fit-test"><i class="fa fa-check"></i><b>5.1</b> Goodness of fit test</a><ul>
<li class="chapter" data-level="5.1.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#what-to-do-if-you-are-given-a-table-with-tallies"><i class="fa fa-check"></i><b>5.1.1</b> What to do if you are given a table with tallies</a></li>
<li class="chapter" data-level="5.1.2" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#assuming-all-things-are-not-equal"><i class="fa fa-check"></i><b>5.1.2</b> Assuming all things are NOT equal</a></li>
<li class="chapter" data-level="5.1.3" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#real-data-is-likely-not-pre-tallied"><i class="fa fa-check"></i><b>5.1.3</b> Real data is likely NOT pre-tallied</a></li>
<li class="chapter" data-level="5.1.4" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#getting-counts-the-in-class-way-not-recommended"><i class="fa fa-check"></i><b>5.1.4</b> getting counts the in-class way (not recommended)</a></li>
<li class="chapter" data-level="5.1.5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#getting-counts-the-table-way-my-new-recommendation"><i class="fa fa-check"></i><b>5.1.5</b> getting counts the <code>table()</code> way (my new recommendation)</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#contingency-table-analysis-in-r"><i class="fa fa-check"></i><b>5.2</b> Contingency Table Analysis in R</a><ul>
<li class="chapter" data-level="5.2.1" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#okay-but-what-about-with-real-data"><i class="fa fa-check"></i><b>5.2.1</b> Okay, but what about with REAL DATA:</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#effect-sizes-and-odds-ratios"><i class="fa fa-check"></i><b>5.3</b> Effect Sizes and Odds Ratios</a></li>
<li class="chapter" data-level="5.4" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#fishers-exact-test"><i class="fa fa-check"></i><b>5.4</b> Fisher’s exact test</a></li>
<li class="chapter" data-level="5.5" data-path="chi-square-and-associated-methods.html"><a href="chi-square-and-associated-methods.html#cohens-kappa"><i class="fa fa-check"></i><b>5.5</b> Cohen’s kappa</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html"><i class="fa fa-check"></i><b>6</b> Correlation and Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#the-relationship-btw-stress-and-health"><i class="fa fa-check"></i><b>6.1</b> The Relationship b/tw Stress and Health</a><ul>
<li class="chapter" data-level="6.1.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#testing-our-assumptions"><i class="fa fa-check"></i><b>6.1.1</b> Testing our assumptions</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#plotting-the-data"><i class="fa fa-check"></i><b>6.2</b> Plotting the data</a></li>
<li class="chapter" data-level="6.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#covariance-and-correlation"><i class="fa fa-check"></i><b>6.3</b> Covariance and Correlation</a><ul>
<li class="chapter" data-level="6.3.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#covariance"><i class="fa fa-check"></i><b>6.3.1</b> Covariance</a></li>
<li class="chapter" data-level="6.3.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#correlation"><i class="fa fa-check"></i><b>6.3.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#sigfnificance-testing-r"><i class="fa fa-check"></i><b>6.4</b> Sigfnificance testing <span class="math inline">\(r\)</span></a></li>
<li class="chapter" data-level="6.5" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#fitting-the-data-to-a-model"><i class="fa fa-check"></i><b>6.5</b> Fitting the data to a model</a></li>
<li class="chapter" data-level="6.6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#linear-models-in-r"><i class="fa fa-check"></i><b>6.6</b> Linear models in R</a><ul>
<li class="chapter" data-level="6.6.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#attributes-of-class-lm"><i class="fa fa-check"></i><b>6.6.1</b> Attributes of class <code>lm</code>:</a></li>
<li class="chapter" data-level="6.6.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#testing-the-residuals"><i class="fa fa-check"></i><b>6.6.2</b> Testing the residuals</a></li>
<li class="chapter" data-level="6.6.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#using-your-lm-object-with-other-functions"><i class="fa fa-check"></i><b>6.6.3</b> Using your <code>lm</code> object with other functions</a></li>
<li class="chapter" data-level="6.6.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#plotting-the-regression-line"><i class="fa fa-check"></i><b>6.6.4</b> Plotting the regression line</a></li>
<li class="chapter" data-level="6.6.5" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#a-note-on-degrees-of-freedom-of-our-model"><i class="fa fa-check"></i><b>6.6.5</b> A note on degrees of freedom of our model</a></li>
<li class="chapter" data-level="6.6.6" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#interpreting-the-output"><i class="fa fa-check"></i><b>6.6.6</b> Interpreting the output</a></li>
<li class="chapter" data-level="6.6.7" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#the-coeff.-of-determination-as-index-of-explanatory-value"><i class="fa fa-check"></i><b>6.6.7</b> The coeff. of determination as index of explanatory value</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#write-up-and-presentaion"><i class="fa fa-check"></i><b>6.7</b> Write up and presentaion</a></li>
<li class="chapter" data-level="6.8" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#advanced-plotting"><i class="fa fa-check"></i><b>6.8</b> Advanced plotting</a><ul>
<li class="chapter" data-level="6.8.1" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#adding-text-to-the-plot"><i class="fa fa-check"></i><b>6.8.1</b> Adding text to the plot</a></li>
<li class="chapter" data-level="6.8.2" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#addnig-text-like-a-r-ninja"><i class="fa fa-check"></i><b>6.8.2</b> addnig text like a R-ninja:</a></li>
<li class="chapter" data-level="6.8.3" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#placing-plots-side-by-side-in-a-grid"><i class="fa fa-check"></i><b>6.8.3</b> Placing plots side-by-side in a grid</a></li>
<li class="chapter" data-level="6.8.4" data-path="correlation-and-regression.html"><a href="correlation-and-regression.html#two-series-on-the-same-damn-plot"><i class="fa fa-check"></i><b>6.8.4</b> Two series on the same damn plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html"><i class="fa fa-check"></i><b>7</b> Testing differences in means: t-test</a><ul>
<li class="chapter" data-level="7.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#things-to-consider-before-running-the-t-test"><i class="fa fa-check"></i><b>7.1</b> Things to consider before running the t-test</a><ul>
<li class="chapter" data-level="7.1.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#what-is-the-nature-of-your-sample-data"><i class="fa fa-check"></i><b>7.1.1</b> What is the nature of your sample data?</a></li>
<li class="chapter" data-level="7.1.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#what-is-the-structure-of-your-data-file"><i class="fa fa-check"></i><b>7.1.2</b> What is the structure of your data file?</a></li>
<li class="chapter" data-level="7.1.3" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#testing-assumptions"><i class="fa fa-check"></i><b>7.1.3</b> Testing assumptions</a></li>
<li class="chapter" data-level="7.1.4" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#getting-the-descriptive-stats-and-plotting-the-means."><i class="fa fa-check"></i><b>7.1.4</b> Getting the descriptive stats and plotting the means.</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#performing-the-t-test-paired-sample-t-test"><i class="fa fa-check"></i><b>7.2</b> Performing the t-test (Paired sample t-test)</a></li>
<li class="chapter" data-level="7.3" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#measuring-effect-size"><i class="fa fa-check"></i><b>7.3</b> Measuring effect size</a></li>
<li class="chapter" data-level="7.4" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#other-t-tests"><i class="fa fa-check"></i><b>7.4</b> Other <span class="math inline">\(t\)</span> tests:</a><ul>
<li class="chapter" data-level="7.4.1" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#one-sample"><i class="fa fa-check"></i><b>7.4.1</b> One sample:</a></li>
<li class="chapter" data-level="7.4.2" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#independent-samples-example"><i class="fa fa-check"></i><b>7.4.2</b> Independent samples example</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="testing-differences-in-means-t-test.html"><a href="testing-differences-in-means-t-test.html#independent-or-paired-sample"><i class="fa fa-check"></i><b>7.5</b> Independent or Paired Sample?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html"><i class="fa fa-check"></i><b>8</b> Analysis of Variance I: the One-way ANOVA</a><ul>
<li class="chapter" data-level="8.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#required-packages"><i class="fa fa-check"></i><b>8.1</b> Required packages</a></li>
<li class="chapter" data-level="8.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#anovas-for-comparing-means"><i class="fa fa-check"></i><b>8.2</b> ANOVAs for comparing means</a></li>
<li class="chapter" data-level="8.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#pre-processing-the-data"><i class="fa fa-check"></i><b>8.3</b> Pre-processing the data:</a><ul>
<li class="chapter" data-level="8.3.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#recoding-the-factors-if-dummy-coded"><i class="fa fa-check"></i><b>8.3.1</b> Recoding the factors (if dummy coded)</a></li>
<li class="chapter" data-level="8.3.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#renaming-column-headers"><i class="fa fa-check"></i><b>8.3.2</b> Renaming column headers</a></li>
<li class="chapter" data-level="8.3.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reordering-your-levels"><i class="fa fa-check"></i><b>8.3.3</b> Reordering your levels</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#assumptions-for-anova"><i class="fa fa-check"></i><b>8.4</b> Assumptions for ANOVA</a><ul>
<li class="chapter" data-level="8.4.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#checking-the-normality-assumption-option-1"><i class="fa fa-check"></i><b>8.4.1</b> Checking the normality assumption, OPTION 1</a></li>
<li class="chapter" data-level="8.4.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#checking-the-normality-assumption-option-2"><i class="fa fa-check"></i><b>8.4.2</b> Checking the normality assumption, OPTION 2</a></li>
<li class="chapter" data-level="8.4.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#homogeneity-of-variance"><i class="fa fa-check"></i><b>8.4.3</b> Homogeneity of Variance</a></li>
<li class="chapter" data-level="8.4.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#what-to-do-if-the-assumptions-are-violated"><i class="fa fa-check"></i><b>8.4.4</b> What to do if the assumptions are violated?</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#running-the-anova-in-r"><i class="fa fa-check"></i><b>8.5</b> Running the ANOVA in R:</a></li>
<li class="chapter" data-level="8.6" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reporting-your-data"><i class="fa fa-check"></i><b>8.6</b> Reporting your data</a><ul>
<li class="chapter" data-level="8.6.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#reporting-in-the-text"><i class="fa fa-check"></i><b>8.6.1</b> Reporting in the text</a></li>
<li class="chapter" data-level="8.6.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#what-the-omnibus-anova-tells-you"><i class="fa fa-check"></i><b>8.6.2</b> What the omnibus ANOVA tells you</a></li>
<li class="chapter" data-level="8.6.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#plots"><i class="fa fa-check"></i><b>8.6.3</b> Plots</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#digging-deeper-anova-and-regression"><i class="fa fa-check"></i><b>8.7</b> DIGGING DEEPER: ANOVA and Regression</a><ul>
<li class="chapter" data-level="8.7.1" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#regression-method-v.-means-method"><i class="fa fa-check"></i><b>8.7.1</b> Regression method v. means method</a></li>
<li class="chapter" data-level="8.7.2" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#comparing-two-models"><i class="fa fa-check"></i><b>8.7.2</b> Comparing two models</a></li>
<li class="chapter" data-level="8.7.3" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#means-method-calculations"><i class="fa fa-check"></i><b>8.7.3</b> Means method calculations</a></li>
<li class="chapter" data-level="8.7.4" data-path="analysis-of-variance-i-the-one-way-anova.html"><a href="analysis-of-variance-i-the-one-way-anova.html#bringing-it-together-its-all-about-the-residuals-baby"><i class="fa fa-check"></i><b>8.7.4</b> Bringing it together: it’s all about the residuals, baby</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><i class="fa fa-check"></i><b>9</b> Analysis of Variance II: Multiple comparisons in One-way ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#getting-started-loading-packages-and-data"><i class="fa fa-check"></i><b>9.1</b> Getting started (loading packages and data)</a></li>
<li class="chapter" data-level="9.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#running-the-one-way-anova"><i class="fa fa-check"></i><b>9.2</b> Running the One-way ANOVA</a></li>
<li class="chapter" data-level="9.3" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#post-hoc-tests"><i class="fa fa-check"></i><b>9.3</b> Post-hoc tests</a><ul>
<li class="chapter" data-level="9.3.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#bonferonni-dunn-and-holm-tests"><i class="fa fa-check"></i><b>9.3.1</b> Bonferonni-Dunn and Holm tests</a></li>
<li class="chapter" data-level="9.3.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#tukey-hsd-and-regwq-tests"><i class="fa fa-check"></i><b>9.3.2</b> Tukey HSD and REGWQ tests</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#the-logic-of-planned-contrasts"><i class="fa fa-check"></i><b>9.4</b> The logic of Planned contrasts</a></li>
<li class="chapter" data-level="9.5" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#performing-planned-contrasts-in-r"><i class="fa fa-check"></i><b>9.5</b> Performing planned contrasts in R</a><ul>
<li class="chapter" data-level="9.5.1" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#making-the-output-easier-to-read"><i class="fa fa-check"></i><b>9.5.1</b> Making the output easier to read</a></li>
<li class="chapter" data-level="9.5.2" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#calculating-your-effect-size"><i class="fa fa-check"></i><b>9.5.2</b> Calculating your effect size</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#reporting-your-results"><i class="fa fa-check"></i><b>9.6</b> Reporting your results</a></li>
<li class="chapter" data-level="9.7" data-path="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html"><a href="analysis-of-variance-ii-multiple-comparisons-in-one-way-anova.html#a-note-on-using-the-multcomp-package-v.-using-the-base-stats-method"><i class="fa fa-check"></i><b>9.7</b> A note on using the <code>multcomp</code> package v. using the base stats method</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html"><i class="fa fa-check"></i><b>10</b> Analysis of Varience III: Factorial ANOVA</a><ul>
<li class="chapter" data-level="10.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#main-effect-main-effect-and-interactions-oh-my"><i class="fa fa-check"></i><b>10.1</b> Main effect, main effect, and interactions… oh my!</a></li>
<li class="chapter" data-level="10.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#example-a-22-anova"><i class="fa fa-check"></i><b>10.2</b> Example: a 2×2 ANOVA</a></li>
<li class="chapter" data-level="10.3" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#making-sense-of-plots"><i class="fa fa-check"></i><b>10.3</b> Making sense of plots</a><ul>
<li class="chapter" data-level="10.3.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-plots"><i class="fa fa-check"></i><b>10.3.1</b> Interaction plots</a></li>
<li class="chapter" data-level="10.3.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#plotting-main-effects"><i class="fa fa-check"></i><b>10.3.2</b> Plotting main effects</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-lm-method"><i class="fa fa-check"></i><b>10.4</b> Running the ANOVA <code>lm()</code> method</a></li>
<li class="chapter" data-level="10.5" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-in-the-afexaov_ez-method"><i class="fa fa-check"></i><b>10.5</b> Running the ANOVA in the <code>afex::aov_ez()</code> method:</a></li>
<li class="chapter" data-level="10.6" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#getting-cell-means"><i class="fa fa-check"></i><b>10.6</b> Getting cell means</a></li>
<li class="chapter" data-level="10.7" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#more-examples-a-2-3-anova"><i class="fa fa-check"></i><b>10.7</b> More examples: a 2 × 3 ANOVA</a><ul>
<li class="chapter" data-level="10.7.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova"><i class="fa fa-check"></i><b>10.7.1</b> Running the ANOVA</a></li>
<li class="chapter" data-level="10.7.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#apa-plotting"><i class="fa fa-check"></i><b>10.7.2</b> APA plotting</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#anova-howell-13.1"><i class="fa fa-check"></i><b>10.8</b> 2 × 5 ANOVA (Howell 13.1)</a><ul>
<li class="chapter" data-level="10.8.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-1"><i class="fa fa-check"></i><b>10.8.1</b> Running the ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#one-last-example"><i class="fa fa-check"></i><b>10.9</b> One last example,</a><ul>
<li class="chapter" data-level="10.9.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#running-the-anova-2"><i class="fa fa-check"></i><b>10.9.1</b> Running the ANOVA</a></li>
<li class="chapter" data-level="10.9.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-plot"><i class="fa fa-check"></i><b>10.9.2</b> Interaction plot</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#interaction-v.-no-interaction"><i class="fa fa-check"></i><b>10.10</b> Interaction v. no interaction</a><ul>
<li class="chapter" data-level="10.10.1" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#no-interaction-how-about-some-posthocs"><i class="fa fa-check"></i><b>10.10.1</b> No interaction? How about some posthocs?</a></li>
<li class="chapter" data-level="10.10.2" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#what-to-do-if-you-do-have-an-interaction"><i class="fa fa-check"></i><b>10.10.2</b> what to do if you DO have an interaction</a></li>
</ul></li>
<li class="chapter" data-level="10.11" data-path="analysis-of-varience-iii-factorial-anova.html"><a href="analysis-of-varience-iii-factorial-anova.html#what-about-planned-contrasts"><i class="fa fa-check"></i><b>10.11</b> What about planned contrasts?</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html"><i class="fa fa-check"></i><b>11</b> ANOVA IV: Interactions &amp; simple Effects</a><ul>
<li class="chapter" data-level="11.1" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#the-data-set"><i class="fa fa-check"></i><b>11.1</b> the data set</a></li>
<li class="chapter" data-level="11.2" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#plotting-the-data-and-descriptive-stats"><i class="fa fa-check"></i><b>11.2</b> Plotting the data and descriptive stats</a></li>
<li class="chapter" data-level="11.3" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#the-omnibus-anova-and-assumption-tests"><i class="fa fa-check"></i><b>11.3</b> the Omnibus ANOVA (and assumption tests)</a></li>
<li class="chapter" data-level="11.4" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#running-the-simple-effects-anova-in-6-steps"><i class="fa fa-check"></i><b>11.4</b> Running the simple effects ANOVA in 6 steps:</a><ul>
<li class="chapter" data-level="11.4.1" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-1-get-the-omnibus-anova"><i class="fa fa-check"></i><b>11.4.1</b> step 1: get the omnibus ANOVA:</a></li>
<li class="chapter" data-level="11.4.2" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-2-get-the-mserror-error-df-and-error-ss-from-omnibus-anova"><i class="fa fa-check"></i><b>11.4.2</b> step 2: get the MSError, Error df, and Error SS from omnibus ANOVA</a></li>
<li class="chapter" data-level="11.4.3" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-3-subset-your-data-accordingly"><i class="fa fa-check"></i><b>11.4.3</b> step 3: subset your data accordingly</a></li>
<li class="chapter" data-level="11.4.4" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-4-run-your-one-way-simple-effects-anovas"><i class="fa fa-check"></i><b>11.4.4</b> step 4: run your One-way simple effects ANOVA(s)</a></li>
<li class="chapter" data-level="11.4.5" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-5-get-the-treatment-ms-df-ss-and-f-value-from-your-simple-anova"><i class="fa fa-check"></i><b>11.4.5</b> step 5: get the treatment MS, df, SS, and F-value from your simple ANOVA</a></li>
<li class="chapter" data-level="11.4.6" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#step-6-make-our-corrections"><i class="fa fa-check"></i><b>11.4.6</b> step 6: make our corrections</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#building-a-function-to-ninja-this-for-us"><i class="fa fa-check"></i><b>11.5</b> Building a function to ninja this for us</a></li>
<li class="chapter" data-level="11.6" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#post-hoc-tests-1"><i class="fa fa-check"></i><b>11.6</b> Post hoc tests</a></li>
<li class="chapter" data-level="11.7" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#interpreting-these-results"><i class="fa fa-check"></i><b>11.7</b> Interpreting these results:</a></li>
<li class="chapter" data-level="11.8" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#example-write-up"><i class="fa fa-check"></i><b>11.8</b> Example write-up:</a></li>
<li class="chapter" data-level="11.9" data-path="anova-iv-interactions-simple-effects.html"><a href="anova-iv-interactions-simple-effects.html#performing-this-in-spss-video"><i class="fa fa-check"></i><b>11.9</b> Performing this in SPSS (video)</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html"><i class="fa fa-check"></i><b>12</b> ANOVA V: Higher Order Factorial ANOVA</a><ul>
<li class="chapter" data-level="12.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#packages-and-data"><i class="fa fa-check"></i><b>12.1</b> Packages and data</a></li>
<li class="chapter" data-level="12.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-1-no-three-way-interaction-single-two-way-interaction"><i class="fa fa-check"></i><b>12.2</b> EXAMPLE 1: no three-way interaction, single two way interaction</a><ul>
<li class="chapter" data-level="12.2.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#first-plot-3-way-interaction-plot"><i class="fa fa-check"></i><b>12.2.1</b> First plot: 3 way interaction plot</a></li>
<li class="chapter" data-level="12.2.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-anova-3"><i class="fa fa-check"></i><b>12.2.2</b> running the ANOVA:</a></li>
<li class="chapter" data-level="12.2.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#replotting-the-2-way-interaction"><i class="fa fa-check"></i><b>12.2.3</b> Replotting the 2-way interaction</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-2-no-three-way-interaction-multiple-main-effects-multiple-2-way-interactions"><i class="fa fa-check"></i><b>12.3</b> EXAMPLE 2: No three-way interaction, multiple main effects, multiple 2 way interactions:</a><ul>
<li class="chapter" data-level="12.3.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#plotting-the-data-1"><i class="fa fa-check"></i><b>12.3.1</b> plotting the data</a></li>
<li class="chapter" data-level="12.3.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-omnibus-anova"><i class="fa fa-check"></i><b>12.3.2</b> running the omnibus ANOVA:</a></li>
<li class="chapter" data-level="12.3.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#testing-the-lecturepresentation-interaction"><i class="fa fa-check"></i><b>12.3.3</b> testing the <code>Lecture:Presentation</code> interaction:</a></li>
<li class="chapter" data-level="12.3.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#testing-the-lecturegrade-interaction"><i class="fa fa-check"></i><b>12.3.4</b> testing the <code>Lecture:Grade</code> interaction:</a></li>
<li class="chapter" data-level="12.3.5" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#simple-effect-anovas-1"><i class="fa fa-check"></i><b>12.3.5</b> simple effect ANOVAs:</a></li>
<li class="chapter" data-level="12.3.6" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#main-takeaways-write-up"><i class="fa fa-check"></i><b>12.3.6</b> Main takeaways / write-up</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#example-3-omg-multiple-two-way-interactions-and-a-nasty-three-way"><i class="fa fa-check"></i><b>12.4</b> EXAMPLE 3: OMG, multiple two way interactions and a nasty three-way!!!</a><ul>
<li class="chapter" data-level="12.4.1" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#plotting"><i class="fa fa-check"></i><b>12.4.1</b> Plotting:</a></li>
<li class="chapter" data-level="12.4.2" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#running-the-anova-4"><i class="fa fa-check"></i><b>12.4.2</b> running the ANOVA:</a></li>
<li class="chapter" data-level="12.4.3" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#fifth-graders-lecturepresentation-interaction."><i class="fa fa-check"></i><b>12.4.3</b> Fifth Graders, Lecture:Presentation interaction.</a></li>
<li class="chapter" data-level="12.4.4" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#eighth-graders-lecturepresentation-interaction."><i class="fa fa-check"></i><b>12.4.4</b> Eighth Graders, Lecture:Presentation interaction.</a></li>
<li class="chapter" data-level="12.4.5" data-path="anova-v-higher-order-factorial-anova.html"><a href="anova-v-higher-order-factorial-anova.html#constructing-a-narrative"><i class="fa fa-check"></i><b>12.4.5</b> Constructing a narrative:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html"><i class="fa fa-check"></i><b>13</b> ANOVA6: Within-Subjects</a><ul>
<li class="chapter" data-level="13.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#within-subject-v.-between-subjects"><i class="fa fa-check"></i><b>13.1</b> Within-Subject v. Between Subjects</a><ul>
<li class="chapter" data-level="13.1.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#within-v-between-anova"><i class="fa fa-check"></i><b>13.1.1</b> Within v Between ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-1"><i class="fa fa-check"></i><b>13.2</b> EXAMPLE 1</a><ul>
<li class="chapter" data-level="13.2.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data"><i class="fa fa-check"></i><b>13.2.1</b> loading in the data:</a></li>
<li class="chapter" data-level="13.2.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-2"><i class="fa fa-check"></i><b>13.2.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.2.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-a-within-anova-afex"><i class="fa fa-check"></i><b>13.2.3</b> running a within ANOVA (afex):</a></li>
<li class="chapter" data-level="13.2.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#planned-contrasts"><i class="fa fa-check"></i><b>13.2.4</b> planned contrasts</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-2"><i class="fa fa-check"></i><b>13.3</b> EXAMPLE 2</a><ul>
<li class="chapter" data-level="13.3.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data-1"><i class="fa fa-check"></i><b>13.3.1</b> loading in the data</a></li>
<li class="chapter" data-level="13.3.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-3"><i class="fa fa-check"></i><b>13.3.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.3.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-anova-5"><i class="fa fa-check"></i><b>13.3.3</b> running the ANOVA:</a></li>
<li class="chapter" data-level="13.3.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#post-hocs"><i class="fa fa-check"></i><b>13.3.4</b> post-hocs</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#example-3"><i class="fa fa-check"></i><b>13.4</b> EXAMPLE 3</a><ul>
<li class="chapter" data-level="13.4.1" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#loading-in-the-data-2"><i class="fa fa-check"></i><b>13.4.1</b> loading in the data:</a></li>
<li class="chapter" data-level="13.4.2" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#plotting-the-data-4"><i class="fa fa-check"></i><b>13.4.2</b> plotting the data</a></li>
<li class="chapter" data-level="13.4.3" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-omnibus-anova-1"><i class="fa fa-check"></i><b>13.4.3</b> running the omnibus ANOVA:</a></li>
<li class="chapter" data-level="13.4.4" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#running-the-simple-effects-anovas"><i class="fa fa-check"></i><b>13.4.4</b> running the simple effects ANOVAs</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="anova6-within-subjects.html"><a href="anova6-within-subjects.html#how-to-perform-a-within-subjects-analysis-in-spss"><i class="fa fa-check"></i><b>13.5</b> How to perform a within subjects analysis in SPSS:</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html"><i class="fa fa-check"></i><b>14</b> ANOVA VI: Mixed-effects ANOVA (BS + WS)</a><ul>
<li class="chapter" data-level="14.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#example-1-1"><i class="fa fa-check"></i><b>14.1</b> Example 1:</a><ul>
<li class="chapter" data-level="14.1.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#data-import-and-wrangling"><i class="fa fa-check"></i><b>14.1.1</b> data import and wrangling</a></li>
<li class="chapter" data-level="14.1.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#plotting-the-data-5"><i class="fa fa-check"></i><b>14.1.2</b> plotting the data</a></li>
<li class="chapter" data-level="14.1.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#running-our-anova"><i class="fa fa-check"></i><b>14.1.3</b> Running our ANOVA:</a></li>
<li class="chapter" data-level="14.1.4" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#simple-effects"><i class="fa fa-check"></i><b>14.1.4</b> simple effects</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#example-2-1"><i class="fa fa-check"></i><b>14.2</b> Example 2:</a><ul>
<li class="chapter" data-level="14.2.1" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#data-import-and-wrangling-1"><i class="fa fa-check"></i><b>14.2.1</b> data import and wrangling</a></li>
<li class="chapter" data-level="14.2.2" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#plotting-the-data-6"><i class="fa fa-check"></i><b>14.2.2</b> plotting the data</a></li>
<li class="chapter" data-level="14.2.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#run-your-omnibus-anova"><i class="fa fa-check"></i><b>14.2.3</b> Run your omnibus ANOVA:</a></li>
<li class="chapter" data-level="14.2.4" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#simple-effects-1"><i class="fa fa-check"></i><b>14.2.4</b> simple effects:</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="anova-vi-mixed-effects-anova-bs-ws.html"><a href="anova-vi-mixed-effects-anova-bs-ws.html#to-pool-or-not-to-pool-this-is-the-yada-yada-yada"><i class="fa fa-check"></i><b>14.3</b> to pool or not to pool, this is the yada yada yada</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html"><i class="fa fa-check"></i><b>A</b> Plotting histograms and probability distributions</a><ul>
<li class="chapter" data-level="A.1" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#the-basics"><i class="fa fa-check"></i><b>A.1</b> The Basics</a><ul>
<li class="chapter" data-level="A.1.1" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-1-building-the-canvas"><i class="fa fa-check"></i><b>A.1.1</b> Step 1: Building the canvas</a></li>
<li class="chapter" data-level="A.1.2" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-2-tell-ggplot-what-kind-of-plot-to-make."><i class="fa fa-check"></i><b>A.1.2</b> Step 2: Tell <code>ggplot</code> what kind of plot to make.</a></li>
<li class="chapter" data-level="A.1.3" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-3-adjust-the-axes-and-labels"><i class="fa fa-check"></i><b>A.1.3</b> Step 3: Adjust the axes and labels</a></li>
<li class="chapter" data-level="A.1.4" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-4-adjusting-for-apa"><i class="fa fa-check"></i><b>A.1.4</b> Step 4: Adjusting for APA</a></li>
<li class="chapter" data-level="A.1.5" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-5-add-and-adjust-the-legend"><i class="fa fa-check"></i><b>A.1.5</b> Step 5: Add and adjust the legend</a></li>
<li class="chapter" data-level="A.1.6" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#step-6-save-the-ggplot."><i class="fa fa-check"></i><b>A.1.6</b> Step 6: Save the <code>ggplot</code>.</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#a-note-about-your-bonus-on-week-4."><i class="fa fa-check"></i><b>A.2</b> A note about your BONUS on Week 4.</a></li>
<li class="chapter" data-level="A.3" data-path="plotting-histograms-and-probability-distributions.html"><a href="plotting-histograms-and-probability-distributions.html#advanced-stuff"><i class="fa fa-check"></i><b>A.3</b> Advanced stuff</a></li>
</ul></li>
<li class="divider"></li>
<li></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">musings of the Professor</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="correlation-and-regression" class="section level1">
<h1><span class="header-section-number">Week 6</span> Correlation and Regression</h1>
<p>In this week’s class we covered <strong>correlation</strong> and <strong>regression</strong>. In what follows we will revisit the ideas from this week’s lecture making explicit callbacks to topics from slides and using an example from the text. The examples from this page involve R. For a tutorial on how to perform similar analyses in SPSS, please check the appropriate video on the course Box Drive. Please note that this vignette assumes that you have the following packages installed and loaded in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pacman<span class="op">::</span><span class="kw">p_load</span>(car, <span class="co"># new qqPlot function</span>
               cowplot, <span class="co"># apa plotting</span>
               tidyverse, <span class="co"># tidyverse goodness</span>
               psych,
               lm.beta <span class="co"># getting standard coefficient</span>
               ) </code></pre></div>
<div id="the-relationship-btw-stress-and-health" class="section level2">
<h2><span class="header-section-number">6.1</span> The Relationship b/tw Stress and Health</h2>
<p><strong>From Howell (Section 9.2):</strong> Wagner, Compas, and Howell (1988) investigated the relationship between stress and mental health in first-year college students. Using a scale they developed to measure the frequency, perceived importance, and desirability of recent life events, they created a measure of negative events weighted by the reported frequency and the respondent’s subjective estimate of the impact of each event. This served as their measure of the subject’s perceived social and environmental stress. They also asked students to complete the Hopkins Symptom Checklist, assessing the presence or absence of 57 psychological symptoms.</p>
<p>This data (and most data mentioned in the text) can be accessed directly from Howell’s <a href="https://www.uvm.edu/~dhowell/methods8/">companion website</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Data from Table 9.2 Howell</span>
example &lt;-<span class="st"> </span><span class="kw">read_table</span>(<span class="st">&quot;https://www.uvm.edu/~dhowell/methods8/DataFiles/Tab9-2.dat&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   ID = col_integer(),
##   Stress = col_integer(),
##   Symptoms = col_integer(),
##   lnSymptoms = col_double()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">psych<span class="op">::</span><span class="kw">describe</span>(example)</code></pre></div>
<pre><code>##            vars   n  mean    sd median trimmed   mad   min    max  range
## ID            1 107 54.00 31.03  54.00   54.00 40.03  1.00 107.00 106.00
## Stress        2 107 21.29 12.49  20.00   20.49 11.86  1.00  58.00  57.00
## Symptoms      3 107 90.33 18.81  88.00   88.87 17.79 58.00 147.00  89.00
## lnSymptoms    4 107  4.48  0.20   4.48    4.48  0.19  4.06   4.99   0.93
##            skew kurtosis   se
## ID         0.00    -1.23 3.00
## Stress     0.62    -0.19 1.21
## Symptoms   0.74     0.45 1.82
## lnSymptoms 0.21    -0.28 0.02</code></pre>
<div id="testing-our-assumptions" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Testing our assumptions</h3>
<p>Here we are interested in the relationship between perceived <strong>Stress</strong> (as measured on a scale factors the number and impact of negative life events) and the presence of psychological <strong>Symptoms</strong>. As with any other parametric analysis, we first need to see if our data adheres to the assumptions of <strong>normality</strong> and <strong>homogeniety of varience</strong>. We can use the tools we’ve been employing for the last few weeks test these assumptions:</p>
<p>First <strong>Stress</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(example<span class="op">$</span>Stress, <span class="dt">breaks =</span> <span class="dv">10</span>)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-164-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">car<span class="op">::</span><span class="kw">qqPlot</span>(example<span class="op">$</span>Stress)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-164-2.png" width="672" /></p>
<pre><code>## [1] 72 55</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">shapiro.test</span>(example<span class="op">$</span>Stress)  <span class="co"># see Field (2014), Sec 5.6.1</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  example$Stress
## W = 0.96009, p-value = 0.002709</code></pre>
<p>Eyeballing the plots, our <strong>Stress</strong> measures look slightly skewed, but not egregiously so. This is confirmed by our obtained <code>skew</code> and <code>kurtosis</code> values. The final function <code>shapiro.test()</code> performs a Shapiro-Wilkes test (<span class="math inline">\(W\)</span>) of normality by comparing our observed distribution against a theoretical normal. Here the null hypothesis is that the <span class="math inline">\(observed == theoretical\)</span>, where <span class="math inline">\(p &lt; .05\)</span> indicates that the observed distribution is <em>not normal</em>. Our obtained p-value confirms suggests the possibility that <strong>Stress</strong> measures deviate from normal. However, as noted in the Field text (5.6.1) we need to be careful using the Shapiro-Wilkes test on large samples. Ultimately you need to make a judgment on whether or not all of the evidence available leads you to the conclusion of non-normality. In this case I would trust the normality of this data due to what I see in the Q-Q plot (very few large deviations from the normal line).</p>
<p><strong>Now Symptoms</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(example<span class="op">$</span>Symptoms, <span class="dt">breaks =</span> <span class="dv">10</span>)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-165-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">psych<span class="op">::</span><span class="kw">describe</span>(example<span class="op">$</span>Symptoms)</code></pre></div>
<pre><code>##    vars   n  mean    sd median trimmed   mad min max range skew kurtosis
## X1    1 107 90.33 18.81     88   88.87 17.79  58 147    89 0.74     0.45
##      se
## X1 1.82</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">car<span class="op">::</span><span class="kw">qqPlot</span>(example<span class="op">$</span>Symptoms)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-165-2.png" width="672" /></p>
<pre><code>## [1] 24 19</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">shapiro.test</span>(example<span class="op">$</span>Symptoms)  <span class="co"># see Field (2014), Sec 5.6.1</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  example$Symptoms
## W = 0.95918, p-value = 0.00232</code></pre>
<p><strong>Symptoms</strong> does not pass either the eyeball or the Shapiro-Wilkes tests. These data are positively skewed. One way of dealing with non-normal data is by performing a logarithmic transformation (see Field, 5.8). This has already been performed for this data, <strong>lnSymptoms</strong> is a natural logarithmic transform of <strong>Symptoms</strong>. With your own data, this can be accomplished quite simply in R by using the <code>log()</code>:</p>
<p><strong>Question 1. Perform a natural log transform of Symptoms and save it to a new column in your data frame <code>TransformedData</code>. Assess <code>TransformedData</code> using a qqPlot:</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">example<span class="op">$</span>TransformedData &lt;-<span class="st"> </span><span class="kw">log</span>(example<span class="op">$</span>Symptoms)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">car<span class="op">::</span><span class="kw">qqPlot</span>(example<span class="op">$</span>TransformedData)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-167-1.png" width="672" /></p>
<pre><code>## [1] 24 19</code></pre>
</div>
</div>
<div id="plotting-the-data" class="section level2">
<h2><span class="header-section-number">6.2</span> Plotting the data</h2>
<p>One of the first things that you should do is plot your data. Plotting gives you a sense of what is going on with your data. In fact, <strong>YOU SHOULD NEVER TAKE A TEST RESULT AT FACE VALUE WITHOUT FIRST LOOKING AT YOUR DATA!!</strong> Beware of <a href="https://en.wikipedia.org/wiki/Anscombe%27s_quartet">Anscombe’s quartet</a>!</p>
<p>Let’s plot using <code>ggplot</code>:</p>
<p><strong>Question 2: create a ggplot scatterplot</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(example, <span class="kw">aes</span>(<span class="dt">x =</span> example<span class="op">$</span>Stress, <span class="dt">y =</span> example<span class="op">$</span>lnSymptoms)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Stress&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;lnSymptoms&quot;</span>)

<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-168-1.png" width="672" /></p>
</div>
<div id="covariance-and-correlation" class="section level2">
<h2><span class="header-section-number">6.3</span> Covariance and Correlation</h2>
<p>Both the Howell and Field texts offer excellent overviews of <strong>covariance</strong> and <strong>correlation</strong> so I won’t go into too much depth here. Briefly, let’s make a few connections to ideas that we’ve already encountered.</p>
<div id="covariance" class="section level3">
<h3><span class="header-section-number">6.3.1</span> Covariance</h3>
<p>Recall that <strong>variance</strong> may be calculated as:   <span class="math inline">\(s_{x}^{2}=\frac{\sum \left ( x_{i}-\bar{X} \right )^{2}}{n-1}\)</span></p>
<p>Where the numerator is the sum of squared differences from each score to the sample mean, and the denominator is our degrees of freedom.</p>
<p>Variance tells us to what degree scores in a particular sample variable deviate from its mean. With this in mind, <strong>covarience</strong> is a statement about the degree to which two sampled variables deviate from their respective means. Consider we have sampled two measures, <em>X</em> &amp; <em>Y</em> from a population. When addressing the degree to which <em>X</em> and <em>Y</em> co-vary, we are asking the question: “To what degree and in what direction does <em>Y</em> move away from its mean as <em>X</em> moves from its mean?”</p>
<p>As such, the formula for covariance is simply an extension of the formula for variance that we already know: <span class="math display">\[s_{xy}=\frac{\sum \left ( x_{i}-\bar{X} \right )\left ( y_{i}-\bar{Y} \right )}{n-1}\]</span></p>
<p>So, in order to calculate the covariance we need the calculate the sum of the cross-product of the sum of squared differences of our two variables (<em>X</em> = <strong>Stress</strong>; <em>Y</em> = <strong>lnSymptoms</strong>) and divide that number by of degrees of freedom. We could go about the business of calculating this “by hand”:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># N = number of rows in data frame</span>
N &lt;-<span class="st"> </span><span class="kw">nrow</span>(example)


<span class="co"># mean Stress:</span>
meanX &lt;-<span class="st"> </span><span class="kw">mean</span>(example<span class="op">$</span>Stress)

<span class="co"># and same for lnSymptoms:</span>
meanY &lt;-<span class="st"> </span><span class="kw">mean</span>(example<span class="op">$</span>lnSymptoms)

<span class="co"># plug these values into our equation:</span>

<span class="co"># sum of cross product</span>
numerator &lt;-<span class="st"> </span><span class="kw">sum</span>((example<span class="op">$</span>Stress <span class="op">-</span><span class="st"> </span>meanX) <span class="op">*</span><span class="st"> </span>(example<span class="op">$</span>lnSymptoms <span class="op">-</span><span class="st"> </span>meanY))

<span class="co"># degrees of freedom</span>
denominator &lt;-<span class="st"> </span>(N <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)

<span class="co"># covariance:</span>
covXY &lt;-<span class="st"> </span>(numerator<span class="op">/</span>denominator) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre></div>
<pre><code>## [1] 1.336434</code></pre>
<p>The covariance of Stress and lnSymptoms is <strong>1.336</strong>.</p>
<p><strong>Question 3: Alternatively, covariance may be calculated quickly in <code>R</code> using the <code>cov()</code> function:</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cov</span>(example<span class="op">$</span>Stress, example<span class="op">$</span>lnSymptoms)</code></pre></div>
<pre><code>## [1] 1.336434</code></pre>
</div>
<div id="correlation" class="section level3">
<h3><span class="header-section-number">6.3.2</span> Correlation</h3>
<p>It may be tempting to calculate our <strong>covariance</strong> and stop there, but covariance is a limited measure. What I mean by this is that covarience indexes the degree of relationship between two specific variables, but doesn’t allow for more general comparison across situations. For a quick example, lets multiply both <strong>Stress</strong> and <strong>lnSymptoms</strong> by two. In R, (assuming all columns are <code>numerics</code>) we can accomplish this by multiplying the entire data frame by 2:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">example.by2 &lt;-<span class="st"> </span>example <span class="op">*</span><span class="st"> </span><span class="dv">2</span>
<span class="kw">head</span>(example.by2)</code></pre></div>
<pre><code>##   ID Stress Symptoms lnSymptoms TransformedData
## 1  2     60      198   9.190240        9.190240
## 2  4     54      188   9.086590        9.086590
## 3  6     18      160   8.764054        8.764053
## 4  8     40      140   8.496990        8.496990
## 5 10      6      200   9.210340        9.210340
## 6 12     30      218   9.382696        9.382696</code></pre>
<p>We would like to think that multiplying every value by a constant should have no effect on our general interpretation of the relationships in our data as the overall relationship in our data remain the same. To help make this apparent, let’s imagine that I weigh 200 lbs (yea… imagine) and my wife weighs 100 lbs. So I weigh twice as much as my wife. Over the next year we both go on a binge fest and both double our respective weights—I’m now 400 lbs and my wife is 200 lbs. I still weigh twice as much as my wife. Coincidentally the fact that relationships remain unchanged in spite of these sorts of mathematical transformations is why we could perform the natural logarithmic transform earlier and not feel too guilty.</p>
<p>Well what happens when I get the covariance of my <code>example.by2</code> data?:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cov</span>(example.by2<span class="op">$</span>Stress, example.by2<span class="op">$</span>lnSymptoms)</code></pre></div>
<pre><code>## [1] 5.345735</code></pre>
<p><strong>The covariance changes!!</strong> This is a problem, and is why, in order to usefully convey this data we report the <strong>correlation</strong>. The correlation is a <em>standardized</em> covariance.</p>
<p>The unit of measurement we’ll use for standardization is the standard deviation. We can standardize the covariance in one of two ways:</p>
<p>      1. Standardize our variables (into z-scores) and then calculate the covariance: <span class="math display">\[r_{xy}=\frac{\sum z_{x}z_{y}}{n-1}\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">zX &lt;-<span class="st"> </span><span class="kw">scale</span>(example<span class="op">$</span>Stress)
zY &lt;-<span class="st"> </span><span class="kw">scale</span>(example<span class="op">$</span>lnSymptoms)

corXY &lt;-<span class="st"> </span>(<span class="kw">sum</span>(zX <span class="op">*</span><span class="st"> </span>zY)<span class="op">/</span>(N <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre></div>
<pre><code>## [1] 0.5286565</code></pre>
<p>or</p>
<p>      2. Calculate the covariance and standardize it (by dividing by the product of the standard deviation): <span class="math display">\[r_{xy}=\frac{\sum \left ( x_{i}-\bar{X} \right )\left ( y_{i}-\bar{Y} \right )}{(n-1)s_{x}s_{y}}\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># get SD of X and Y:</span>
sdX &lt;-<span class="st"> </span><span class="kw">sd</span>(example<span class="op">$</span>Stress)
sdY &lt;-<span class="st"> </span><span class="kw">sd</span>(example<span class="op">$</span>lnSymptoms)

<span class="co"># using the covXY calculated above:</span>
covXY<span class="op">/</span>(sdX <span class="op">*</span><span class="st"> </span>sdY)</code></pre></div>
<pre><code>## [1] 0.5286565</code></pre>
<p>Again, in <code>R</code> we don’t need to do this by hand, there are in fact several functions. A more comprehensive look can be found in Field 6.5.3. The simplest function is <code>cor()</code>, with outputs the correlation as a single value. However, I prefer to use <code>cor.test()</code> as it tends to provide the most immediately useful data. You can input your data into this function in two ways:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(example<span class="op">$</span>Stress, example<span class="op">$</span>lnSymptoms)</code></pre></div>
<p>or</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(<span class="op">~</span>Stress <span class="op">+</span><span class="st"> </span>lnSymptoms, <span class="dt">data =</span> example)</code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Stress and lnSymptoms
## t = 6.3818, df = 105, p-value = 4.827e-09
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3765970 0.6529758
## sample estimates:
##       cor 
## 0.5286565</code></pre>
<p>I prefer the latter as it uses formula notation which is the sort of notation we will use for regression and later t.tests, and ANOVA. Finally, if you don’t want all the additional gobble-dee-gook from <code>cor.test</code> you can simply attach <code>$estimate</code> to the end of either the function or object like so:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(<span class="op">~</span>Stress <span class="op">+</span><span class="st"> </span>lnSymptoms, <span class="dt">data =</span> example)<span class="op">$</span>estimate</code></pre></div>
<pre><code>##       cor 
## 0.5286565</code></pre>
<p>How did I know that I could do this you ask? To get a quick list of things that you can pull from the attributes, try the <code>attributes()</code> function.</p>
<p><strong>Question 4</strong> save the <code>cor.test()</code> output of the correlation between <code>Stress</code> and <code>lnSymptoms</code> as an object <code>corOut</code>. Submit <code>corOut</code> to the <code>attributes()</code> function. Grab the <code>p.value</code> and <code>estimate</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">corOut &lt;-<span class="st"> </span><span class="kw">cor.test</span>(<span class="op">~</span>Stress <span class="op">+</span><span class="st"> </span>lnSymptoms, <span class="dt">data =</span> example)
<span class="kw">attributes</span>(corOut)</code></pre></div>
<pre><code>## $names
## [1] &quot;statistic&quot;   &quot;parameter&quot;   &quot;p.value&quot;     &quot;estimate&quot;    &quot;null.value&quot; 
## [6] &quot;alternative&quot; &quot;method&quot;      &quot;data.name&quot;   &quot;conf.int&quot;   
## 
## $class
## [1] &quot;htest&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">corOut<span class="op">$</span>p.value</code></pre></div>
<pre><code>## [1] 4.827486e-09</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">corOut<span class="op">$</span>estimate</code></pre></div>
<pre><code>##       cor 
## 0.5286565</code></pre>
<p>Our correlation is expressed in terms of the <strong>Pearson’s product-moment correlation coefficient</strong> (or <span class="math inline">\(r\)</span>, for short). Here <span class="math inline">\(r\)</span> = .529.</p>
<p>Coincidentally, returning to our problematic transformed data <code>example.by2</code>, we find that the obtained <span class="math inline">\(r\)</span> is identical:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(<span class="op">~</span>Stress <span class="op">+</span><span class="st"> </span>lnSymptoms, <span class="dt">data =</span> example.by2)</code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Stress and lnSymptoms
## t = 6.3818, df = 105, p-value = 4.827e-09
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3765970 0.6529758
## sample estimates:
##       cor 
## 0.5286565</code></pre>
<p>Note that when our sample size is small we may need to adjust <span class="math inline">\(r\)</span>. This is because the sampling distribution of <span class="math inline">\(r\)</span> is not normally distributed.</p>
<p>The formula for this adjustment is:     <span class="math inline">\(r_{adj}=\sqrt{1-\frac{\sum \left (1-r^2 \right )\left ( n-1 \right )}{n-2}}\)</span></p>
<p>For now, we can calculate this by hand, but later we will see that it will be provided by another function (or at least its squared value will).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Pearson&#39;s r:</span>
rXY &lt;-<span class="st"> </span><span class="kw">cor.test</span>(<span class="op">~</span>Stress <span class="op">+</span><span class="st"> </span>lnSymptoms, <span class="dt">data =</span> example)<span class="op">$</span>estimate

<span class="co"># adjusted r:</span>
rXYadj &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>((<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>rXY<span class="op">^</span><span class="dv">2</span>) <span class="op">*</span><span class="st"> </span>(N <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)<span class="op">/</span>(N <span class="op">-</span><span class="st"> </span><span class="dv">2</span>))) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre></div>
<pre><code>##      cor 
## 0.522126</code></pre>
</div>
</div>
<div id="sigfnificance-testing-r" class="section level2">
<h2><span class="header-section-number">6.4</span> Sigfnificance testing <span class="math inline">\(r\)</span></h2>
<p>It may be useful to perform tests of significance on <span class="math inline">\(r\)</span>. Typically, there are two types of tests that we perform:</p>
<ol style="list-style-type: decimal">
<li>a test of the observed <span class="math inline">\(r\)</span> to <span class="math inline">\(r=0\)</span>, and</li>
<li>a test of the difference between two <span class="math inline">\(r\)</span> values.</li>
</ol>
<p>Regarding the first case, the test that the observed correlation is different from 0, Howell correctly notes the following (Section 9.11): - “a test on b is equivalent to a test on r in the one-predictor case we are discussing in this chapter. If it is true that <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are related, then it must also be true that <span class="math inline">\(Y\)</span> varies with <span class="math inline">\(X\)</span>—that is, that the slope is nonzero. This suggests that a test on <span class="math inline">\(b\)</span> (beta coefficient) will produce the same answer as a test on <span class="math inline">\(r\)</span>, and we could dispense with a test for <span class="math inline">\(b\)</span> altogether.”</p>
<p>The reverse is also true. In the single predictor case, if one has a test of <span class="math inline">\(b\)</span> this obviates the need to run an independent test of <span class="math inline">\(r\)</span>. As you will see below, we indeed do have a simple test that gives us the significance of the beta coefficient, <span class="math inline">\(b\)</span>.</p>
<p>In the second case, the difference between <span class="math inline">\(r\)</span> values, we may invoke the <code>paired.r()</code> function from the <code>psych</code> package. Using the <span class="math inline">\(r\)</span> values from the example in Section 9.11 of the Howell text, “Testing the Difference Between Two Independent <span class="math inline">\(r\)</span>s”:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">psych<span class="op">::</span><span class="kw">paired.r</span>(<span class="dt">xy =</span> <span class="fl">0.5</span>, <span class="dt">xz =</span> <span class="fl">0.4</span>, <span class="dt">n =</span> <span class="dv">53</span>, <span class="dt">n2 =</span> <span class="dv">53</span>, <span class="dt">twotailed =</span> T)</code></pre></div>
<pre><code>## Call: psych::paired.r(xy = 0.5, xz = 0.4, n = 53, n2 = 53, twotailed = T)
## [1] &quot;test of difference between two independent correlations&quot;
## z = 0.63  With probability =  0.53</code></pre>
<p>where:</p>
<ul>
<li><code>xy</code>: the correlation in the first data set</li>
<li><code>xz</code>: the correlation in the second data set</li>
<li><code>n</code>: the number of samples in the first data set</li>
<li><code>n2</code>: the number of samples in the second data set -<code>twotailed</code>: run a two-tailed test, <code>TRUE</code> or <code>FALSE</code></li>
</ul>
<p>This output tells us the resulting Fisher <span class="math inline">\(z\)</span> score and corresponding probability.</p>
<p><strong>Question 5</strong>: For example assume that you sample 35 men and find a correlation of .42 between Symptoms and Stress. In another sample of 42 women you find a correlation of .51. Perform a test to see if those two correlations are different from one another.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">psych<span class="op">::</span><span class="kw">paired.r</span>(<span class="dt">xy =</span> <span class="fl">0.42</span>, <span class="dt">xz =</span> <span class="fl">0.51</span>, <span class="dt">n =</span> <span class="dv">35</span>, <span class="dt">n2 =</span> <span class="dv">42</span>, <span class="dt">twotailed =</span> T)</code></pre></div>
<pre><code>## Call: psych::paired.r(xy = 0.42, xz = 0.51, n = 35, n2 = 42, twotailed = T)
## [1] &quot;test of difference between two independent correlations&quot;
## z = 0.48  With probability =  0.63</code></pre>
</div>
<div id="fitting-the-data-to-a-model" class="section level2">
<h2><span class="header-section-number">6.5</span> Fitting the data to a model</h2>
<p>As social scientists, we are not only concerned with observation, but also with explanation. Measures of correlation provide us with the former; we use regression methods to build models in service of the latter. Again both the Field and Howell texts provide excellent overviews of regression, so I won’t repeat much of what they say here.</p>
<p>For the purposes of this vignette (and course) we will limit ourselves to linear regression, that is describing a line that best fits our data. By “fit” we mean a line than when compared to our observed data minimizes our squared residuals.</p>
<p>To perform a linear regression we may call upon the <code>lm()</code> function. This function uses formula notation <code>outcome variable ~ predictor variable(s)</code>. A simple regression has a single predictor. More often in our analyses we are concerned with the relative effects of multiple predictors, but this is multiple regression and saved for the Spring course. Here, we may be interested in the degree to which perceived <strong>Stress</strong> contributes to the number of <strong>lnSymptons</strong>, or using formula terminology: “How do lnSymptoms (outcome) vary as a function of Stress (predictor)”. This is represented in R as <code>example$lnSymptoms~example$Stress</code></p>
</div>
<div id="linear-models-in-r" class="section level2">
<h2><span class="header-section-number">6.6</span> Linear models in R</h2>
<p>Our model assigned to <code>example.model</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">example.model &lt;-<span class="st"> </span><span class="kw">lm</span>(example<span class="op">$</span>lnSymptoms <span class="op">~</span><span class="st"> </span>example<span class="op">$</span>Stress)
<span class="kw">print</span>(example.model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = example$lnSymptoms ~ example$Stress)
## 
## Coefficients:
##    (Intercept)  example$Stress  
##       4.300537        0.008565</code></pre>
<p>While this output only gives us our coefficients (intercept and slope of our line), our object <code>example.model</code> has the class <code>lm</code>. This simply means that R understands that this object is storing a linear model. Hiding behind this spartan output is a multitude of info that may be accessed via its <code>attributes</code> or it may be thrown into other functions for additional info and analysis.</p>
<div id="attributes-of-class-lm" class="section level3">
<h3><span class="header-section-number">6.6.1</span> Attributes of class <code>lm</code>:</h3>
<p>As I mentioned above, <code>lm</code> objects contain various attributes that may be accessed using the names convention, <code>$nameOfAttribute</code>.</p>
<p>For example, returning to the <code>example.model</code> object we created above, we may get a glimpse of its attributes by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attributes</span>(example.model)</code></pre></div>
<pre><code>## $names
##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;        
## 
## $class
## [1] &quot;lm&quot;</code></pre>
<p>This command tells us the names of several attributes (values) that are stored in <code>example.model</code>. Typically we are interested in the <code>$coefficients</code>, <code>fitted.values</code> (aka <em>predicted values</em>), and <code>$residuals</code>. Recall that in our model <code>fitted.values</code> are the predicted values of <strong>lnSymptoms</strong> for each value of <strong>Stress</strong>, that is those values that fall along the line of best fit. <code>residuals</code> are the difference between our observed values of <strong>lnSymptoms</strong> and those predicted by the model. Mathematically <code>example.model$residuals</code> is equivalent to:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">example<span class="op">$</span>lnSymptoms <span class="op">-</span><span class="st"> </span>example.model<span class="op">$</span>fitted.values</code></pre></div>
</div>
<div id="testing-the-residuals" class="section level3">
<h3><span class="header-section-number">6.6.2</span> Testing the residuals</h3>
<p>An important assumption test for our model is that the residuals are normally distributed. In fact some argue that this is more important than than having normal distributions in the raw data itself. Quickly, we can test this using the regular methods:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(example.model<span class="op">$</span>residuals, <span class="dt">breaks =</span> <span class="dv">10</span>)
car<span class="op">::</span><span class="kw">qqPlot</span>(example.model<span class="op">$</span>residuals) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">show</span>()
psych<span class="op">::</span><span class="kw">describe</span>(example.model<span class="op">$</span>residuals)</code></pre></div>
<p><strong>Question 6: Run a Shapiro-Wilkes test on our <code>example.model</code> residuals. How do we feel about the residuals here?</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">shapiro.test</span>(example.model<span class="op">$</span>residuals)</code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  example.model$residuals
## W = 0.9876, p-value = 0.429</code></pre>
</div>
<div id="using-your-lm-object-with-other-functions" class="section level3">
<h3><span class="header-section-number">6.6.3</span> Using your <code>lm</code> object with other functions</h3>
<p>As I mentioned above you may also use <code>lm</code> objects with other functions. For example, for our model <code>example.model</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(example.model)</code></pre></div>
<p>produces a host of successive plots, including a plot of “Residuals v. Fitted”, A Q-Q plot that includes possible outliers, and a leverage plot. The last is outside of the scope of this course, but may be useful for you to remember in the Spring!</p>
<p>A useful call for our present purposes is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(example.model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = example$lnSymptoms ~ example$Stress)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.42889 -0.13568  0.00478  0.09672  0.40726 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    4.300537   0.033088 129.974  &lt; 2e-16 ***
## example$Stress 0.008565   0.001342   6.382 4.83e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1726 on 105 degrees of freedom
## Multiple R-squared:  0.2795, Adjusted R-squared:  0.2726 
## F-statistic: 40.73 on 1 and 105 DF,  p-value: 4.827e-09</code></pre>
<p>which provides us with info about the coefficients, their standard error, <em>t</em>-scores, and corresponding p-values (Pr&gt;|t|). It also provides us with our <span class="math inline">\(r^2\)</span> and adjusted <span class="math inline">\(r_{adj}^2\)</span> (which corresponds to our <span class="math inline">\(r\)</span> and <span class="math inline">\(r_{adj}\)</span> from above).</p>
<p>Coincidentally we can also call the individual attributes of this summary as well:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(example.model) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">attributes</span>()</code></pre></div>
<pre><code>## $names
##  [1] &quot;call&quot;          &quot;terms&quot;         &quot;residuals&quot;     &quot;coefficients&quot; 
##  [5] &quot;aliased&quot;       &quot;sigma&quot;         &quot;df&quot;            &quot;r.squared&quot;    
##  [9] &quot;adj.r.squared&quot; &quot;fstatistic&quot;    &quot;cov.unscaled&quot; 
## 
## $class
## [1] &quot;summary.lm&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(example.model)<span class="op">$</span>coefficients</code></pre></div>
<pre><code>##                   Estimate  Std. Error    t value      Pr(&gt;|t|)
## (Intercept)    4.300536618 0.033087547 129.974478 8.085268e-118
## example$Stress 0.008564802 0.001342063   6.381819  4.827486e-09</code></pre>
<p>We’ll return to each of these later, but first let’s return to our plot:</p>
</div>
<div id="plotting-the-regression-line" class="section level3">
<h3><span class="header-section-number">6.6.4</span> Plotting the regression line</h3>
<p>It’s useful practice to plot the regression line. In fact, I would typically recommend doing this at the outset of the analysis (way back at the beginning) but we had a few things to cover make this step clear. To add a simple regression line to our previous plot we can use the <code>geom_smooth()</code> function. <code>geom_smooth()</code> takes the following arguements:</p>
<p>-<code>method</code>: what kind of regression line do you want to create? in this case we are performing a linear regression, so <code>lm</code>.</p>
<p>-<code>mapping</code>: is you did not specify your <code>aes()</code> in the original call you need to specify them here (whats on the x-axis, y-axis, etc).</p>
<p>-<code>level</code>: create a ribbon specifying a confidence interval of each predicted value (here I’m using 95% CI).</p>
<p>-<code>color</code>: what color do you want the line.</p>
<p>-<code>linetype</code>: solid line? dotted line? dashed line? default is solid.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># creating a new plot with our original scatter plot as a template:</span>
p &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw">ggplot</span>(example, <span class="kw">aes</span>(<span class="dt">x =</span> example<span class="op">$</span>Stress, <span class="dt">y =</span> example<span class="op">$</span>lnSymptoms)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Stress&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;lnSymptoms&quot;</span>)

smooth_p &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms), <span class="dt">method =</span> lm, 
    <span class="dt">level =</span> <span class="fl">0.95</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>)
<span class="kw">show</span>(smooth_p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-190-1.png" width="672" /></p>
<p>The shaded ribbon around the line of regression represents the 95% CI of the estimate at each value of the predictor. The size of the CI may be adjusted by using the <code>level</code> parameter in <code>geom_smooth()</code>.</p>
<p>Comparing this plot to our <code>example.model</code> output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(example.model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = example$lnSymptoms ~ example$Stress)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.42889 -0.13568  0.00478  0.09672  0.40726 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    4.300537   0.033088 129.974  &lt; 2e-16 ***
## example$Stress 0.008565   0.001342   6.382 4.83e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1726 on 105 degrees of freedom
## Multiple R-squared:  0.2795, Adjusted R-squared:  0.2726 
## F-statistic: 40.73 on 1 and 105 DF,  p-value: 4.827e-09</code></pre>
<p>From this plot it becomes apparent that the model coefficients obtained above represent the values of the slope and intercept of the regression line.</p>
<ul>
<li><p>The beta coefficient conveys the <em>slope</em> of the line—unit change in outcome per unit change in predictor. Typically this is expressed as <em>b</em> in text or <strong>B</strong> in SPSS. In <code>R</code> output, the beta estimate is tied to the name of the corresponding predictor variable. In our case that’s <code>example$Stress</code>.</p></li>
<li><p>The <strong>intercept</strong> tells us what the value of the outcome would be if the predictor was 0. In most instances the intercept is not terribly useful. For example if you were looking at the relationship between height and weight it would make no sense to concern yourself with instances where height is absolutely 0. Obviously, a caveat here is if the value 0 is meaningful for your analysis. For example perhaps you are looking at depression as a function of alcohol consumption and want to explicitly say something about people that have never had a single drink in their life.</p></li>
</ul>
<p>One way of making a meaningless intercept meaningful is by centering your data (subtracting every value of your predictor from a constant). For example, if you center around the mean, the intercept will tell you the predicted value of the outcome variable at the mean value of the predictor.</p>
<p>Just for giggles, lets plot our mean-centered data. We mean center <code>Stress</code> by subtracting each value of <code>Stress</code> from its mean:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ggplot2<span class="op">::</span><span class="kw">ggplot</span>(<span class="dt">data =</span> example) <span class="op">+</span><span class="st"> </span><span class="co"># plot each data point as a small red open circle</span>
<span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> (Stress <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(Stress)), <span class="dt">y =</span> lnSymptoms), <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, 
    <span class="dt">shape =</span> <span class="dv">19</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="kw">aes</span>(<span class="dt">x =</span> (Stress <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(Stress)), <span class="dt">y =</span> lnSymptoms), <span class="dt">method =</span> lm, 
    <span class="dt">level =</span> <span class="fl">0.95</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Stress&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;lnSymptoms&quot;</span>)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-192-1.png" width="672" /></p>
<p>as you can see slope doesn’t change, but the values become centered around the intercept.</p>
</div>
<div id="a-note-on-degrees-of-freedom-of-our-model" class="section level3">
<h3><span class="header-section-number">6.6.5</span> A note on degrees of freedom of our model</h3>
<p>The general equation for calculating the requisite degrees of freedom of a model is <span class="math inline">\(n-k\)</span> where <span class="math inline">\(n\)</span> is the number of observations (or later conditions) and <span class="math inline">\(k\)</span> is the number of parameters that are required to be known for the calculation.</p>
<p>Recall how we calculate variance / standard deviation. We take the sum of the squared deviations from the <em>mean</em> <span class="math inline">\(\sum(X-\bar{X})\)</span> and divide by <span class="math inline">\((n-1)\)</span>. Remember that we are subtracting that 1 because in order to calculate the variance we must keep one thing constant, the <strong>mean</strong>. In this case the <strong>mean</strong> is our parameter that must be known in order to calculate the variance.</p>
<p>We can now ask the question “what must be known in order to derive the line of best fit?”, or more simply what must one know in order to create a particular line. We must know <strong>both</strong> the line’s <strong>slope</strong> and its <strong>intercept</strong>. Knowing slope alone leads to the indeterminism presented in Fig A (identical slopes, infinitely-many intercepts), intercept alone leads to indeterminism presented in Fig B (identical intercept, infinitely-many slopes). We need <strong>both</strong> to define a particular line. Just like the <strong>mean</strong> above, these are the two parameters that must be <em>locked-in</em> to derive our model.</p>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-193-1.png" width="768" /></p>
<p>A simple way of restating this is that your model degrees of freedom are the: <span class="math display">\[number \space of \space observations -  number \space of \space predictors\]</span></p>
<p>where at least one of your predictors is used as a constant (the intercept) and the remainder provide your <span class="math inline">\(\beta\)</span> coefficients.</p>
<p>For simple regression we have 1 predictor and 1 constant so our degrees of freedom are <span class="math inline">\(n-k\)</span>; where <span class="math inline">\(k=2\)</span>. However, in your future <strong>there be be dragons</strong>… models that may have multiple predictors and multiple intercepts (multiple regression, mixed effects / multi-level models, etc).</p>
</div>
<div id="interpreting-the-output" class="section level3">
<h3><span class="header-section-number">6.6.6</span> Interpreting the output</h3>
<p>With our plot in hand, we can return to our <code>summary(example.model)</code> output:</p>
<ul>
<li><strong>Call</strong>: tells us the formula we originally input for this model</li>
<li><strong>Residuals</strong>: descriptive stats of the residuals</li>
<li><p><strong>Coefficients</strong>: provides the estimated values, standard error of the estimates, and NHST of the intercept and beta coefficient. In both cases the null hypothesis is Estimate = 0. Again for the intercept this may or may not be useful. For example you might use it to test whether people who haven’t had a single drink of alcohol have no depression at all. The test of <code>beta</code> tests against the null hypothesis of zero correlation (relationship). All tests are conducted provided the t-value on <span class="math inline">\(n-k\)</span> degrees of freedom (see next bullet point)</p></li>
<li><p><strong>Residual standard error</strong>: This is calculated by first getting the sum of the squared residuals and dividing that number by the degrees of freedom of the model. In this case the df equals the number of total observations (107) minus the number of parameters (<span class="math inline">\(k\)</span>) that were calculated by the model in order to generate the predicted values (2). This may be interpreted as a measure of goodness of fit of the model, and perhaps more importantly its predictive value (see Howell 9.7).</p></li>
<li><p><strong>Multiple R-squared</strong> and <strong>Adjusted R-squared</strong>: The <strong>coefficient of determination</strong> calculated from <span class="math inline">\(r\)</span> or <span class="math inline">\(r_{adj}\)</span>. <span class="math inline">\(r^2\)</span> tells us the degree to which our model accounts for observed variance in the observed outcomes. On was to think about this is, to what degree does variation in our predictor explain the observed variation in our outcomes. More on this below.</p></li>
<li><p>Finally, this output gives is the resulting <span class="math inline">\(F\)</span>-ratio and corresponding <span class="math inline">\(df\)</span> for an <span class="math inline">\(F\)</span>-test. This is a significance test for our <span class="math inline">\(r^2\)</span>. Does our model explain a significant amount of the variance?</p></li>
</ul>
</div>
<div id="the-coeff.-of-determination-as-index-of-explanatory-value" class="section level3">
<h3><span class="header-section-number">6.6.7</span> The coeff. of determination as index of explanatory value</h3>
<p>Here we may turn to a (a little bit longer than expected) digression involving J.S. Mill and <em>exact</em> and <em>inexact</em> sciences. One philosophical conceit is that we can never really empirically observe causes, but only effects. That is, I can never truly observe that one billiard ball <em>caused</em> another to move, I can only say with a high degree of certainty that I observed the first billiard ball striking the second and subsequently the second moved at a particular velocity. In order to deal with this epistemological crisis (how can you really ever know anything!!!) we build explanatory models. The degree to which our model is able to account for the range of our previous observations tells us how useful our model parameters (predictors) are in explaining a phenomenon in question.</p>
<p>For example, to explain what I observe about the contact and subsequent motion of billiard balls I might build a model that takes into account the mass and velocity (speed and direction) of the first ball, the mass and velocity of the second ball and the point and angle of contact. Presuming I use these as predictors, I can account with varying degrees of success the heading and direction of the balls, or the <em>outcome</em>. In fact, in this example, I’m likely to be very successful in describing most, <strong>but not all</strong> observed outcomes. That is, there are some variations in the outcomes that just using these parameters does not result in a successful account. I can refine my <em>billiard contact model</em> to include things like the friction caused from the felt, the force of gravity, the angle of the table top, etc., and it’s likely the case that with each new predictor my model becomes better. However at some point I begin to reach diminishing returns (see over-fitting next semester).</p>
<p>This is why physics <em>appears</em> to be an exact science (well, mechanical physics at least). They’ve had centuries to develop and refine their models about the mechanical workings of our very local corner of the universe to the point that these models are able to account for a very high degree of variation in observed phenomena. These models typically have a very high <span class="math inline">\(r^2\)</span> and as such tend to have high predictive value. Which is why with some understanding of gravitational force, mass, and a few simple calculations, high school students all over country are able to do <a href="https://www.youtube.com/watch?v=46CJmWlxfck">this</a> in their physics lab.</p>
<p>Indeed within some disciplines having an <span class="math inline">\(r^2\)</span> &lt; .9 means you model isn’t good enough. Typically this is the case when the phenomenon under observation is not complex (hope that doesn’t offend). As you move away from physics and chemistry (or at least the low complexity phenomena under each discipline), the explanatory value of models tends to decrease. Us folks in the social sciences, we are moving into inexact-science-land. Weather patterns, economies, ecosystems, and human behaviors are highly complex; in many cases in inordinate number of contributing factors may be present in an observed outcome. As a result degree of variation that these models may account for is typically diminished, especially in the social sciences. For example depending on the phenomena and sub-discipline, an <span class="math inline">\(r^2\)</span> of .3 might mean you’re cooking with gas! In fact, for some phenomena, a reported <span class="math inline">\(r^2\)</span> that is too high might be a cause for suspicion (“they weren’t so much cooking with gas so much as they were cooking the books”).</p>
<p>As a final note, its typically poor practice to get a significant <span class="math inline">\(r^2\)</span> and just stop there. Remember, this is just a claim that your model accounts for significantly more variation than 0%. If you were to have a model that accounted for 6% (<span class="math inline">\(r^2 = .06\)</span>) of the variance but was significant (<span class="math inline">\(p&lt;.05\)</span>), you need to ask yourself whether that model is useful at all. It certainly has very little predictive value (I wouldn’t bet my life… or even a few bills on it predicting a future outcome), and its true explanatory value is quite questionable. <br> <br> <br> <img src="https://imgs.xkcd.com/comics/linear_regression.png" /></p>
</div>
</div>
<div id="write-up-and-presentaion" class="section level2">
<h2><span class="header-section-number">6.7</span> Write up and presentaion</h2>
<p>Our obtained results can be reported in several different ways. However, typically it’s best practice to report both the <span class="math inline">\(beta\)</span> coefficient with corresponding <span class="math inline">\(t-test\)</span>; as well as the general statistics about the model including the <span class="math inline">\(r^2\)</span> and corresponding <span class="math inline">\(F-test\)</span>. Prior to any reporting of the stats, you also need to articulate the structure of the model.</p>
<p>I think a good template to start from is:</p>
<blockquote>
<p>“[Clearly restate the alternative hypothesis identifying operationalized variables]. To test this hypothesis the data were [what type of analysis?] with [what is your dv] as the outcome and [what is your predictor] as our predictor. The resulting model was significant, r^2=XXX; <em>F</em>(df1,df2)=F-ratio, <em>p</em>=p-value and revealed a significant relationship between the [covariables], <em>b</em>=XX; <em>t</em>(df)=XX, <em>p</em>=XX$.”</p>
</blockquote>
<p>For example, with this data you may report it as:</p>
<blockquote>
<p>“We hypothesized that increases in self-reported measures of Stress would correspond to increases in the number of self-reported symptoms. Given that our Symptoms data showed a significant violation of the normality assumption, we transformed these scores using a log-transformation (lnSymptoms). To test this hypothesis the data were submitted to a simple linear regression with lnSymptoms as the outcome and Stress as our predictor. The resulting model was significant, <span class="math inline">\(r^2\)</span>=.28; <span class="math inline">\(F\)</span>(1,105)=40.73, p&lt;.001$, and revealed a significant positive relationship between the Stress and Symptoms, <span class="math inline">\(b\)</span>=.008; <span class="math inline">\(t\)</span>(105)=6.38, <span class="math inline">\(p\)</span>&lt;.001.”</p>
</blockquote>
<p>That said, in many circles it’s typical practice to report the <em>standardized</em> <span class="math inline">\(beta\)</span> coefficients (<span class="math inline">\(\beta\)</span>). These are the <span class="math inline">\(beta\)</span> coefficients we would have obtained if we had initially converted both our <em>Stress</em> and <em>lnSymptom</em> values to <span class="math inline">\(z\)</span>-scores. We can retroactively obtain these coefficients by using the <code>lm.beta()</code> function from the <code>lm.beta</code> package (duplicate names, confusing I know). We can then input an <code>lm</code> class objects into the <code>lm.beta()</code> function and get the summary of those results. The new column <code>Standardized</code> is reported rather than <code>Estimate</code>:</p>
<p><strong>Question 7</strong> Use <code>lm.beta::lm.beta()</code> to obtain the standard coefficients. How would you report these results?</p>
<div class="sourceCode"><pre class="sourceCode rs"><code class="sourceCode rust">lm.beta::lm.beta(example.model) %&gt;% summary()</code></pre></div>
<p>So amending the example reporting paragrah above:</p>
<blockquote>
<p>The resulting model was significant, <span class="math inline">\(r^2\)</span>=.28; <span class="math inline">\(F\)</span>(1,105)=40.73, <span class="math inline">\(p\)</span>&lt;.001, and revealed a significant positive relationship between the Stress and Symptoms, <span class="math inline">\(\beta =.528\)</span>; <span class="math inline">\(t(105)=6.38\)</span>, <span class="math inline">\(p&lt;.001\)</span>.&quot;</p>
</blockquote>
<p>Coincidentally you may have noticed that this value is the correlation that we established earlier. Again I point to Howell 9.11 for how these two are similar in the single predictor case.</p>
</div>
<div id="advanced-plotting" class="section level2">
<h2><span class="header-section-number">6.8</span> Advanced plotting</h2>
<p>Depending on what info you are trying to convey, there are several ways of dressing up your plot. In this section we’ll cover three things that you can do with the plots above: - adding text information like <span class="math inline">\(r^2\)</span> and the equation of the regression line - placing two (or more) plots side-by-side - placing two sample (and regression lines) on the same plot</p>
<div id="adding-text-to-the-plot" class="section level3">
<h3><span class="header-section-number">6.8.1</span> Adding text to the plot</h3>
<p>Text may be added to a plot using the <code>annotate()</code> function in <code>ggplot2</code>. This function has several arguments: the type of annotation (typically <code>geom=&quot;text&quot;</code>), the <code>x</code> position of the plot (measured in units of the x axis), the <code>y</code> position of the plot, the <code>label</code> or text that you want to add (in string form) and the whether or not <code>R</code> needs to parse the text. For simple text like “Hi my name is..” doesn’t need parsing. For more complex text like some of what we will be doing (text that needs to be italicized, superscripts, etc) you need to set <code>parse=TRUE</code>. Finally you can adjust the size of the text.</p>
<p>We can create the necessary text for out plot by hand by simply adding these repective values in format that we construct. However, there are a few leaps and bounds that we need to do in order to format the text and plug in our values. For the same of simplicity just take this at face value for now, but feel free to follow-up in your free time to see exactly what is going on here:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># putting together my equation, telling R to add superscripts and italics:</span>
equation &lt;-<span class="st"> </span><span class="kw">italic</span>(y) <span class="op">==</span><span class="st"> </span><span class="fl">4.301</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.009</span> <span class="op">%.%</span><span class="st"> </span><span class="kw">italic</span>(x) <span class="op">*</span><span class="st"> &quot;,&quot;</span> <span class="op">~</span><span class="st"> </span><span class="er">~</span><span class="kw">italic</span>(r)<span class="op">^</span><span class="dv">2</span> <span class="op">~</span><span class="st"> &quot;=&quot;</span> <span class="op">~</span><span class="st"> </span>
<span class="st">    </span><span class="fl">0.28</span>

<span class="co"># turn it into an expression for R to parse:</span>
equation &lt;-<span class="st"> </span><span class="kw">as.expression</span>(equation) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as.character</span>()</code></pre></div>
<p>and now add it to my previous plot using <code>annotate()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create scatter plot</span>
p &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw">ggplot</span>(<span class="dt">data =</span> example) <span class="op">+</span><span class="st"> </span><span class="co"># plot each data point as a small red open circle</span>
<span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms), <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">shape =</span> <span class="dv">19</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_cowplot</span>()

<span class="co"># adding the regression line</span>
p &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms), <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">method =</span> lm, 
    <span class="dt">level =</span> <span class="fl">0.95</span>)

<span class="co"># adding text</span>
p &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="kw">annotate</span>(<span class="dt">geom =</span> <span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="dv">20</span>, <span class="dt">y =</span> <span class="dv">5</span>, <span class="dt">label =</span> equation, <span class="dt">parse =</span> T, <span class="dt">size =</span> <span class="dv">4</span>)

<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-196-1.png" width="672" /></p>
<p>You’ll note that my text is centered at the intesection of where <code>x=20</code> and <code>y=5</code>. You may need to play around with these values to get this right.</p>
</div>
<div id="addnig-text-like-a-r-ninja" class="section level3">
<h3><span class="header-section-number">6.8.2</span> addnig text like a R-ninja:</h3>
<p>The other useful thing to remember is that you can access different parts of an <code>lm</code> class object using its attributes (see above). In this case we can call on various attributes of <code>example.model</code>. For example we can get the coefficients by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">example.model<span class="op">$</span>coefficients</code></pre></div>
<pre><code>##    (Intercept) example$Stress 
##    4.300536618    0.008564802</code></pre>
<p>we call also get them by using the <code>coef()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(example.model)</code></pre></div>
<pre><code>##    (Intercept) example$Stress 
##    4.300536618    0.008564802</code></pre>
<p>the same can be said about the <span class="math inline">\(r^2\)</span>. It’s available from the summary model attributes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># list our attributes:</span>
<span class="kw">summary</span>(example.model) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">attributes</span>()</code></pre></div>
<pre><code>## $names
##  [1] &quot;call&quot;          &quot;terms&quot;         &quot;residuals&quot;     &quot;coefficients&quot; 
##  [5] &quot;aliased&quot;       &quot;sigma&quot;         &quot;df&quot;            &quot;r.squared&quot;    
##  [9] &quot;adj.r.squared&quot; &quot;fstatistic&quot;    &quot;cov.unscaled&quot; 
## 
## $class
## [1] &quot;summary.lm&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># we want &#39;r.squared&#39;:</span>
<span class="kw">summary</span>(example.model)<span class="op">$</span>r.squared</code></pre></div>
<pre><code>## [1] 0.2794776</code></pre>
<p>knowing this we can actually create a function to do the above for us automatically (see I told you building you own functions would com in handy). True, there are a few things that we haven’t covered yet in the code, so feel free to look them up:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create a function called lm_eqn</span>
lm_eqn =<span class="st"> </span><span class="cf">function</span>(m) {
    
    l &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">a =</span> <span class="kw">format</span>(<span class="kw">coef</span>(m)[<span class="dv">1</span>], <span class="dt">digits =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unname</span>(), <span class="dt">b =</span> <span class="kw">format</span>(<span class="kw">abs</span>(<span class="kw">coef</span>(m)[<span class="dv">2</span>]), 
        <span class="dt">digits =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unname</span>(), <span class="dt">r2 =</span> <span class="kw">format</span>(<span class="kw">summary</span>(m)<span class="op">$</span>r.squared, <span class="dt">digits =</span> <span class="dv">3</span>))
    
    <span class="cf">if</span> (<span class="kw">coef</span>(m)[<span class="dv">2</span>] <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span>) {
        eq &lt;-<span class="st"> </span><span class="kw">substitute</span>(<span class="kw">italic</span>(y) <span class="op">==</span><span class="st"> </span>a <span class="op">+</span><span class="st"> </span>b <span class="op">%.%</span><span class="st"> </span><span class="kw">italic</span>(x) <span class="op">*</span><span class="st"> &quot;,&quot;</span> <span class="op">~</span><span class="st"> </span><span class="er">~</span><span class="kw">italic</span>(r)<span class="op">^</span><span class="dv">2</span> <span class="op">~</span><span class="st"> </span>
<span class="st">            &quot;=&quot;</span> <span class="op">~</span><span class="st"> </span>r2, l)
    } <span class="cf">else</span> {
        eq &lt;-<span class="st"> </span><span class="kw">substitute</span>(<span class="kw">italic</span>(y) <span class="op">==</span><span class="st"> </span>a <span class="op">-</span><span class="st"> </span>b <span class="op">%.%</span><span class="st"> </span><span class="kw">italic</span>(x) <span class="op">*</span><span class="st"> &quot;,&quot;</span> <span class="op">~</span><span class="st"> </span><span class="er">~</span><span class="kw">italic</span>(r)<span class="op">^</span><span class="dv">2</span> <span class="op">~</span><span class="st"> </span>
<span class="st">            &quot;=&quot;</span> <span class="op">~</span><span class="st"> </span>r2, l)
    }
    
    <span class="kw">as.character</span>(<span class="kw">as.expression</span>(eq))
}</code></pre></div>
<p>after running the chunk above (or executing the function in to memory) you can just plug in you <code>lm</code> object into the new function <code>lm_eqn()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plug in the lm.model</span>
equation &lt;-<span class="st"> </span><span class="kw">lm_eqn</span>(example.model)

<span class="co"># create scatter plot</span>
p &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw">ggplot</span>(<span class="dt">data =</span> example) <span class="op">+</span><span class="st"> </span><span class="co"># plot each data point as a small red open circle</span>
<span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms), <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">shape =</span> <span class="dv">19</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_cowplot</span>()

<span class="co"># adding the regression line</span>
p &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms), <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">method =</span> lm, 
    <span class="dt">level =</span> <span class="fl">0.95</span>)

<span class="co"># adding text from &#39;equation&#39; object above</span>
p &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="kw">annotate</span>(<span class="dt">geom =</span> <span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="dv">20</span>, <span class="dt">y =</span> <span class="dv">5</span>, <span class="dt">label =</span> equation, <span class="dt">parse =</span> T, <span class="dt">size =</span> <span class="dv">4</span>)


<span class="kw">show</span>(p)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-201-1.png" width="672" /></p>
</div>
<div id="placing-plots-side-by-side-in-a-grid" class="section level3">
<h3><span class="header-section-number">6.8.3</span> Placing plots side-by-side in a grid</h3>
<p>You can place two or more plots in a grid using the <code>plot_grid()</code> function from the <code>cowplot</code> library. You can check out an <a href="https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html">intro to cowplot here</a>. Indeed, <code>cowplot</code> does so much more than grid plotting! <code>cowplot</code> can be installed from CRAN, so we can simply:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pacman<span class="op">::</span><span class="kw">p_load</span>(cowplot)</code></pre></div>
<p>The <code>plot.grid()</code> function has several arguments. For now, we’ll just focus on a few, including the <em>list of plots to include</em>, <em>labels for each plot</em>, and their <em>arrangement</em> specified in the number of rows and columns. For the purpose of this example and the next, let’s create a new data set that takes a look at the data above as broken down by men and women:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># read in the data above:</span>
example2 &lt;-<span class="st"> </span><span class="kw">read_table</span>(<span class="st">&quot;https://www.uvm.edu/~dhowell/methods8/DataFiles/Tab9-2.dat&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   ID = col_integer(),
##   Stress = col_integer(),
##   Symptoms = col_integer(),
##   lnSymptoms = col_double()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create a gender vector of 57 women and 50 men:</span>
gender &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;w&quot;</span>, <span class="dv">57</span>), <span class="kw">rep</span>(<span class="st">&quot;m&quot;</span>, <span class="dv">50</span>))

<span class="co"># randomize gender using sample</span>
<span class="kw">set.seed</span>(<span class="dv">1</span>)  <span class="co"># just so we randomize the same</span>
gender &lt;-<span class="st"> </span><span class="kw">sample</span>(gender)

<span class="co"># add gender to our example 2 data.frame</span>
example2<span class="op">$</span>gender &lt;-<span class="st"> </span>gender
<span class="kw">show</span>(example2)</code></pre></div>
<pre><code>## # A tibble: 107 x 5
##       ID Stress Symptoms lnSymptoms gender
##    &lt;int&gt;  &lt;int&gt;    &lt;int&gt;      &lt;dbl&gt; &lt;chr&gt; 
##  1     1     30       99       4.60 w     
##  2     2     27       94       4.54 w     
##  3     3      9       80       4.38 m     
##  4     4     20       70       4.25 m     
##  5     5      3      100       4.61 w     
##  6     6     15      109       4.69 m     
##  7     7      5       62       4.13 m     
##  8     8     10       81       4.39 m     
##  9     9     23       74       4.30 m     
## 10    10     34      121       4.80 w     
## # ... with 97 more rows</code></pre>
<p>Now that we have our data set we can separate out women’s data from men’s data. We’ve done this before using the <code>filter</code> function in <code>dplyr</code>. Another way is to use the <code>subset()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">womenData &lt;-<span class="st"> </span><span class="kw">subset</span>(example2, gender <span class="op">==</span><span class="st"> &quot;w&quot;</span>)
menData &lt;-<span class="st"> </span><span class="kw">subset</span>(example2, gender <span class="op">==</span><span class="st"> &quot;m&quot;</span>)</code></pre></div>
<p>now we can create two separate plots…</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># women plot</span>
wPlot &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw">ggplot</span>(<span class="dt">data =</span> womenData, <span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms)) <span class="op">+</span><span class="st"> </span><span class="co"># plot each data point as a small red open circle</span>
<span class="kw">geom_point</span>(<span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">shape =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">level =</span> <span class="fl">0.95</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_cowplot</span>()

<span class="co"># men plot</span>
mPlot &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw">ggplot</span>(<span class="dt">data =</span> menData, <span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms)) <span class="op">+</span><span class="st"> </span><span class="co"># plot each data point as a small red open circle</span>
<span class="kw">geom_point</span>(<span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">shape =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">level =</span> <span class="fl">0.95</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_cowplot</span>()</code></pre></div>
<p>And plot them side-by-side. To do so, in the <code>cowplot::plot_grid()</code> function I need to enter the name of each plot; the corresponding labels that I choose, and tell <code>plot_grid</code> how many columns there should be in my grid:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot_grid</span>(wPlot, mPlot, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="dt">ncol =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-206-1.png" width="672" /></p>
<p>Note here I’ve labeled the women’s plot “A” and men’s plot “B”. I can label these whatever my hear desires, though typical convention is lettering. I can also stack them vertically by specifying <code>nrow</code> instead of <code>ncol</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot_grid</span>(wPlot, mPlot, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;W&quot;</span>, <span class="st">&quot;M&quot;</span>), <span class="dt">nrow =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-207-1.png" width="672" /></p>
</div>
<div id="two-series-on-the-same-damn-plot" class="section level3">
<h3><span class="header-section-number">6.8.4</span> Two series on the same damn plot</h3>
<p><em>on the same damn plot, on the same damn plot…</em></p>
<p>For our last trick, let’s plot both men and women’s data on the same figure. This can be accomplished by using our original <code>example2</code> data frame and using <code>aes()</code> to specify different shape, colors, and regression lines as a function of gender:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># add color and shape arguments here. These arguements in aes() indicate that</span>
<span class="co"># different shapes and colors should be used for each level of gender:</span>
bothPlot &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw">ggplot</span>(<span class="dt">data =</span> example2, <span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms, <span class="dt">shape =</span> gender, 
    <span class="dt">color =</span> gender)) <span class="op">+</span><span class="st"> </span><span class="co"># only need to specify size here:</span>
<span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">level =</span> <span class="fl">0.95</span>)

<span class="kw">show</span>(bothPlot)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-208-1.png" width="672" /></p>
<p>Of course to make this APA I’ll need to add my <code>cowplot()</code> to the end. I’ll also need to perform a few manual tweaks of the color, <code>scale_color_manual()</code> takes a vector of color names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bothPlot &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw">ggplot</span>(<span class="dt">data =</span> example2, <span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms, <span class="dt">shape =</span> gender, 
    <span class="dt">color =</span> gender)) <span class="op">+</span><span class="st"> </span><span class="co"># only need to specify size here:</span>
<span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">level =</span> <span class="fl">0.95</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">    </span>
<span class="co"># colors, make one series black and the other grey greys have a numeric value 10,</span>
<span class="co"># 20, 30 etc that determines how light:</span>
<span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;grey60&quot;</span>))


<span class="kw">show</span>(bothPlot)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-209-1.png" width="672" /></p>
<p>Note that I can also specify <code>linetype</code> aesthetic in <code>geom_smooth()</code> for different lines:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bothPlot &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw">ggplot</span>(<span class="dt">data =</span> example2, <span class="kw">aes</span>(<span class="dt">x =</span> Stress, <span class="dt">y =</span> lnSymptoms, <span class="dt">shape =</span> gender, 
    <span class="dt">color =</span> gender)) <span class="op">+</span><span class="st"> </span><span class="co"># only need to specify size here:</span>
<span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">level =</span> <span class="fl">0.95</span>, <span class="kw">aes</span>(<span class="dt">linetype =</span> gender)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_cowplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="co"># colors, make one series black and the other grey greys have a numeric value 10,</span>
<span class="co"># 20, 30 etc that determines how light:</span>
<span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;grey60&quot;</span>))


<span class="kw">show</span>(bothPlot)</code></pre></div>
<p><img src="Vignettes_files/figure-html/unnamed-chunk-210-1.png" width="672" /></p>
<p><br> <br> <br> <br> <br> <br> <br> <br> <br></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chi-square-and-associated-methods.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="testing-differences-in-means-t-test.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["Vignettes.pdf", "Vignettes.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
